// GENERATED by nomo_gen v0.1.0-dev.0 — do not edit.
// Source: primary_nomo_button.dart
// ignore_for_file: type=lint, unused_import

import 'package:flutter/widgets.dart';
import 'package:nomo_ui_kit/nomo_ui_kit.dart';
import 'package:nomo_ui_kit/src/annotations/annotations.dart';
import 'package:nomo_ui_kit/src/primitives/nomo_button_core.dart';
import 'primary_nomo_button.dart';

/// Resolved theme for [PrimaryNomoButton].
class PrimaryNomoButtonTheme {
  const PrimaryNomoButtonTheme({
    required this.background,
    required this.foreground,
    required this.padding,
    required this.borderRadius,
    required this.textStyle,
    required this.shadows,
  });

  /// Token-derived defaults (level 5).
  factory PrimaryNomoButtonTheme.defaults(NomoTokens t) =>
      PrimaryNomoButtonTheme(
        background: t.colors.primary,
        foreground: t.colors.onPrimary,
        padding: EdgeInsets.symmetric(
          horizontal: t.sizes.md,
          vertical: t.sizes.sm,
        ),
        borderRadius: t.sizes.borderRadiusMd,
        textStyle: t.typography.b2,
        shadows: t.shadows.none,
      );

  final Color background;
  final Color foreground;
  final EdgeInsetsGeometry padding;
  final BorderRadius borderRadius;
  final TextStyle textStyle;
  final List<BoxShadow> shadows;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static PrimaryNomoButtonTheme of(
    BuildContext context, [
    PrimaryNomoButtonThemeNullable? local,
  ]) {
    final data = NomoTheme.of(context);
    return PrimaryNomoButtonTheme.defaults(data.tokens)
        .merge(data.component<PrimaryNomoButtonThemeNullable>())
        .merge(
          NomoThemeOverride.maybeOf<PrimaryNomoButtonThemeNullable>(context),
        )
        .merge(local);
  }

  PrimaryNomoButtonTheme merge(PrimaryNomoButtonThemeNullable? other) {
    if (other == null) return this;
    return PrimaryNomoButtonTheme(
      background: other.background ?? background,
      foreground: other.foreground ?? foreground,
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
      textStyle: other.textStyle ?? textStyle,
      shadows: other.shadows ?? shadows,
    );
  }

  PrimaryNomoButtonTheme copyWith({
    Color? background,
    Color? foreground,
    EdgeInsetsGeometry? padding,
    BorderRadius? borderRadius,
    TextStyle? textStyle,
    List<BoxShadow>? shadows,
  }) => PrimaryNomoButtonTheme(
    background: background ?? this.background,
    foreground: foreground ?? this.foreground,
    padding: padding ?? this.padding,
    borderRadius: borderRadius ?? this.borderRadius,
    textStyle: textStyle ?? this.textStyle,
    shadows: shadows ?? this.shadows,
  );

  static PrimaryNomoButtonTheme lerp(
    PrimaryNomoButtonTheme a,
    PrimaryNomoButtonTheme b,
    double t,
  ) => PrimaryNomoButtonTheme(
    background: Color.lerp(a.background, b.background, t)!,
    foreground: Color.lerp(a.foreground, b.foreground, t)!,
    padding: t < 0.5 ? a.padding : b.padding,
    borderRadius: t < 0.5 ? a.borderRadius : b.borderRadius,
    textStyle: t < 0.5 ? a.textStyle : b.textStyle,
    shadows: t < 0.5 ? a.shadows : b.shadows,
  );
}

/// Sparse overrides for [PrimaryNomoButtonTheme]; null means "inherit".
class PrimaryNomoButtonThemeNullable {
  const PrimaryNomoButtonThemeNullable({
    this.background,
    this.foreground,
    this.padding,
    this.borderRadius,
    this.textStyle,
    this.shadows,
  });

  final Color? background;
  final Color? foreground;
  final EdgeInsetsGeometry? padding;
  final BorderRadius? borderRadius;
  final TextStyle? textStyle;
  final List<BoxShadow>? shadows;

  PrimaryNomoButtonThemeNullable merge(PrimaryNomoButtonThemeNullable? other) {
    if (other == null) return this;
    return PrimaryNomoButtonThemeNullable(
      background: other.background ?? background,
      foreground: other.foreground ?? foreground,
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
      textStyle: other.textStyle ?? textStyle,
      shadows: other.shadows ?? shadows,
    );
  }
}

/// Overrides [PrimaryNomoButtonTheme] for a subtree (level 2).
class PrimaryNomoButtonThemeOverride extends StatelessWidget {
  const PrimaryNomoButtonThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final PrimaryNomoButtonThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      NomoThemeOverride<PrimaryNomoButtonThemeNullable>(
        data: data,
        child: child,
      );
}
