// GENERATED by nomo_gen v0.1.0-dev.0 — do not edit.
// Source: secondary_nomo_button.dart
// ignore_for_file: type=lint, unused_import

import 'package:flutter/widgets.dart';
import 'package:nomo_ui_kit/nomo_ui_kit.dart';
import 'package:nomo_ui_kit/src/annotations/annotations.dart';
import 'package:nomo_ui_kit/src/primitives/nomo_button_core.dart';
import 'package:nomo_ui_kit/src/theme/nomo_theme.dart';
import 'secondary_nomo_button.dart';

/// Resolved theme for [SecondaryNomoButton].
class SecondaryNomoButtonTheme {
  const SecondaryNomoButtonTheme({
    required this.background,
    required this.foreground,
    required this.borderColor,
    required this.padding,
    required this.borderRadius,
    required this.textStyle,
  });

  /// Token-derived defaults (level 5).
  factory SecondaryNomoButtonTheme.defaults(NomoTokens t) =>
      SecondaryNomoButtonTheme(
        background: t.colors.primaryContainer,
        foreground: t.colors.primary,
        borderColor: t.colors.primary,
        padding: EdgeInsets.symmetric(
          horizontal: t.sizes.md,
          vertical: t.sizes.sm,
        ),
        borderRadius: t.sizes.borderRadiusMd,
        textStyle: t.typography.b2,
      );

  final Color background;
  final Color foreground;
  final Color borderColor;
  final EdgeInsetsGeometry padding;
  final BorderRadius borderRadius;
  final TextStyle textStyle;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static SecondaryNomoButtonTheme of(
    BuildContext context, [
    SecondaryNomoButtonThemeNullable? local,
  ]) {
    final data = NomoTheme.of(context);
    return SecondaryNomoButtonTheme.defaults(data.tokens)
        .merge(data.component<SecondaryNomoButtonThemeNullable>())
        .merge(
          NomoThemeOverride.maybeOf<SecondaryNomoButtonThemeNullable>(context),
        )
        .merge(local);
  }

  SecondaryNomoButtonTheme merge(SecondaryNomoButtonThemeNullable? other) {
    if (other == null) return this;
    return SecondaryNomoButtonTheme(
      background: other.background ?? background,
      foreground: other.foreground ?? foreground,
      borderColor: other.borderColor ?? borderColor,
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
      textStyle: other.textStyle ?? textStyle,
    );
  }

  SecondaryNomoButtonTheme copyWith({
    Color? background,
    Color? foreground,
    Color? borderColor,
    EdgeInsetsGeometry? padding,
    BorderRadius? borderRadius,
    TextStyle? textStyle,
  }) => SecondaryNomoButtonTheme(
    background: background ?? this.background,
    foreground: foreground ?? this.foreground,
    borderColor: borderColor ?? this.borderColor,
    padding: padding ?? this.padding,
    borderRadius: borderRadius ?? this.borderRadius,
    textStyle: textStyle ?? this.textStyle,
  );

  static SecondaryNomoButtonTheme lerp(
    SecondaryNomoButtonTheme a,
    SecondaryNomoButtonTheme b,
    double t,
  ) => SecondaryNomoButtonTheme(
    background: Color.lerp(a.background, b.background, t)!,
    foreground: Color.lerp(a.foreground, b.foreground, t)!,
    borderColor: t < 0.5 ? a.borderColor : b.borderColor,
    padding: t < 0.5 ? a.padding : b.padding,
    borderRadius: t < 0.5 ? a.borderRadius : b.borderRadius,
    textStyle: t < 0.5 ? a.textStyle : b.textStyle,
  );
}

/// Sparse overrides for [SecondaryNomoButtonTheme]; null means "inherit".
class SecondaryNomoButtonThemeNullable {
  const SecondaryNomoButtonThemeNullable({
    this.background,
    this.foreground,
    this.borderColor,
    this.padding,
    this.borderRadius,
    this.textStyle,
  });

  final Color? background;
  final Color? foreground;
  final Color? borderColor;
  final EdgeInsetsGeometry? padding;
  final BorderRadius? borderRadius;
  final TextStyle? textStyle;

  SecondaryNomoButtonThemeNullable merge(
    SecondaryNomoButtonThemeNullable? other,
  ) {
    if (other == null) return this;
    return SecondaryNomoButtonThemeNullable(
      background: other.background ?? background,
      foreground: other.foreground ?? foreground,
      borderColor: other.borderColor ?? borderColor,
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
      textStyle: other.textStyle ?? textStyle,
    );
  }
}

/// Overrides [SecondaryNomoButtonTheme] for a subtree (level 2).
class SecondaryNomoButtonThemeOverride extends StatelessWidget {
  const SecondaryNomoButtonThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final SecondaryNomoButtonThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      NomoThemeOverride<SecondaryNomoButtonThemeNullable>(
        data: data,
        child: child,
      );
}
