// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_info_item.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendInfoItem`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_info_item.dart.
const List<LegendDocEntry> legendInfoItemDocEntries = [
  LegendDocEntry(
    owner: 'LegendInfoItem',
    name: 'labelStyle',
    type: 'TextStyle?',
    doc: '',
    defaultDescription: 't.typography.b3.copyWith(color: t.colors.foreground2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendInfoItem',
    name: 'valueStyle',
    type: 'TextStyle?',
    doc: '',
    defaultDescription: 't.typography.b2.copyWith(color: t.colors.foreground1)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendInfoItem',
    name: 'padding',
    type: 'EdgeInsetsGeometry?',
    doc: '',
    defaultDescription: 'EdgeInsets.symmetric(vertical: t.sizes.xs)',
    group: 'component',
  ),
];
