// GENERATED by legend_gen v0.1.0-dev.0 — do not edit.
// Source: legend_info_item.dart
// ignore_for_file: type=lint, unused_import

import 'legend_info_item.dart';
import 'package:flutter/widgets.dart';
import 'package:legend_ui/legend_ui.dart';
import 'package:legend_ui/src/annotations/annotations.dart';
import 'package:legend_ui/src/theme/legend_theme.dart';

/// Resolved theme for [LegendInfoItem].
class LegendInfoItemTheme {
  const LegendInfoItemTheme({
    required this.labelStyle,
    required this.valueStyle,
    required this.padding,
  });

  /// Token-derived defaults (level 5).
  factory LegendInfoItemTheme.defaults(LegendTokens t) => LegendInfoItemTheme(
    labelStyle: t.typography.b3.copyWith(color: t.colors.foreground2),
    valueStyle: t.typography.b2.copyWith(color: t.colors.foreground1),
    padding: EdgeInsets.symmetric(vertical: t.sizes.xs),
  );

  final TextStyle labelStyle;
  final TextStyle valueStyle;
  final EdgeInsetsGeometry padding;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static LegendInfoItemTheme of(
    BuildContext context, [
    LegendInfoItemThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    return LegendInfoItemTheme.defaults(data.tokens)
        .merge(data.component<LegendInfoItemThemeNullable>())
        .merge(
          LegendThemeOverride.maybeOf<LegendInfoItemThemeNullable>(context),
        )
        .merge(local);
  }

  LegendInfoItemTheme merge(LegendInfoItemThemeNullable? other) {
    if (other == null) return this;
    return LegendInfoItemTheme(
      labelStyle: other.labelStyle ?? labelStyle,
      valueStyle: other.valueStyle ?? valueStyle,
      padding: other.padding ?? padding,
    );
  }

  LegendInfoItemTheme copyWith({
    TextStyle? labelStyle,
    TextStyle? valueStyle,
    EdgeInsetsGeometry? padding,
  }) => LegendInfoItemTheme(
    labelStyle: labelStyle ?? this.labelStyle,
    valueStyle: valueStyle ?? this.valueStyle,
    padding: padding ?? this.padding,
  );

  static LegendInfoItemTheme lerp(
    LegendInfoItemTheme a,
    LegendInfoItemTheme b,
    double t,
  ) => LegendInfoItemTheme(
    labelStyle: t < 0.5 ? a.labelStyle : b.labelStyle,
    valueStyle: t < 0.5 ? a.valueStyle : b.valueStyle,
    padding: t < 0.5 ? a.padding : b.padding,
  );
}

/// Sparse overrides for [LegendInfoItemTheme]; null means "inherit".
class LegendInfoItemThemeNullable {
  const LegendInfoItemThemeNullable({
    this.labelStyle,
    this.valueStyle,
    this.padding,
  });

  final TextStyle? labelStyle;
  final TextStyle? valueStyle;
  final EdgeInsetsGeometry? padding;

  LegendInfoItemThemeNullable merge(LegendInfoItemThemeNullable? other) {
    if (other == null) return this;
    return LegendInfoItemThemeNullable(
      labelStyle: other.labelStyle ?? labelStyle,
      valueStyle: other.valueStyle ?? valueStyle,
      padding: other.padding ?? padding,
    );
  }
}

/// Overrides [LegendInfoItemTheme] for a subtree (level 2).
class LegendInfoItemThemeOverride extends StatelessWidget {
  const LegendInfoItemThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendInfoItemThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendInfoItemThemeNullable>(
        data: data,
        child: child,
      );
}
