// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_slider.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendSlider`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_slider.dart.
const List<LegendDocEntry> legendSliderDocEntries = [
  LegendDocEntry(
    owner: 'LegendSlider',
    name: 'track',
    type: 'Color?',
    doc: 'Color of the unfilled portion of the track.',
    defaultDescription: 'ColorRef.background3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSlider',
    name: 'activeTrack',
    type: 'Color?',
    doc: 'Color of the filled portion, from the start edge to the thumb.',
    defaultDescription: 'ColorRef.primary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSlider',
    name: 'thumb',
    type: 'InteractiveColors?',
    doc:
        'Fill of the draggable thumb per interaction state — hover/press\ntints derive through the state overlays; focus shows as a halo\naround the thumb instead of a fill shift.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSlider',
    name: 'thumb.normal',
    type: 'Color?',
    doc: 'Fill at rest (and the base unset members fall back to).',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSlider',
    name: 'thumb.hovered',
    type: 'Color?',
    doc: 'Fill while a pointer hovers the widget.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSlider',
    name: 'thumb.pressed',
    type: 'Color?',
    doc: 'Fill while the widget is actively pressed.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSlider',
    name: 'thumb.focused',
    type: 'Color?',
    doc: 'Fill while the widget holds keyboard focus.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSlider',
    name: 'thumb.disabled',
    type: 'Color?',
    doc: 'Fill while the widget is disabled.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSlider',
    name: 'trackHeight',
    type: 'double?',
    doc: 'Height of the track bar.',
    defaultDescription: '4',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSlider',
    name: 'thumbSize',
    type: 'double?',
    doc:
        'Diameter of the thumb (the focus halo and the widget\'s own height\nscale from it).',
    defaultDescription: '20',
    group: 'component',
  ),
];
