// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_button_core.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_button_core.dart';

/// Resolved theme for [LegendButtonCore].
class LegendButtonCoreTheme {
  const LegendButtonCoreTheme({
    required this.padding,
    required this.borderRadius,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendButtonCoreTheme.defaults(LegendTokens t) =>
      LegendButtonCoreTheme(
        padding: _padding(t),
        borderRadius: _borderRadius(t),
      );

  final EdgeInsetsGeometry padding;
  final BorderRadius borderRadius;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendButtonCore] first, [LegendButtonCoreThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  static LegendButtonCoreTheme of(
    BuildContext context, [
    LegendButtonCoreThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    return LegendButtonCoreTheme.defaults(data.tokens)
        .merge(
          data.componentOf<LegendButtonCoreThemeNullable>(LegendButtonCore),
        )
        .merge(
          LegendThemeOverride.maybeOf<LegendButtonCoreThemeNullable>(context),
        )
        .merge(local);
  }

  LegendButtonCoreTheme merge(LegendButtonCoreThemeNullable? other) {
    if (other == null) return this;
    return LegendButtonCoreTheme(
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
    );
  }

  LegendButtonCoreTheme copyWith({
    EdgeInsetsGeometry? padding,
    BorderRadius? borderRadius,
  }) => LegendButtonCoreTheme(
    padding: padding ?? this.padding,
    borderRadius: borderRadius ?? this.borderRadius,
  );

  static LegendButtonCoreTheme lerp(
    LegendButtonCoreTheme a,
    LegendButtonCoreTheme b,
    double t,
  ) => LegendButtonCoreTheme(
    padding: t < 0.5 ? a.padding : b.padding,
    borderRadius: t < 0.5 ? a.borderRadius : b.borderRadius,
  );
}

/// Sparse overrides for [LegendButtonCoreTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendButtonCoreThemeNullable {
  const LegendButtonCoreThemeNullable({this.padding, this.borderRadius});

  final EdgeInsetsGeometry? padding;
  final BorderRadius? borderRadius;

  LegendButtonCoreThemeNullable merge(LegendButtonCoreThemeNullable? other) {
    if (other == null) return this;
    return LegendButtonCoreThemeNullable(
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendButtonCoreThemeNullable &&
          other.padding == padding &&
          other.borderRadius == borderRadius;

  @override
  int get hashCode => Object.hashAll([padding, borderRadius]);
}

/// Overrides [LegendButtonCoreTheme] for a subtree (level 2).
class LegendButtonCoreThemeOverride extends StatelessWidget {
  const LegendButtonCoreThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendButtonCoreThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendButtonCoreThemeNullable>(
        data: data,
        child: child,
      );
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendButtonCoreThemeResolve on LegendButtonCore {
  /// [LegendButtonCoreTheme.of] with this widget's constructor params as
  /// level 1.
  LegendButtonCoreTheme _theme(BuildContext context) =>
      LegendButtonCoreTheme.of(
        context,
        LegendButtonCoreThemeNullable(
          padding: padding,
          borderRadius: borderRadius,
        ),
      );
}
