// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_stat.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_stat.dart';

/// Resolved theme for [LegendStat].
class LegendStatTheme {
  const LegendStatTheme({
    required this.labelStyle,
    required this.valueStyle,
    required this.captionStyle,
    required this.positiveColor,
    required this.negativeColor,
    required this.neutralColor,
    required this.spacing,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendStatTheme.defaults(LegendTokens t) => LegendStatTheme(
    labelStyle: _labelStyle(t),
    valueStyle: _valueStyle(t),
    captionStyle: _captionStyle(t),
    positiveColor: ColorRef.secondary(t),
    negativeColor: ColorRef.error(t),
    neutralColor: ColorRef.foreground2(t),
    spacing: SizeRef.xs(t),
  );

  final TextStyle labelStyle;
  final TextStyle valueStyle;
  final TextStyle captionStyle;
  final Color positiveColor;
  final Color negativeColor;
  final Color neutralColor;
  final double spacing;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendStat] first, [LegendStatThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static LegendStatTheme of(
    BuildContext context, [
    LegendStatThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendStatThemeNullable>(context);
    LegendTheme.depend(context, _$LegendStatAspectLabelStyle);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectLabelStyle,
    );
    LegendTheme.depend(context, _$LegendStatAspectValueStyle);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectValueStyle,
    );
    LegendTheme.depend(context, _$LegendStatAspectCaptionStyle);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectCaptionStyle,
    );
    LegendTheme.depend(context, _$LegendStatAspectPositiveColor);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectPositiveColor,
    );
    LegendTheme.depend(context, _$LegendStatAspectNegativeColor);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectNegativeColor,
    );
    LegendTheme.depend(context, _$LegendStatAspectNeutralColor);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectNeutralColor,
    );
    LegendTheme.depend(context, _$LegendStatAspectSpacing);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectSpacing,
    );
    return LegendStatTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendStatThemeNullable>(LegendStat))
        .merge(override)
        .merge(local);
  }

  LegendStatTheme merge(LegendStatThemeNullable? other) {
    if (other == null) return this;
    return LegendStatTheme(
      labelStyle: other.labelStyle ?? labelStyle,
      valueStyle: other.valueStyle ?? valueStyle,
      captionStyle: other.captionStyle ?? captionStyle,
      positiveColor: other.positiveColor ?? positiveColor,
      negativeColor: other.negativeColor ?? negativeColor,
      neutralColor: other.neutralColor ?? neutralColor,
      spacing: other.spacing ?? spacing,
    );
  }

  LegendStatTheme copyWith({
    TextStyle? labelStyle,
    TextStyle? valueStyle,
    TextStyle? captionStyle,
    Color? positiveColor,
    Color? negativeColor,
    Color? neutralColor,
    double? spacing,
  }) => LegendStatTheme(
    labelStyle: labelStyle ?? this.labelStyle,
    valueStyle: valueStyle ?? this.valueStyle,
    captionStyle: captionStyle ?? this.captionStyle,
    positiveColor: positiveColor ?? this.positiveColor,
    negativeColor: negativeColor ?? this.negativeColor,
    neutralColor: neutralColor ?? this.neutralColor,
    spacing: spacing ?? this.spacing,
  );

  static LegendStatTheme lerp(LegendStatTheme a, LegendStatTheme b, double t) =>
      LegendStatTheme(
        labelStyle: t < 0.5 ? a.labelStyle : b.labelStyle,
        valueStyle: t < 0.5 ? a.valueStyle : b.valueStyle,
        captionStyle: t < 0.5 ? a.captionStyle : b.captionStyle,
        positiveColor: t < 0.5 ? a.positiveColor : b.positiveColor,
        negativeColor: t < 0.5 ? a.negativeColor : b.negativeColor,
        neutralColor: t < 0.5 ? a.neutralColor : b.neutralColor,
        spacing: t < 0.5 ? a.spacing : b.spacing,
      );
}

/// Sparse overrides for [LegendStatTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendStatThemeNullable {
  const LegendStatThemeNullable({
    this.labelStyle,
    this.valueStyle,
    this.captionStyle,
    this.positiveColor,
    this.negativeColor,
    this.neutralColor,
    this.spacing,
  });

  final TextStyle? labelStyle;
  final TextStyle? valueStyle;
  final TextStyle? captionStyle;
  final Color? positiveColor;
  final Color? negativeColor;
  final Color? neutralColor;
  final double? spacing;

  LegendStatThemeNullable merge(LegendStatThemeNullable? other) {
    if (other == null) return this;
    return LegendStatThemeNullable(
      labelStyle: other.labelStyle ?? labelStyle,
      valueStyle: other.valueStyle ?? valueStyle,
      captionStyle: other.captionStyle ?? captionStyle,
      positiveColor: other.positiveColor ?? positiveColor,
      negativeColor: other.negativeColor ?? negativeColor,
      neutralColor: other.neutralColor ?? neutralColor,
      spacing: other.spacing ?? spacing,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendStatThemeNullable &&
          other.labelStyle == labelStyle &&
          other.valueStyle == valueStyle &&
          other.captionStyle == captionStyle &&
          other.positiveColor == positiveColor &&
          other.negativeColor == negativeColor &&
          other.neutralColor == neutralColor &&
          other.spacing == spacing;

  @override
  int get hashCode => Object.hashAll([
    labelStyle,
    valueStyle,
    captionStyle,
    positiveColor,
    negativeColor,
    neutralColor,
    spacing,
  ]);
}

/// Overrides [LegendStatTheme] for a subtree (level 2).
class LegendStatThemeOverride extends StatelessWidget {
  const LegendStatThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendStatThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendStatThemeNullable>(data: data, child: child);
}

/// Resolves [LegendStat.labelStyle] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
TextStyle _$LegendStatSelectLabelStyle(LegendThemeData data) =>
    data.componentOf<LegendStatThemeNullable>(LegendStat)?.labelStyle ??
    _labelStyle(data.tokens);
const _$LegendStatAspectLabelStyle = LegendThemeAspect(
  _$LegendStatSelectLabelStyle,
);
Object? _$LegendStatOverrideSelectLabelStyle(LegendStatThemeNullable data) =>
    data.labelStyle;
const _$LegendStatOverrideAspectLabelStyle =
    LegendOverrideAspect<LegendStatThemeNullable>(
      _$LegendStatOverrideSelectLabelStyle,
    );

/// Resolves [LegendStat.valueStyle] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
TextStyle _$LegendStatSelectValueStyle(LegendThemeData data) =>
    data.componentOf<LegendStatThemeNullable>(LegendStat)?.valueStyle ??
    _valueStyle(data.tokens);
const _$LegendStatAspectValueStyle = LegendThemeAspect(
  _$LegendStatSelectValueStyle,
);
Object? _$LegendStatOverrideSelectValueStyle(LegendStatThemeNullable data) =>
    data.valueStyle;
const _$LegendStatOverrideAspectValueStyle =
    LegendOverrideAspect<LegendStatThemeNullable>(
      _$LegendStatOverrideSelectValueStyle,
    );

/// Resolves [LegendStat.captionStyle] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
TextStyle _$LegendStatSelectCaptionStyle(LegendThemeData data) =>
    data.componentOf<LegendStatThemeNullable>(LegendStat)?.captionStyle ??
    _captionStyle(data.tokens);
const _$LegendStatAspectCaptionStyle = LegendThemeAspect(
  _$LegendStatSelectCaptionStyle,
);
Object? _$LegendStatOverrideSelectCaptionStyle(LegendStatThemeNullable data) =>
    data.captionStyle;
const _$LegendStatOverrideAspectCaptionStyle =
    LegendOverrideAspect<LegendStatThemeNullable>(
      _$LegendStatOverrideSelectCaptionStyle,
    );

/// Resolves [LegendStat.positiveColor] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendStatSelectPositiveColor(LegendThemeData data) =>
    data.componentOf<LegendStatThemeNullable>(LegendStat)?.positiveColor ??
    ColorRef.secondary(data.tokens);
const _$LegendStatAspectPositiveColor = LegendThemeAspect(
  _$LegendStatSelectPositiveColor,
);
Object? _$LegendStatOverrideSelectPositiveColor(LegendStatThemeNullable data) =>
    data.positiveColor;
const _$LegendStatOverrideAspectPositiveColor =
    LegendOverrideAspect<LegendStatThemeNullable>(
      _$LegendStatOverrideSelectPositiveColor,
    );

/// Resolves [LegendStat.negativeColor] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendStatSelectNegativeColor(LegendThemeData data) =>
    data.componentOf<LegendStatThemeNullable>(LegendStat)?.negativeColor ??
    ColorRef.error(data.tokens);
const _$LegendStatAspectNegativeColor = LegendThemeAspect(
  _$LegendStatSelectNegativeColor,
);
Object? _$LegendStatOverrideSelectNegativeColor(LegendStatThemeNullable data) =>
    data.negativeColor;
const _$LegendStatOverrideAspectNegativeColor =
    LegendOverrideAspect<LegendStatThemeNullable>(
      _$LegendStatOverrideSelectNegativeColor,
    );

/// Resolves [LegendStat.neutralColor] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendStatSelectNeutralColor(LegendThemeData data) =>
    data.componentOf<LegendStatThemeNullable>(LegendStat)?.neutralColor ??
    ColorRef.foreground2(data.tokens);
const _$LegendStatAspectNeutralColor = LegendThemeAspect(
  _$LegendStatSelectNeutralColor,
);
Object? _$LegendStatOverrideSelectNeutralColor(LegendStatThemeNullable data) =>
    data.neutralColor;
const _$LegendStatOverrideAspectNeutralColor =
    LegendOverrideAspect<LegendStatThemeNullable>(
      _$LegendStatOverrideSelectNeutralColor,
    );

/// Resolves [LegendStat.spacing] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
double _$LegendStatSelectSpacing(LegendThemeData data) =>
    data.componentOf<LegendStatThemeNullable>(LegendStat)?.spacing ??
    SizeRef.xs(data.tokens);
const _$LegendStatAspectSpacing = LegendThemeAspect(_$LegendStatSelectSpacing);
Object? _$LegendStatOverrideSelectSpacing(LegendStatThemeNullable data) =>
    data.spacing;
const _$LegendStatOverrideAspectSpacing =
    LegendOverrideAspect<LegendStatThemeNullable>(
      _$LegendStatOverrideSelectSpacing,
    );

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class LegendStatThemeListenables {
  /// Change stream of the resolved [LegendStatTheme.labelStyle].
  static ValueListenable<TextStyle> labelStyle(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendStatSelectLabelStyle);

  /// Change stream of the resolved [LegendStatTheme.valueStyle].
  static ValueListenable<TextStyle> valueStyle(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendStatSelectValueStyle);

  /// Change stream of the resolved [LegendStatTheme.captionStyle].
  static ValueListenable<TextStyle> captionStyle(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendStatSelectCaptionStyle);

  /// Change stream of the resolved [LegendStatTheme.positiveColor].
  static ValueListenable<Color> positiveColor(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendStatSelectPositiveColor);

  /// Change stream of the resolved [LegendStatTheme.negativeColor].
  static ValueListenable<Color> negativeColor(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendStatSelectNegativeColor);

  /// Change stream of the resolved [LegendStatTheme.neutralColor].
  static ValueListenable<Color> neutralColor(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendStatSelectNeutralColor);

  /// Change stream of the resolved [LegendStatTheme.spacing].
  static ValueListenable<double> spacing(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendStatSelectSpacing);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendStatThemeResolve on LegendStat {
  /// [LegendStatTheme.of] with this widget's constructor params as
  /// level 1.
  LegendStatTheme _theme(BuildContext context) => LegendStatTheme.of(
    context,
    LegendStatThemeNullable(
      labelStyle: labelStyle,
      valueStyle: valueStyle,
      captionStyle: captionStyle,
      positiveColor: positiveColor,
      negativeColor: negativeColor,
      neutralColor: neutralColor,
      spacing: spacing,
    ),
  );

  /// Resolves ONLY [LegendStat.labelStyle] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._labelStyle(context)`).
  TextStyle _labelStyle(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendStatThemeNullable>(context);
    LegendTheme.depend(context, _$LegendStatAspectLabelStyle);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectLabelStyle,
    );
    return labelStyle ??
        override?.labelStyle ??
        _$LegendStatSelectLabelStyle(data);
  }

  /// Resolves ONLY [LegendStat.valueStyle] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._valueStyle(context)`).
  TextStyle _valueStyle(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendStatThemeNullable>(context);
    LegendTheme.depend(context, _$LegendStatAspectValueStyle);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectValueStyle,
    );
    return valueStyle ??
        override?.valueStyle ??
        _$LegendStatSelectValueStyle(data);
  }

  /// Resolves ONLY [LegendStat.captionStyle] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._captionStyle(context)`).
  TextStyle _captionStyle(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendStatThemeNullable>(context);
    LegendTheme.depend(context, _$LegendStatAspectCaptionStyle);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectCaptionStyle,
    );
    return captionStyle ??
        override?.captionStyle ??
        _$LegendStatSelectCaptionStyle(data);
  }

  /// Resolves ONLY [LegendStat.positiveColor] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._positiveColor(context)`).
  Color _positiveColor(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendStatThemeNullable>(context);
    LegendTheme.depend(context, _$LegendStatAspectPositiveColor);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectPositiveColor,
    );
    return positiveColor ??
        override?.positiveColor ??
        _$LegendStatSelectPositiveColor(data);
  }

  /// Resolves ONLY [LegendStat.negativeColor] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._negativeColor(context)`).
  Color _negativeColor(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendStatThemeNullable>(context);
    LegendTheme.depend(context, _$LegendStatAspectNegativeColor);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectNegativeColor,
    );
    return negativeColor ??
        override?.negativeColor ??
        _$LegendStatSelectNegativeColor(data);
  }

  /// Resolves ONLY [LegendStat.neutralColor] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._neutralColor(context)`).
  Color _neutralColor(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendStatThemeNullable>(context);
    LegendTheme.depend(context, _$LegendStatAspectNeutralColor);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectNeutralColor,
    );
    return neutralColor ??
        override?.neutralColor ??
        _$LegendStatSelectNeutralColor(data);
  }

  /// Resolves ONLY [LegendStat.spacing] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._spacing(context)`).
  double _spacing(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendStatThemeNullable>(context);
    LegendTheme.depend(context, _$LegendStatAspectSpacing);
    LegendThemeOverride.depend<LegendStatThemeNullable>(
      context,
      _$LegendStatOverrideAspectSpacing,
    );
    return spacing ?? override?.spacing ?? _$LegendStatSelectSpacing(data);
  }
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class LegendStat extends
/// _$LegendStatBase` receives the resolved
/// [LegendStatTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$LegendStatBase extends LegendStatelessWidget<LegendStatTheme> {
  const _$LegendStatBase({super.key});

  TextStyle? get labelStyle;
  TextStyle? get valueStyle;
  TextStyle? get captionStyle;
  Color? get positiveColor;
  Color? get negativeColor;
  Color? get neutralColor;
  double? get spacing;

  @override
  LegendStatTheme resolveThemeOf(BuildContext context) => LegendStatTheme.of(
    context,
    LegendStatThemeNullable(
      labelStyle: labelStyle,
      valueStyle: valueStyle,
      captionStyle: captionStyle,
      positiveColor: positiveColor,
      negativeColor: negativeColor,
      neutralColor: neutralColor,
      spacing: spacing,
    ),
  );
}
