// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_loading.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_loading.dart';

/// Resolved theme for [LegendLoading].
class LegendLoadingTheme {
  const LegendLoadingTheme({
    required this.color,
    required this.size,
    required this.strokeWidth,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendLoadingTheme.defaults(LegendTokens t) =>
      LegendLoadingTheme(color: ColorRef.primary(t), size: 24, strokeWidth: 3);

  final Color color;
  final double size;
  final double strokeWidth;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendLoading] first, [LegendLoadingThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  static LegendLoadingTheme of(
    BuildContext context, [
    LegendLoadingThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    final resolved = LegendLoadingTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendLoadingThemeNullable>(LegendLoading))
        .merge(LegendThemeOverride.maybeOf<LegendLoadingThemeNullable>(context))
        .merge(local);
    return resolved;
  }

  LegendLoadingTheme merge(LegendLoadingThemeNullable? other) {
    if (other == null) return this;
    return LegendLoadingTheme(
      color: other.color ?? color,
      size: other.size ?? size,
      strokeWidth: other.strokeWidth ?? strokeWidth,
    );
  }

  LegendLoadingTheme copyWith({
    Color? color,
    double? size,
    double? strokeWidth,
  }) => LegendLoadingTheme(
    color: color ?? this.color,
    size: size ?? this.size,
    strokeWidth: strokeWidth ?? this.strokeWidth,
  );

  static LegendLoadingTheme lerp(
    LegendLoadingTheme a,
    LegendLoadingTheme b,
    double t,
  ) => LegendLoadingTheme(
    color: t < 0.5 ? a.color : b.color,
    size: t < 0.5 ? a.size : b.size,
    strokeWidth: t < 0.5 ? a.strokeWidth : b.strokeWidth,
  );
}

/// Sparse overrides for [LegendLoadingTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendLoadingThemeNullable {
  const LegendLoadingThemeNullable({this.color, this.size, this.strokeWidth});

  final Color? color;
  final double? size;
  final double? strokeWidth;

  LegendLoadingThemeNullable merge(LegendLoadingThemeNullable? other) {
    if (other == null) return this;
    return LegendLoadingThemeNullable(
      color: other.color ?? color,
      size: other.size ?? size,
      strokeWidth: other.strokeWidth ?? strokeWidth,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendLoadingThemeNullable &&
          other.color == color &&
          other.size == size &&
          other.strokeWidth == strokeWidth;

  @override
  int get hashCode => Object.hashAll([color, size, strokeWidth]);
}

/// Overrides [LegendLoadingTheme] for a subtree (level 2).
class LegendLoadingThemeOverride extends StatelessWidget {
  const LegendLoadingThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendLoadingThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendLoadingThemeNullable>(data: data, child: child);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendLoadingThemeResolve on LegendLoading {
  /// [LegendLoadingTheme.of] with this widget's constructor params as
  /// level 1.
  LegendLoadingTheme _theme(BuildContext context) => LegendLoadingTheme.of(
    context,
    LegendLoadingThemeNullable(
      color: color,
      size: size,
      strokeWidth: strokeWidth,
    ),
  );
}
