// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_banner.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_banner.dart';

/// Resolved theme for [LegendBanner].
class LegendBannerTheme {
  const LegendBannerTheme({
    required this.infoBackground,
    required this.infoForeground,
    required this.successBackground,
    required this.successForeground,
    required this.warningBackground,
    required this.warningForeground,
    required this.errorBackground,
    required this.errorForeground,
    required this.padding,
    required this.borderRadius,
    required this.iconSize,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendBannerTheme.defaults(LegendTokens t) => LegendBannerTheme(
    infoBackground: _infoBackground(t),
    infoForeground: ColorRef.primary(t),
    successBackground: _successBackground(t),
    successForeground: ColorRef.secondary(t),
    warningBackground: _warningBackground(t),
    warningForeground: _warningForeground(t),
    errorBackground: _errorBackground(t),
    errorForeground: ColorRef.error(t),
    padding: _padding(t),
    borderRadius: _borderRadius(t),
    iconSize: SizeRef.iconMd(t),
  );

  final Color infoBackground;
  final Color infoForeground;
  final Color successBackground;
  final Color successForeground;
  final Color warningBackground;
  final Color warningForeground;
  final Color errorBackground;
  final Color errorForeground;
  final EdgeInsetsGeometry padding;
  final BorderRadius borderRadius;
  final double iconSize;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendBanner] first, [LegendBannerThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static LegendBannerTheme of(
    BuildContext context, [
    LegendBannerThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectInfoBackground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectInfoBackground,
    );
    LegendTheme.depend(context, _$LegendBannerAspectInfoForeground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectInfoForeground,
    );
    LegendTheme.depend(context, _$LegendBannerAspectSuccessBackground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectSuccessBackground,
    );
    LegendTheme.depend(context, _$LegendBannerAspectSuccessForeground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectSuccessForeground,
    );
    LegendTheme.depend(context, _$LegendBannerAspectWarningBackground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectWarningBackground,
    );
    LegendTheme.depend(context, _$LegendBannerAspectWarningForeground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectWarningForeground,
    );
    LegendTheme.depend(context, _$LegendBannerAspectErrorBackground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectErrorBackground,
    );
    LegendTheme.depend(context, _$LegendBannerAspectErrorForeground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectErrorForeground,
    );
    LegendTheme.depend(context, _$LegendBannerAspectPadding);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectPadding,
    );
    LegendTheme.depend(context, _$LegendBannerAspectBorderRadius);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectBorderRadius,
    );
    LegendTheme.depend(context, _$LegendBannerAspectIconSize);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectIconSize,
    );
    return LegendBannerTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendBannerThemeNullable>(LegendBanner))
        .merge(override)
        .merge(local);
  }

  LegendBannerTheme merge(LegendBannerThemeNullable? other) {
    if (other == null) return this;
    return LegendBannerTheme(
      infoBackground: other.infoBackground ?? infoBackground,
      infoForeground: other.infoForeground ?? infoForeground,
      successBackground: other.successBackground ?? successBackground,
      successForeground: other.successForeground ?? successForeground,
      warningBackground: other.warningBackground ?? warningBackground,
      warningForeground: other.warningForeground ?? warningForeground,
      errorBackground: other.errorBackground ?? errorBackground,
      errorForeground: other.errorForeground ?? errorForeground,
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
      iconSize: other.iconSize ?? iconSize,
    );
  }

  LegendBannerTheme copyWith({
    Color? infoBackground,
    Color? infoForeground,
    Color? successBackground,
    Color? successForeground,
    Color? warningBackground,
    Color? warningForeground,
    Color? errorBackground,
    Color? errorForeground,
    EdgeInsetsGeometry? padding,
    BorderRadius? borderRadius,
    double? iconSize,
  }) => LegendBannerTheme(
    infoBackground: infoBackground ?? this.infoBackground,
    infoForeground: infoForeground ?? this.infoForeground,
    successBackground: successBackground ?? this.successBackground,
    successForeground: successForeground ?? this.successForeground,
    warningBackground: warningBackground ?? this.warningBackground,
    warningForeground: warningForeground ?? this.warningForeground,
    errorBackground: errorBackground ?? this.errorBackground,
    errorForeground: errorForeground ?? this.errorForeground,
    padding: padding ?? this.padding,
    borderRadius: borderRadius ?? this.borderRadius,
    iconSize: iconSize ?? this.iconSize,
  );

  static LegendBannerTheme lerp(
    LegendBannerTheme a,
    LegendBannerTheme b,
    double t,
  ) => LegendBannerTheme(
    infoBackground: t < 0.5 ? a.infoBackground : b.infoBackground,
    infoForeground: t < 0.5 ? a.infoForeground : b.infoForeground,
    successBackground: t < 0.5 ? a.successBackground : b.successBackground,
    successForeground: t < 0.5 ? a.successForeground : b.successForeground,
    warningBackground: t < 0.5 ? a.warningBackground : b.warningBackground,
    warningForeground: t < 0.5 ? a.warningForeground : b.warningForeground,
    errorBackground: t < 0.5 ? a.errorBackground : b.errorBackground,
    errorForeground: t < 0.5 ? a.errorForeground : b.errorForeground,
    padding: t < 0.5 ? a.padding : b.padding,
    borderRadius: t < 0.5 ? a.borderRadius : b.borderRadius,
    iconSize: t < 0.5 ? a.iconSize : b.iconSize,
  );
}

/// Sparse overrides for [LegendBannerTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendBannerThemeNullable {
  const LegendBannerThemeNullable({
    this.infoBackground,
    this.infoForeground,
    this.successBackground,
    this.successForeground,
    this.warningBackground,
    this.warningForeground,
    this.errorBackground,
    this.errorForeground,
    this.padding,
    this.borderRadius,
    this.iconSize,
  });

  final Color? infoBackground;
  final Color? infoForeground;
  final Color? successBackground;
  final Color? successForeground;
  final Color? warningBackground;
  final Color? warningForeground;
  final Color? errorBackground;
  final Color? errorForeground;
  final EdgeInsetsGeometry? padding;
  final BorderRadius? borderRadius;
  final double? iconSize;

  LegendBannerThemeNullable merge(LegendBannerThemeNullable? other) {
    if (other == null) return this;
    return LegendBannerThemeNullable(
      infoBackground: other.infoBackground ?? infoBackground,
      infoForeground: other.infoForeground ?? infoForeground,
      successBackground: other.successBackground ?? successBackground,
      successForeground: other.successForeground ?? successForeground,
      warningBackground: other.warningBackground ?? warningBackground,
      warningForeground: other.warningForeground ?? warningForeground,
      errorBackground: other.errorBackground ?? errorBackground,
      errorForeground: other.errorForeground ?? errorForeground,
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
      iconSize: other.iconSize ?? iconSize,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendBannerThemeNullable &&
          other.infoBackground == infoBackground &&
          other.infoForeground == infoForeground &&
          other.successBackground == successBackground &&
          other.successForeground == successForeground &&
          other.warningBackground == warningBackground &&
          other.warningForeground == warningForeground &&
          other.errorBackground == errorBackground &&
          other.errorForeground == errorForeground &&
          other.padding == padding &&
          other.borderRadius == borderRadius &&
          other.iconSize == iconSize;

  @override
  int get hashCode => Object.hashAll([
    infoBackground,
    infoForeground,
    successBackground,
    successForeground,
    warningBackground,
    warningForeground,
    errorBackground,
    errorForeground,
    padding,
    borderRadius,
    iconSize,
  ]);
}

/// Overrides [LegendBannerTheme] for a subtree (level 2).
class LegendBannerThemeOverride extends StatelessWidget {
  const LegendBannerThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendBannerThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendBannerThemeNullable>(data: data, child: child);
}

/// Resolves [LegendBanner.infoBackground] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendBannerSelectInfoBackground(LegendThemeData data) =>
    data.componentOf<LegendBannerThemeNullable>(LegendBanner)?.infoBackground ??
    _infoBackground(data.tokens);
const _$LegendBannerAspectInfoBackground = LegendThemeAspect(
  _$LegendBannerSelectInfoBackground,
);
Object? _$LegendBannerOverrideSelectInfoBackground(
  LegendBannerThemeNullable data,
) => data.infoBackground;
const _$LegendBannerOverrideAspectInfoBackground =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectInfoBackground,
    );

/// Resolves [LegendBanner.infoForeground] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendBannerSelectInfoForeground(LegendThemeData data) =>
    data.componentOf<LegendBannerThemeNullable>(LegendBanner)?.infoForeground ??
    ColorRef.primary(data.tokens);
const _$LegendBannerAspectInfoForeground = LegendThemeAspect(
  _$LegendBannerSelectInfoForeground,
);
Object? _$LegendBannerOverrideSelectInfoForeground(
  LegendBannerThemeNullable data,
) => data.infoForeground;
const _$LegendBannerOverrideAspectInfoForeground =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectInfoForeground,
    );

/// Resolves [LegendBanner.successBackground] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendBannerSelectSuccessBackground(LegendThemeData data) =>
    data
        .componentOf<LegendBannerThemeNullable>(LegendBanner)
        ?.successBackground ??
    _successBackground(data.tokens);
const _$LegendBannerAspectSuccessBackground = LegendThemeAspect(
  _$LegendBannerSelectSuccessBackground,
);
Object? _$LegendBannerOverrideSelectSuccessBackground(
  LegendBannerThemeNullable data,
) => data.successBackground;
const _$LegendBannerOverrideAspectSuccessBackground =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectSuccessBackground,
    );

/// Resolves [LegendBanner.successForeground] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendBannerSelectSuccessForeground(LegendThemeData data) =>
    data
        .componentOf<LegendBannerThemeNullable>(LegendBanner)
        ?.successForeground ??
    ColorRef.secondary(data.tokens);
const _$LegendBannerAspectSuccessForeground = LegendThemeAspect(
  _$LegendBannerSelectSuccessForeground,
);
Object? _$LegendBannerOverrideSelectSuccessForeground(
  LegendBannerThemeNullable data,
) => data.successForeground;
const _$LegendBannerOverrideAspectSuccessForeground =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectSuccessForeground,
    );

/// Resolves [LegendBanner.warningBackground] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendBannerSelectWarningBackground(LegendThemeData data) =>
    data
        .componentOf<LegendBannerThemeNullable>(LegendBanner)
        ?.warningBackground ??
    _warningBackground(data.tokens);
const _$LegendBannerAspectWarningBackground = LegendThemeAspect(
  _$LegendBannerSelectWarningBackground,
);
Object? _$LegendBannerOverrideSelectWarningBackground(
  LegendBannerThemeNullable data,
) => data.warningBackground;
const _$LegendBannerOverrideAspectWarningBackground =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectWarningBackground,
    );

/// Resolves [LegendBanner.warningForeground] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendBannerSelectWarningForeground(LegendThemeData data) =>
    data
        .componentOf<LegendBannerThemeNullable>(LegendBanner)
        ?.warningForeground ??
    _warningForeground(data.tokens);
const _$LegendBannerAspectWarningForeground = LegendThemeAspect(
  _$LegendBannerSelectWarningForeground,
);
Object? _$LegendBannerOverrideSelectWarningForeground(
  LegendBannerThemeNullable data,
) => data.warningForeground;
const _$LegendBannerOverrideAspectWarningForeground =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectWarningForeground,
    );

/// Resolves [LegendBanner.errorBackground] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendBannerSelectErrorBackground(LegendThemeData data) =>
    data
        .componentOf<LegendBannerThemeNullable>(LegendBanner)
        ?.errorBackground ??
    _errorBackground(data.tokens);
const _$LegendBannerAspectErrorBackground = LegendThemeAspect(
  _$LegendBannerSelectErrorBackground,
);
Object? _$LegendBannerOverrideSelectErrorBackground(
  LegendBannerThemeNullable data,
) => data.errorBackground;
const _$LegendBannerOverrideAspectErrorBackground =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectErrorBackground,
    );

/// Resolves [LegendBanner.errorForeground] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendBannerSelectErrorForeground(LegendThemeData data) =>
    data
        .componentOf<LegendBannerThemeNullable>(LegendBanner)
        ?.errorForeground ??
    ColorRef.error(data.tokens);
const _$LegendBannerAspectErrorForeground = LegendThemeAspect(
  _$LegendBannerSelectErrorForeground,
);
Object? _$LegendBannerOverrideSelectErrorForeground(
  LegendBannerThemeNullable data,
) => data.errorForeground;
const _$LegendBannerOverrideAspectErrorForeground =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectErrorForeground,
    );

/// Resolves [LegendBanner.padding] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
EdgeInsetsGeometry _$LegendBannerSelectPadding(LegendThemeData data) =>
    data.componentOf<LegendBannerThemeNullable>(LegendBanner)?.padding ??
    _padding(data.tokens);
const _$LegendBannerAspectPadding = LegendThemeAspect(
  _$LegendBannerSelectPadding,
);
Object? _$LegendBannerOverrideSelectPadding(LegendBannerThemeNullable data) =>
    data.padding;
const _$LegendBannerOverrideAspectPadding =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectPadding,
    );

/// Resolves [LegendBanner.borderRadius] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
BorderRadius _$LegendBannerSelectBorderRadius(LegendThemeData data) =>
    data.componentOf<LegendBannerThemeNullable>(LegendBanner)?.borderRadius ??
    _borderRadius(data.tokens);
const _$LegendBannerAspectBorderRadius = LegendThemeAspect(
  _$LegendBannerSelectBorderRadius,
);
Object? _$LegendBannerOverrideSelectBorderRadius(
  LegendBannerThemeNullable data,
) => data.borderRadius;
const _$LegendBannerOverrideAspectBorderRadius =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectBorderRadius,
    );

/// Resolves [LegendBanner.iconSize] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
double _$LegendBannerSelectIconSize(LegendThemeData data) =>
    data.componentOf<LegendBannerThemeNullable>(LegendBanner)?.iconSize ??
    SizeRef.iconMd(data.tokens);
const _$LegendBannerAspectIconSize = LegendThemeAspect(
  _$LegendBannerSelectIconSize,
);
Object? _$LegendBannerOverrideSelectIconSize(LegendBannerThemeNullable data) =>
    data.iconSize;
const _$LegendBannerOverrideAspectIconSize =
    LegendOverrideAspect<LegendBannerThemeNullable>(
      _$LegendBannerOverrideSelectIconSize,
    );

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class LegendBannerThemeListenables {
  /// Change stream of the resolved [LegendBannerTheme.infoBackground].
  static ValueListenable<Color> infoBackground(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectInfoBackground);

  /// Change stream of the resolved [LegendBannerTheme.infoForeground].
  static ValueListenable<Color> infoForeground(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectInfoForeground);

  /// Change stream of the resolved [LegendBannerTheme.successBackground].
  static ValueListenable<Color> successBackground(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectSuccessBackground);

  /// Change stream of the resolved [LegendBannerTheme.successForeground].
  static ValueListenable<Color> successForeground(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectSuccessForeground);

  /// Change stream of the resolved [LegendBannerTheme.warningBackground].
  static ValueListenable<Color> warningBackground(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectWarningBackground);

  /// Change stream of the resolved [LegendBannerTheme.warningForeground].
  static ValueListenable<Color> warningForeground(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectWarningForeground);

  /// Change stream of the resolved [LegendBannerTheme.errorBackground].
  static ValueListenable<Color> errorBackground(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectErrorBackground);

  /// Change stream of the resolved [LegendBannerTheme.errorForeground].
  static ValueListenable<Color> errorForeground(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectErrorForeground);

  /// Change stream of the resolved [LegendBannerTheme.padding].
  static ValueListenable<EdgeInsetsGeometry> padding(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectPadding);

  /// Change stream of the resolved [LegendBannerTheme.borderRadius].
  static ValueListenable<BorderRadius> borderRadius(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectBorderRadius);

  /// Change stream of the resolved [LegendBannerTheme.iconSize].
  static ValueListenable<double> iconSize(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendBannerSelectIconSize);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendBannerThemeResolve on LegendBanner {
  /// [LegendBannerTheme.of] with this widget's constructor params as
  /// level 1.
  LegendBannerTheme _theme(BuildContext context) => LegendBannerTheme.of(
    context,
    LegendBannerThemeNullable(
      infoBackground: infoBackground,
      infoForeground: infoForeground,
      successBackground: successBackground,
      successForeground: successForeground,
      warningBackground: warningBackground,
      warningForeground: warningForeground,
      errorBackground: errorBackground,
      errorForeground: errorForeground,
      padding: padding,
      borderRadius: borderRadius,
      iconSize: iconSize,
    ),
  );

  /// Resolves ONLY [LegendBanner.infoBackground] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._infoBackground(context)`).
  Color _infoBackground(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectInfoBackground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectInfoBackground,
    );
    return infoBackground ??
        override?.infoBackground ??
        _$LegendBannerSelectInfoBackground(data);
  }

  /// Resolves ONLY [LegendBanner.infoForeground] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._infoForeground(context)`).
  Color _infoForeground(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectInfoForeground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectInfoForeground,
    );
    return infoForeground ??
        override?.infoForeground ??
        _$LegendBannerSelectInfoForeground(data);
  }

  /// Resolves ONLY [LegendBanner.successBackground] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._successBackground(context)`).
  Color _successBackground(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectSuccessBackground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectSuccessBackground,
    );
    return successBackground ??
        override?.successBackground ??
        _$LegendBannerSelectSuccessBackground(data);
  }

  /// Resolves ONLY [LegendBanner.successForeground] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._successForeground(context)`).
  Color _successForeground(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectSuccessForeground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectSuccessForeground,
    );
    return successForeground ??
        override?.successForeground ??
        _$LegendBannerSelectSuccessForeground(data);
  }

  /// Resolves ONLY [LegendBanner.warningBackground] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._warningBackground(context)`).
  Color _warningBackground(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectWarningBackground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectWarningBackground,
    );
    return warningBackground ??
        override?.warningBackground ??
        _$LegendBannerSelectWarningBackground(data);
  }

  /// Resolves ONLY [LegendBanner.warningForeground] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._warningForeground(context)`).
  Color _warningForeground(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectWarningForeground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectWarningForeground,
    );
    return warningForeground ??
        override?.warningForeground ??
        _$LegendBannerSelectWarningForeground(data);
  }

  /// Resolves ONLY [LegendBanner.errorBackground] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._errorBackground(context)`).
  Color _errorBackground(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectErrorBackground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectErrorBackground,
    );
    return errorBackground ??
        override?.errorBackground ??
        _$LegendBannerSelectErrorBackground(data);
  }

  /// Resolves ONLY [LegendBanner.errorForeground] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._errorForeground(context)`).
  Color _errorForeground(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectErrorForeground);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectErrorForeground,
    );
    return errorForeground ??
        override?.errorForeground ??
        _$LegendBannerSelectErrorForeground(data);
  }

  /// Resolves ONLY [LegendBanner.padding] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._padding(context)`).
  EdgeInsetsGeometry _padding(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectPadding);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectPadding,
    );
    return padding ?? override?.padding ?? _$LegendBannerSelectPadding(data);
  }

  /// Resolves ONLY [LegendBanner.borderRadius] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._borderRadius(context)`).
  BorderRadius _borderRadius(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectBorderRadius);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectBorderRadius,
    );
    return borderRadius ??
        override?.borderRadius ??
        _$LegendBannerSelectBorderRadius(data);
  }

  /// Resolves ONLY [LegendBanner.iconSize] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._iconSize(context)`).
  double _iconSize(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendBannerThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendBannerAspectIconSize);
    LegendThemeOverride.depend<LegendBannerThemeNullable>(
      context,
      _$LegendBannerOverrideAspectIconSize,
    );
    return iconSize ?? override?.iconSize ?? _$LegendBannerSelectIconSize(data);
  }
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class LegendBanner extends
/// _$LegendBannerBase` receives the resolved
/// [LegendBannerTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$LegendBannerBase
    extends LegendStatelessWidget<LegendBannerTheme> {
  const _$LegendBannerBase({super.key});

  Color? get infoBackground;
  Color? get infoForeground;
  Color? get successBackground;
  Color? get successForeground;
  Color? get warningBackground;
  Color? get warningForeground;
  Color? get errorBackground;
  Color? get errorForeground;
  EdgeInsetsGeometry? get padding;
  BorderRadius? get borderRadius;
  double? get iconSize;

  @override
  LegendBannerTheme resolveThemeOf(BuildContext context) =>
      LegendBannerTheme.of(
        context,
        LegendBannerThemeNullable(
          infoBackground: infoBackground,
          infoForeground: infoForeground,
          successBackground: successBackground,
          successForeground: successForeground,
          warningBackground: warningBackground,
          warningForeground: warningForeground,
          errorBackground: errorBackground,
          errorForeground: errorForeground,
          padding: padding,
          borderRadius: borderRadius,
          iconSize: iconSize,
        ),
      );
}
