// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_pin_field.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendPinField`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_pin_field.dart.
const List<LegendDocEntry> legendPinFieldDocEntries = [
  LegendDocEntry(
    owner: 'LegendPinField',
    name: 'cellSize',
    type: 'Size?',
    doc: 'Width and height of one character cell.',
    defaultDescription: 'Size(t.sizes.xl + t.sizes.sm, t.sizes.xxl)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendPinField',
    name: 'cellSpacing',
    type: 'double?',
    doc: 'Gap between adjacent cells.',
    defaultDescription: 'SizeRef.sm',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendPinField',
    name: 'cellBackground',
    type: 'Color?',
    doc: 'Fill of each cell.',
    defaultDescription: 'ColorRef.background1',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendPinField',
    name: 'borderColor',
    type: 'Color?',
    doc: 'Cell border while inactive.',
    defaultDescription: 'ColorRef.background3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendPinField',
    name: 'focusedBorderColor',
    type: 'Color?',
    doc:
        'Border of the active cell (the one the next character lands in) while\nthe field is focused.',
    defaultDescription: 'ColorRef.primary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendPinField',
    name: 'errorBorderColor',
    type: 'Color?',
    doc: 'Cell border while [errorText] is set.',
    defaultDescription: 'ColorRef.error',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendPinField',
    name: 'textStyle',
    type: 'TextStyle?',
    doc: 'Style of the entered characters (recolored to the foreground).',
    defaultDescription: 'TextRef.h3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendPinField',
    name: 'borderRadius',
    type: 'BorderRadius?',
    doc: 'Corner rounding of each cell.',
    defaultDescription: 't.sizes.borderRadiusMd',
    group: 'component',
  ),
];
