// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: balance_card.dart
// ignore_for_file: type=lint, unused_element
part of 'balance_card.dart';

/// Resolved theme for [BalanceCard].
class BalanceCardTheme {
  const BalanceCardTheme({
    required this.background,
    required this.accent,
    required this.padding,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory BalanceCardTheme.defaults(LegendTokens t) => BalanceCardTheme(
    background: ColorRef.surface(t),
    accent: ColorRef.secondary(t),
    padding: _padding(t),
  );

  final Color background;
  final Color accent;
  final EdgeInsetsGeometry padding;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [BalanceCard] first, [BalanceCardThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static BalanceCardTheme of(
    BuildContext context, [
    BalanceCardThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<BalanceCardThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$BalanceCardAspectBackground);
    LegendThemeOverride.depend<BalanceCardThemeNullable>(
      context,
      _$BalanceCardOverrideAspectBackground,
    );
    LegendTheme.depend(context, _$BalanceCardAspectAccent);
    LegendThemeOverride.depend<BalanceCardThemeNullable>(
      context,
      _$BalanceCardOverrideAspectAccent,
    );
    LegendTheme.depend(context, _$BalanceCardAspectPadding);
    LegendThemeOverride.depend<BalanceCardThemeNullable>(
      context,
      _$BalanceCardOverrideAspectPadding,
    );
    return BalanceCardTheme.defaults(data.tokens)
        .merge(data.componentOf<BalanceCardThemeNullable>(BalanceCard))
        .merge(override)
        .merge(local);
  }

  BalanceCardTheme merge(BalanceCardThemeNullable? other) {
    if (other == null) return this;
    return BalanceCardTheme(
      background: other.background ?? background,
      accent: other.accent ?? accent,
      padding: other.padding ?? padding,
    );
  }

  BalanceCardTheme copyWith({
    Color? background,
    Color? accent,
    EdgeInsetsGeometry? padding,
  }) => BalanceCardTheme(
    background: background ?? this.background,
    accent: accent ?? this.accent,
    padding: padding ?? this.padding,
  );

  static BalanceCardTheme lerp(
    BalanceCardTheme a,
    BalanceCardTheme b,
    double t,
  ) => BalanceCardTheme(
    background: Color.lerp(a.background, b.background, t)!,
    accent: t < 0.5 ? a.accent : b.accent,
    padding: t < 0.5 ? a.padding : b.padding,
  );
}

/// Sparse overrides for [BalanceCardTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class BalanceCardThemeNullable {
  const BalanceCardThemeNullable({this.background, this.accent, this.padding});

  final Color? background;
  final Color? accent;
  final EdgeInsetsGeometry? padding;

  BalanceCardThemeNullable merge(BalanceCardThemeNullable? other) {
    if (other == null) return this;
    return BalanceCardThemeNullable(
      background: other.background ?? background,
      accent: other.accent ?? accent,
      padding: other.padding ?? padding,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BalanceCardThemeNullable &&
          other.background == background &&
          other.accent == accent &&
          other.padding == padding;

  @override
  int get hashCode => Object.hashAll([background, accent, padding]);
}

/// Overrides [BalanceCardTheme] for a subtree (level 2).
class BalanceCardThemeOverride extends StatelessWidget {
  const BalanceCardThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final BalanceCardThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<BalanceCardThemeNullable>(data: data, child: child);
}

/// Resolves [BalanceCard.background] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$BalanceCardSelectBackground(LegendThemeData data) =>
    data.componentOf<BalanceCardThemeNullable>(BalanceCard)?.background ??
    ColorRef.surface(data.tokens);
const _$BalanceCardAspectBackground = LegendThemeAspect(
  _$BalanceCardSelectBackground,
);
Object? _$BalanceCardOverrideSelectBackground(BalanceCardThemeNullable data) =>
    data.background;
const _$BalanceCardOverrideAspectBackground =
    LegendOverrideAspect<BalanceCardThemeNullable>(
      _$BalanceCardOverrideSelectBackground,
    );

/// Resolves [BalanceCard.accent] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$BalanceCardSelectAccent(LegendThemeData data) =>
    data.componentOf<BalanceCardThemeNullable>(BalanceCard)?.accent ??
    ColorRef.secondary(data.tokens);
const _$BalanceCardAspectAccent = LegendThemeAspect(_$BalanceCardSelectAccent);
Object? _$BalanceCardOverrideSelectAccent(BalanceCardThemeNullable data) =>
    data.accent;
const _$BalanceCardOverrideAspectAccent =
    LegendOverrideAspect<BalanceCardThemeNullable>(
      _$BalanceCardOverrideSelectAccent,
    );

/// Resolves [BalanceCard.padding] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
EdgeInsetsGeometry _$BalanceCardSelectPadding(LegendThemeData data) =>
    data.componentOf<BalanceCardThemeNullable>(BalanceCard)?.padding ??
    _padding(data.tokens);
const _$BalanceCardAspectPadding = LegendThemeAspect(
  _$BalanceCardSelectPadding,
);
Object? _$BalanceCardOverrideSelectPadding(BalanceCardThemeNullable data) =>
    data.padding;
const _$BalanceCardOverrideAspectPadding =
    LegendOverrideAspect<BalanceCardThemeNullable>(
      _$BalanceCardOverrideSelectPadding,
    );

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class BalanceCardThemeListenables {
  /// Change stream of the resolved [BalanceCardTheme.background].
  static ValueListenable<Color> background(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$BalanceCardSelectBackground);

  /// Change stream of the resolved [BalanceCardTheme.accent].
  static ValueListenable<Color> accent(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$BalanceCardSelectAccent);

  /// Change stream of the resolved [BalanceCardTheme.padding].
  static ValueListenable<EdgeInsetsGeometry> padding(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$BalanceCardSelectPadding);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$BalanceCardThemeResolve on BalanceCard {
  /// [BalanceCardTheme.of] with this widget's constructor params as
  /// level 1.
  BalanceCardTheme _theme(BuildContext context) => BalanceCardTheme.of(
    context,
    BalanceCardThemeNullable(
      background: background,
      accent: accent,
      padding: padding,
    ),
  );

  /// Resolves ONLY [BalanceCard.background] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._background(context)`).
  Color _background(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<BalanceCardThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$BalanceCardAspectBackground);
    LegendThemeOverride.depend<BalanceCardThemeNullable>(
      context,
      _$BalanceCardOverrideAspectBackground,
    );
    return background ??
        override?.background ??
        _$BalanceCardSelectBackground(data);
  }

  /// Resolves ONLY [BalanceCard.accent] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._accent(context)`).
  Color _accent(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<BalanceCardThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$BalanceCardAspectAccent);
    LegendThemeOverride.depend<BalanceCardThemeNullable>(
      context,
      _$BalanceCardOverrideAspectAccent,
    );
    return accent ?? override?.accent ?? _$BalanceCardSelectAccent(data);
  }

  /// Resolves ONLY [BalanceCard.padding] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._padding(context)`).
  EdgeInsetsGeometry _padding(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<BalanceCardThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$BalanceCardAspectPadding);
    LegendThemeOverride.depend<BalanceCardThemeNullable>(
      context,
      _$BalanceCardOverrideAspectPadding,
    );
    return padding ?? override?.padding ?? _$BalanceCardSelectPadding(data);
  }
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class BalanceCard extends
/// _$BalanceCardBase` receives the resolved
/// [BalanceCardTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$BalanceCardBase
    extends LegendStatelessWidget<BalanceCardTheme> {
  const _$BalanceCardBase({super.key});

  Color? get background;
  Color? get accent;
  EdgeInsetsGeometry? get padding;

  @override
  BalanceCardTheme resolveThemeOf(BuildContext context) => BalanceCardTheme.of(
    context,
    BalanceCardThemeNullable(
      background: background,
      accent: accent,
      padding: padding,
    ),
  );
}
