// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: balance_card.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `BalanceCard`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in balance_card.dart.
const List<LegendDocEntry> balanceCardDocEntries = [
  LegendDocEntry(
    owner: 'BalanceCard',
    name: 'background',
    type: 'Color?',
    doc: '',
    defaultDescription: 't.colors.surface',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'BalanceCard',
    name: 'accent',
    type: 'Color?',
    doc: '',
    defaultDescription: 't.colors.secondary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'BalanceCard',
    name: 'padding',
    type: 'EdgeInsetsGeometry?',
    doc: '',
    defaultDescription: 'EdgeInsets.all(t.sizes.lg)',
    group: 'component',
  ),
];
