// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: wiring_forms.dart
// ignore_for_file: type=lint, unused_element
part of 'wiring_forms.dart';

/// Resolved theme for [AutoGetterChip].
class AutoGetterChipTheme {
  const AutoGetterChipTheme({required this.fill});

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory AutoGetterChipTheme.defaults(LegendTokens t) =>
      AutoGetterChipTheme(fill: ColorRef.primary(t));

  final Color fill;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [AutoGetterChip] first, [AutoGetterChipThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static AutoGetterChipTheme of(
    BuildContext context, [
    AutoGetterChipThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<AutoGetterChipThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$AutoGetterChipAspectFill);
    LegendThemeOverride.depend<AutoGetterChipThemeNullable>(
      context,
      _$AutoGetterChipOverrideAspectFill,
    );
    return AutoGetterChipTheme.defaults(data.tokens)
        .merge(data.componentOf<AutoGetterChipThemeNullable>(AutoGetterChip))
        .merge(override)
        .merge(local);
  }

  AutoGetterChipTheme merge(AutoGetterChipThemeNullable? other) {
    if (other == null) return this;
    return AutoGetterChipTheme(fill: other.fill ?? fill);
  }

  AutoGetterChipTheme copyWith({Color? fill}) =>
      AutoGetterChipTheme(fill: fill ?? this.fill);

  static AutoGetterChipTheme lerp(
    AutoGetterChipTheme a,
    AutoGetterChipTheme b,
    double t,
  ) => AutoGetterChipTheme(fill: t < 0.5 ? a.fill : b.fill);
}

/// Sparse overrides for [AutoGetterChipTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class AutoGetterChipThemeNullable {
  const AutoGetterChipThemeNullable({this.fill});

  final Color? fill;

  AutoGetterChipThemeNullable merge(AutoGetterChipThemeNullable? other) {
    if (other == null) return this;
    return AutoGetterChipThemeNullable(fill: other.fill ?? fill);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutoGetterChipThemeNullable && other.fill == fill;

  @override
  int get hashCode => Object.hashAll([fill]);
}

/// Overrides [AutoGetterChipTheme] for a subtree (level 2).
class AutoGetterChipThemeOverride extends StatelessWidget {
  const AutoGetterChipThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final AutoGetterChipThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<AutoGetterChipThemeNullable>(
        data: data,
        child: child,
      );
}

/// Resolves [AutoGetterChip.fill] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$AutoGetterChipSelectFill(LegendThemeData data) =>
    data.componentOf<AutoGetterChipThemeNullable>(AutoGetterChip)?.fill ??
    ColorRef.primary(data.tokens);
const _$AutoGetterChipAspectFill = LegendThemeAspect(
  _$AutoGetterChipSelectFill,
);
Object? _$AutoGetterChipOverrideSelectFill(AutoGetterChipThemeNullable data) =>
    data.fill;
const _$AutoGetterChipOverrideAspectFill =
    LegendOverrideAspect<AutoGetterChipThemeNullable>(
      _$AutoGetterChipOverrideSelectFill,
    );

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class AutoGetterChipThemeListenables {
  /// Change stream of the resolved [AutoGetterChipTheme.fill].
  static ValueListenable<Color> fill(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$AutoGetterChipSelectFill);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$AutoGetterChipThemeResolve on AutoGetterChip {
  /// [AutoGetterChipTheme.of] with this widget's constructor params as
  /// level 1.
  AutoGetterChipTheme _theme(BuildContext context) =>
      AutoGetterChipTheme.of(context, AutoGetterChipThemeNullable(fill: fill));

  /// Resolves ONLY [AutoGetterChip.fill] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._fill(context)`).
  Color _fill(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<AutoGetterChipThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$AutoGetterChipAspectFill);
    LegendThemeOverride.depend<AutoGetterChipThemeNullable>(
      context,
      _$AutoGetterChipOverrideAspectFill,
    );
    return fill ?? override?.fill ?? _$AutoGetterChipSelectFill(data);
  }
}

/// Auto-detected State wiring (RFC-002 R13): [_AutoGetterChipState]
/// is this file's `State<AutoGetterChip>`, so its
/// build reads the resolved theme as a plain `theme`
/// getter — zero visible wiring. A same-named instance
/// member (e.g. from [_$AutoGetterChipThemeState])
/// wins over this extension.
extension _$AutoGetterChipThemeOn_AutoGetterChipState on _AutoGetterChipState {
  AutoGetterChipTheme get theme => widget._theme(context);
}

/// Explicit State wiring (RFC-002 R13): mix onto any
/// `State<AutoGetterChip>` for the `theme` getter as a
/// real, overridable inherited member — no State-class
/// detection involved.
mixin _$AutoGetterChipThemeState on State<AutoGetterChip> {
  AutoGetterChipTheme get theme => widget._theme(context);
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class AutoGetterChip extends
/// _$AutoGetterChipBase` receives the resolved
/// [AutoGetterChipTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$AutoGetterChipBase
    extends LegendStatelessWidget<AutoGetterChipTheme> {
  const _$AutoGetterChipBase({super.key});

  Color? get fill;

  @override
  AutoGetterChipTheme resolveThemeOf(BuildContext context) =>
      AutoGetterChipTheme.of(context, AutoGetterChipThemeNullable(fill: fill));
}

/// Resolved theme for [MixinChip].
class MixinChipTheme {
  const MixinChipTheme({required this.fill});

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory MixinChipTheme.defaults(LegendTokens t) =>
      MixinChipTheme(fill: ColorRef.secondary(t));

  final Color fill;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [MixinChip] first, [MixinChipThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static MixinChipTheme of(
    BuildContext context, [
    MixinChipThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<MixinChipThemeNullable>(context);
    LegendTheme.depend(context, _$MixinChipAspectFill);
    LegendThemeOverride.depend<MixinChipThemeNullable>(
      context,
      _$MixinChipOverrideAspectFill,
    );
    return MixinChipTheme.defaults(data.tokens)
        .merge(data.componentOf<MixinChipThemeNullable>(MixinChip))
        .merge(override)
        .merge(local);
  }

  MixinChipTheme merge(MixinChipThemeNullable? other) {
    if (other == null) return this;
    return MixinChipTheme(fill: other.fill ?? fill);
  }

  MixinChipTheme copyWith({Color? fill}) =>
      MixinChipTheme(fill: fill ?? this.fill);

  static MixinChipTheme lerp(MixinChipTheme a, MixinChipTheme b, double t) =>
      MixinChipTheme(fill: t < 0.5 ? a.fill : b.fill);
}

/// Sparse overrides for [MixinChipTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class MixinChipThemeNullable {
  const MixinChipThemeNullable({this.fill});

  final Color? fill;

  MixinChipThemeNullable merge(MixinChipThemeNullable? other) {
    if (other == null) return this;
    return MixinChipThemeNullable(fill: other.fill ?? fill);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MixinChipThemeNullable && other.fill == fill;

  @override
  int get hashCode => Object.hashAll([fill]);
}

/// Overrides [MixinChipTheme] for a subtree (level 2).
class MixinChipThemeOverride extends StatelessWidget {
  const MixinChipThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final MixinChipThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<MixinChipThemeNullable>(data: data, child: child);
}

/// Resolves [MixinChip.fill] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$MixinChipSelectFill(LegendThemeData data) =>
    data.componentOf<MixinChipThemeNullable>(MixinChip)?.fill ??
    ColorRef.secondary(data.tokens);
const _$MixinChipAspectFill = LegendThemeAspect(_$MixinChipSelectFill);
Object? _$MixinChipOverrideSelectFill(MixinChipThemeNullable data) => data.fill;
const _$MixinChipOverrideAspectFill =
    LegendOverrideAspect<MixinChipThemeNullable>(_$MixinChipOverrideSelectFill);

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class MixinChipThemeListenables {
  /// Change stream of the resolved [MixinChipTheme.fill].
  static ValueListenable<Color> fill(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$MixinChipSelectFill);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$MixinChipThemeResolve on MixinChip {
  /// [MixinChipTheme.of] with this widget's constructor params as
  /// level 1.
  MixinChipTheme _theme(BuildContext context) =>
      MixinChipTheme.of(context, MixinChipThemeNullable(fill: fill));

  /// Resolves ONLY [MixinChip.fill] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._fill(context)`).
  Color _fill(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<MixinChipThemeNullable>(context);
    LegendTheme.depend(context, _$MixinChipAspectFill);
    LegendThemeOverride.depend<MixinChipThemeNullable>(
      context,
      _$MixinChipOverrideAspectFill,
    );
    return fill ?? override?.fill ?? _$MixinChipSelectFill(data);
  }
}

/// Auto-detected State wiring (RFC-002 R13): [_MixinChipState]
/// is this file's `State<MixinChip>`, so its
/// build reads the resolved theme as a plain `theme`
/// getter — zero visible wiring. A same-named instance
/// member (e.g. from [_$MixinChipThemeState])
/// wins over this extension.
extension _$MixinChipThemeOn_MixinChipState on _MixinChipState {
  MixinChipTheme get theme => widget._theme(context);
}

/// Explicit State wiring (RFC-002 R13): mix onto any
/// `State<MixinChip>` for the `theme` getter as a
/// real, overridable inherited member — no State-class
/// detection involved.
mixin _$MixinChipThemeState on State<MixinChip> {
  MixinChipTheme get theme => widget._theme(context);
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class MixinChip extends
/// _$MixinChipBase` receives the resolved
/// [MixinChipTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$MixinChipBase extends LegendStatelessWidget<MixinChipTheme> {
  const _$MixinChipBase({super.key});

  Color? get fill;

  @override
  MixinChipTheme resolveThemeOf(BuildContext context) =>
      MixinChipTheme.of(context, MixinChipThemeNullable(fill: fill));
}

/// Resolved theme for [BaseChip].
class BaseChipTheme {
  const BaseChipTheme({required this.fill});

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory BaseChipTheme.defaults(LegendTokens t) =>
      BaseChipTheme(fill: ColorRef.surface(t));

  final Color fill;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [BaseChip] first, [BaseChipThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static BaseChipTheme of(
    BuildContext context, [
    BaseChipThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<BaseChipThemeNullable>(context);
    LegendTheme.depend(context, _$BaseChipAspectFill);
    LegendThemeOverride.depend<BaseChipThemeNullable>(
      context,
      _$BaseChipOverrideAspectFill,
    );
    return BaseChipTheme.defaults(data.tokens)
        .merge(data.componentOf<BaseChipThemeNullable>(BaseChip))
        .merge(override)
        .merge(local);
  }

  BaseChipTheme merge(BaseChipThemeNullable? other) {
    if (other == null) return this;
    return BaseChipTheme(fill: other.fill ?? fill);
  }

  BaseChipTheme copyWith({Color? fill}) =>
      BaseChipTheme(fill: fill ?? this.fill);

  static BaseChipTheme lerp(BaseChipTheme a, BaseChipTheme b, double t) =>
      BaseChipTheme(fill: t < 0.5 ? a.fill : b.fill);
}

/// Sparse overrides for [BaseChipTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class BaseChipThemeNullable {
  const BaseChipThemeNullable({this.fill});

  final Color? fill;

  BaseChipThemeNullable merge(BaseChipThemeNullable? other) {
    if (other == null) return this;
    return BaseChipThemeNullable(fill: other.fill ?? fill);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BaseChipThemeNullable && other.fill == fill;

  @override
  int get hashCode => Object.hashAll([fill]);
}

/// Overrides [BaseChipTheme] for a subtree (level 2).
class BaseChipThemeOverride extends StatelessWidget {
  const BaseChipThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final BaseChipThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<BaseChipThemeNullable>(data: data, child: child);
}

/// Resolves [BaseChip.fill] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$BaseChipSelectFill(LegendThemeData data) =>
    data.componentOf<BaseChipThemeNullable>(BaseChip)?.fill ??
    ColorRef.surface(data.tokens);
const _$BaseChipAspectFill = LegendThemeAspect(_$BaseChipSelectFill);
Object? _$BaseChipOverrideSelectFill(BaseChipThemeNullable data) => data.fill;
const _$BaseChipOverrideAspectFill =
    LegendOverrideAspect<BaseChipThemeNullable>(_$BaseChipOverrideSelectFill);

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class BaseChipThemeListenables {
  /// Change stream of the resolved [BaseChipTheme.fill].
  static ValueListenable<Color> fill(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$BaseChipSelectFill);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$BaseChipThemeResolve on BaseChip {
  /// [BaseChipTheme.of] with this widget's constructor params as
  /// level 1.
  BaseChipTheme _theme(BuildContext context) =>
      BaseChipTheme.of(context, BaseChipThemeNullable(fill: fill));

  /// Resolves ONLY [BaseChip.fill] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._fill(context)`).
  Color _fill(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<BaseChipThemeNullable>(context);
    LegendTheme.depend(context, _$BaseChipAspectFill);
    LegendThemeOverride.depend<BaseChipThemeNullable>(
      context,
      _$BaseChipOverrideAspectFill,
    );
    return fill ?? override?.fill ?? _$BaseChipSelectFill(data);
  }
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class BaseChip extends
/// _$BaseChipBase` receives the resolved
/// [BaseChipTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$BaseChipBase extends LegendStatelessWidget<BaseChipTheme> {
  const _$BaseChipBase({super.key});

  Color? get fill;

  @override
  BaseChipTheme resolveThemeOf(BuildContext context) =>
      BaseChipTheme.of(context, BaseChipThemeNullable(fill: fill));
}
