// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_radio.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendRadio`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_radio.dart.
const List<LegendDocEntry> legendRadioDocEntries = [
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'fill',
    type: 'InteractiveColors?',
    doc:
        'Fill of the circle while selected, per interaction state —\nhover/press blend the dot color over the fill (8%/16%), disabled\nswaps to the token disabled fill.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), pressed: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.16), t.colors.primary), focused: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'fill.normal',
    type: 'Color?',
    doc: 'Fill at rest (and the base unset members fall back to).',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), pressed: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.16), t.colors.primary), focused: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'fill.hovered',
    type: 'Color?',
    doc: 'Fill while a pointer hovers the widget.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), pressed: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.16), t.colors.primary), focused: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'fill.pressed',
    type: 'Color?',
    doc: 'Fill while the widget is actively pressed.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), pressed: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.16), t.colors.primary), focused: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'fill.focused',
    type: 'Color?',
    doc: 'Fill while the widget holds keyboard focus.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), pressed: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.16), t.colors.primary), focused: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'fill.disabled',
    type: 'Color?',
    doc: 'Fill while the widget is disabled.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), pressed: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.16), t.colors.primary), focused: Color.alphaBlend(t.colors.onPrimary.withValues(alpha: 0.08), t.colors.primary), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'dotColor',
    type: 'Color?',
    doc: 'Color of the selected inner dot.',
    defaultDescription: 'ColorRef.onPrimary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'borderColor',
    type: 'Color?',
    doc: 'Border color of the unselected circle.',
    defaultDescription: 'ColorRef.background3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'focusedBorderColor',
    type: 'Color?',
    doc:
        'Border color while the unselected circle holds keyboard focus (a\nselected radio shows focus through the [fill] focused fill instead).',
    defaultDescription: 'ColorRef.primary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'size',
    type: 'double?',
    doc: 'Diameter of the circle.',
    defaultDescription: 'SizeRef.iconMd',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendRadio',
    name: 'borderWidth',
    type: 'double?',
    doc: 'Stroke width of the unselected border.',
    defaultDescription: '1.5',
    group: 'component',
  ),
];
