// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_radio.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_radio.dart';

/// Resolved theme for [LegendRadio].
class LegendRadioTheme {
  const LegendRadioTheme({
    required this.fill,
    required this.dotColor,
    required this.borderColor,
    required this.focusedBorderColor,
    required this.size,
    required this.borderWidth,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendRadioTheme.defaults(LegendTokens t) => LegendRadioTheme(
    fill: _fill(t),
    dotColor: ColorRef.onPrimary(t),
    borderColor: ColorRef.background3(t),
    focusedBorderColor: ColorRef.primary(t),
    size: SizeRef.iconMd(t),
    borderWidth: 1.5,
  );

  final InteractiveColors fill;
  final Color dotColor;
  final Color borderColor;
  final Color focusedBorderColor;
  final double size;
  final double borderWidth;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendRadio] first, [LegendRadioThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static LegendRadioTheme of(
    BuildContext context, [
    LegendRadioThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendRadioThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendRadioAspectFill);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectFill,
    );
    LegendTheme.depend(context, _$LegendRadioAspectDotColor);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectDotColor,
    );
    LegendTheme.depend(context, _$LegendRadioAspectBorderColor);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectBorderColor,
    );
    LegendTheme.depend(context, _$LegendRadioAspectFocusedBorderColor);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectFocusedBorderColor,
    );
    LegendTheme.depend(context, _$LegendRadioAspectSize);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectSize,
    );
    LegendTheme.depend(context, _$LegendRadioAspectBorderWidth);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectBorderWidth,
    );
    return LegendRadioTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendRadioThemeNullable>(LegendRadio))
        .merge(override)
        .merge(local);
  }

  LegendRadioTheme merge(LegendRadioThemeNullable? other) {
    if (other == null) return this;
    return LegendRadioTheme(
      fill: fill.merge(other.fill),
      dotColor: other.dotColor ?? dotColor,
      borderColor: other.borderColor ?? borderColor,
      focusedBorderColor: other.focusedBorderColor ?? focusedBorderColor,
      size: other.size ?? size,
      borderWidth: other.borderWidth ?? borderWidth,
    );
  }

  LegendRadioTheme copyWith({
    InteractiveColors? fill,
    Color? dotColor,
    Color? borderColor,
    Color? focusedBorderColor,
    double? size,
    double? borderWidth,
  }) => LegendRadioTheme(
    fill: fill ?? this.fill,
    dotColor: dotColor ?? this.dotColor,
    borderColor: borderColor ?? this.borderColor,
    focusedBorderColor: focusedBorderColor ?? this.focusedBorderColor,
    size: size ?? this.size,
    borderWidth: borderWidth ?? this.borderWidth,
  );

  static LegendRadioTheme lerp(
    LegendRadioTheme a,
    LegendRadioTheme b,
    double t,
  ) => LegendRadioTheme(
    fill: InteractiveColors.lerp(a.fill, b.fill, t)!,
    dotColor: Color.lerp(a.dotColor, b.dotColor, t)!,
    borderColor: Color.lerp(a.borderColor, b.borderColor, t)!,
    focusedBorderColor: Color.lerp(
      a.focusedBorderColor,
      b.focusedBorderColor,
      t,
    )!,
    size: t < 0.5 ? a.size : b.size,
    borderWidth: t < 0.5 ? a.borderWidth : b.borderWidth,
  );
}

/// Sparse overrides for [LegendRadioTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendRadioThemeNullable {
  const LegendRadioThemeNullable({
    this.fill,
    this.dotColor,
    this.borderColor,
    this.focusedBorderColor,
    this.size,
    this.borderWidth,
  });

  final InteractiveColors? fill;
  final Color? dotColor;
  final Color? borderColor;
  final Color? focusedBorderColor;
  final double? size;
  final double? borderWidth;

  LegendRadioThemeNullable merge(LegendRadioThemeNullable? other) {
    if (other == null) return this;
    return LegendRadioThemeNullable(
      fill: fill?.merge(other.fill) ?? other.fill,
      dotColor: other.dotColor ?? dotColor,
      borderColor: other.borderColor ?? borderColor,
      focusedBorderColor: other.focusedBorderColor ?? focusedBorderColor,
      size: other.size ?? size,
      borderWidth: other.borderWidth ?? borderWidth,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendRadioThemeNullable &&
          other.fill == fill &&
          other.dotColor == dotColor &&
          other.borderColor == borderColor &&
          other.focusedBorderColor == focusedBorderColor &&
          other.size == size &&
          other.borderWidth == borderWidth;

  @override
  int get hashCode => Object.hashAll([
    fill,
    dotColor,
    borderColor,
    focusedBorderColor,
    size,
    borderWidth,
  ]);
}

/// Overrides [LegendRadioTheme] for a subtree (level 2).
class LegendRadioThemeOverride extends StatelessWidget {
  const LegendRadioThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendRadioThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendRadioThemeNullable>(data: data, child: child);
}

/// Resolves [LegendRadio.fill] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
InteractiveColors _$LegendRadioSelectFill(LegendThemeData data) => _fill(
  data.tokens,
).merge(data.componentOf<LegendRadioThemeNullable>(LegendRadio)?.fill);
const _$LegendRadioAspectFill = LegendThemeAspect(_$LegendRadioSelectFill);
Object? _$LegendRadioOverrideSelectFill(LegendRadioThemeNullable data) =>
    data.fill;
const _$LegendRadioOverrideAspectFill =
    LegendOverrideAspect<LegendRadioThemeNullable>(
      _$LegendRadioOverrideSelectFill,
    );

/// Resolves [LegendRadio.dotColor] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendRadioSelectDotColor(LegendThemeData data) =>
    data.componentOf<LegendRadioThemeNullable>(LegendRadio)?.dotColor ??
    ColorRef.onPrimary(data.tokens);
const _$LegendRadioAspectDotColor = LegendThemeAspect(
  _$LegendRadioSelectDotColor,
);
Object? _$LegendRadioOverrideSelectDotColor(LegendRadioThemeNullable data) =>
    data.dotColor;
const _$LegendRadioOverrideAspectDotColor =
    LegendOverrideAspect<LegendRadioThemeNullable>(
      _$LegendRadioOverrideSelectDotColor,
    );

/// Resolves [LegendRadio.borderColor] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendRadioSelectBorderColor(LegendThemeData data) =>
    data.componentOf<LegendRadioThemeNullable>(LegendRadio)?.borderColor ??
    ColorRef.background3(data.tokens);
const _$LegendRadioAspectBorderColor = LegendThemeAspect(
  _$LegendRadioSelectBorderColor,
);
Object? _$LegendRadioOverrideSelectBorderColor(LegendRadioThemeNullable data) =>
    data.borderColor;
const _$LegendRadioOverrideAspectBorderColor =
    LegendOverrideAspect<LegendRadioThemeNullable>(
      _$LegendRadioOverrideSelectBorderColor,
    );

/// Resolves [LegendRadio.focusedBorderColor] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendRadioSelectFocusedBorderColor(LegendThemeData data) =>
    data
        .componentOf<LegendRadioThemeNullable>(LegendRadio)
        ?.focusedBorderColor ??
    ColorRef.primary(data.tokens);
const _$LegendRadioAspectFocusedBorderColor = LegendThemeAspect(
  _$LegendRadioSelectFocusedBorderColor,
);
Object? _$LegendRadioOverrideSelectFocusedBorderColor(
  LegendRadioThemeNullable data,
) => data.focusedBorderColor;
const _$LegendRadioOverrideAspectFocusedBorderColor =
    LegendOverrideAspect<LegendRadioThemeNullable>(
      _$LegendRadioOverrideSelectFocusedBorderColor,
    );

/// Resolves [LegendRadio.size] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
double _$LegendRadioSelectSize(LegendThemeData data) =>
    data.componentOf<LegendRadioThemeNullable>(LegendRadio)?.size ??
    SizeRef.iconMd(data.tokens);
const _$LegendRadioAspectSize = LegendThemeAspect(_$LegendRadioSelectSize);
Object? _$LegendRadioOverrideSelectSize(LegendRadioThemeNullable data) =>
    data.size;
const _$LegendRadioOverrideAspectSize =
    LegendOverrideAspect<LegendRadioThemeNullable>(
      _$LegendRadioOverrideSelectSize,
    );

/// Resolves [LegendRadio.borderWidth] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
double _$LegendRadioSelectBorderWidth(LegendThemeData data) =>
    data.componentOf<LegendRadioThemeNullable>(LegendRadio)?.borderWidth ?? 1.5;
const _$LegendRadioAspectBorderWidth = LegendThemeAspect(
  _$LegendRadioSelectBorderWidth,
);
Object? _$LegendRadioOverrideSelectBorderWidth(LegendRadioThemeNullable data) =>
    data.borderWidth;
const _$LegendRadioOverrideAspectBorderWidth =
    LegendOverrideAspect<LegendRadioThemeNullable>(
      _$LegendRadioOverrideSelectBorderWidth,
    );

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class LegendRadioThemeListenables {
  /// Change stream of the resolved [LegendRadioTheme.fill].
  static ValueListenable<InteractiveColors> fill(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendRadioSelectFill);

  /// Change stream of the resolved [LegendRadioTheme.dotColor].
  static ValueListenable<Color> dotColor(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendRadioSelectDotColor);

  /// Change stream of the resolved [LegendRadioTheme.borderColor].
  static ValueListenable<Color> borderColor(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendRadioSelectBorderColor);

  /// Change stream of the resolved [LegendRadioTheme.focusedBorderColor].
  static ValueListenable<Color> focusedBorderColor(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendRadioSelectFocusedBorderColor);

  /// Change stream of the resolved [LegendRadioTheme.size].
  static ValueListenable<double> size(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendRadioSelectSize);

  /// Change stream of the resolved [LegendRadioTheme.borderWidth].
  static ValueListenable<double> borderWidth(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendRadioSelectBorderWidth);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendRadioThemeResolve on LegendRadio {
  /// [LegendRadioTheme.of] with this widget's constructor params as
  /// level 1.
  LegendRadioTheme _theme(BuildContext context) => LegendRadioTheme.of(
    context,
    LegendRadioThemeNullable(
      fill: fill,
      dotColor: dotColor,
      borderColor: borderColor,
      focusedBorderColor: focusedBorderColor,
      size: size,
      borderWidth: borderWidth,
    ),
  );

  /// Resolves ONLY [LegendRadio.fill] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._fill(context)`).
  InteractiveColors _fill(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendRadioThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendRadioAspectFill);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectFill,
    );
    return _$LegendRadioSelectFill(data).merge(override?.fill).merge(fill);
  }

  /// Resolves ONLY [LegendRadio.dotColor] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._dotColor(context)`).
  Color _dotColor(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendRadioThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendRadioAspectDotColor);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectDotColor,
    );
    return dotColor ?? override?.dotColor ?? _$LegendRadioSelectDotColor(data);
  }

  /// Resolves ONLY [LegendRadio.borderColor] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._borderColor(context)`).
  Color _borderColor(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendRadioThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendRadioAspectBorderColor);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectBorderColor,
    );
    return borderColor ??
        override?.borderColor ??
        _$LegendRadioSelectBorderColor(data);
  }

  /// Resolves ONLY [LegendRadio.focusedBorderColor] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._focusedBorderColor(context)`).
  Color _focusedBorderColor(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendRadioThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendRadioAspectFocusedBorderColor);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectFocusedBorderColor,
    );
    return focusedBorderColor ??
        override?.focusedBorderColor ??
        _$LegendRadioSelectFocusedBorderColor(data);
  }

  /// Resolves ONLY [LegendRadio.size] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._size(context)`).
  double _size(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendRadioThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendRadioAspectSize);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectSize,
    );
    return size ?? override?.size ?? _$LegendRadioSelectSize(data);
  }

  /// Resolves ONLY [LegendRadio.borderWidth] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._borderWidth(context)`).
  double _borderWidth(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendRadioThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendRadioAspectBorderWidth);
    LegendThemeOverride.depend<LegendRadioThemeNullable>(
      context,
      _$LegendRadioOverrideAspectBorderWidth,
    );
    return borderWidth ??
        override?.borderWidth ??
        _$LegendRadioSelectBorderWidth(data);
  }
}

/// Auto-detected State wiring (RFC-002 R13): [_LegendRadioState]
/// is this file's `State<LegendRadio>`, so its
/// build reads the resolved theme as a plain `theme`
/// getter — zero visible wiring. A same-named instance
/// member (e.g. from [_$LegendRadioThemeState])
/// wins over this extension.
extension _$LegendRadioThemeOn_LegendRadioState<T> on _LegendRadioState<T> {
  LegendRadioTheme get theme => widget._theme(context);
}

/// Explicit State wiring (RFC-002 R13): mix onto any
/// `State<LegendRadio>` for the `theme` getter as a
/// real, overridable inherited member — no State-class
/// detection involved.
mixin _$LegendRadioThemeState on State<LegendRadio> {
  LegendRadioTheme get theme => widget._theme(context);
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class LegendRadio extends
/// _$LegendRadioBase` receives the resolved
/// [LegendRadioTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$LegendRadioBase
    extends LegendStatelessWidget<LegendRadioTheme> {
  const _$LegendRadioBase({super.key});

  InteractiveColors? get fill;
  Color? get dotColor;
  Color? get borderColor;
  Color? get focusedBorderColor;
  double? get size;
  double? get borderWidth;

  @override
  LegendRadioTheme resolveThemeOf(BuildContext context) => LegendRadioTheme.of(
    context,
    LegendRadioThemeNullable(
      fill: fill,
      dotColor: dotColor,
      borderColor: borderColor,
      focusedBorderColor: focusedBorderColor,
      size: size,
      borderWidth: borderWidth,
    ),
  );
}
