// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_state_overlays.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_state_overlays.dart';

/// Generated mechanical members for [LegendStateOverlays] (RFC-002 R5):
/// `copyWith` and value `==`/`hashCode`. Applied via
/// `with _$LegendStateOverlays`; fields are read through a private cast
/// (no abstract getters, so the class declares no overrides).
mixin _$LegendStateOverlays {
  LegendStateOverlays get _self => this as LegendStateOverlays;

  /// Copy with the given fields replaced.
  LegendStateOverlays copyWith({
    double? hoverAmount,
    double? pressAmount,
    double? disabledOpacity,
  }) => LegendStateOverlays(
    hoverAmount: hoverAmount ?? _self.hoverAmount,
    pressAmount: pressAmount ?? _self.pressAmount,
    disabledOpacity: disabledOpacity ?? _self.disabledOpacity,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendStateOverlays &&
          other.hoverAmount == _self.hoverAmount &&
          other.pressAmount == _self.pressAmount &&
          other.disabledOpacity == _self.disabledOpacity;

  @override
  int get hashCode => Object.hashAll([
    _self.hoverAmount,
    _self.pressAmount,
    _self.disabledOpacity,
  ]);
}

/// Member-wise lerp for [LegendStateOverlays]; the public [LegendStateOverlays.lerp]
/// redirects here (part of the one token lerp a theme switch
/// pays, DESIGN.md §2.4). Identical endpoints short-circuit
/// to the same instance (RFC-002 R12 amendment): sub-objects
/// shared between theme poles stay identity-stable through
/// an animation, so per-field rebuild comparators never
/// re-diff unchanged token groups.
LegendStateOverlays _$LegendStateOverlaysLerp(
  LegendStateOverlays a,
  LegendStateOverlays b,
  double t,
) {
  if (identical(a, b)) return a;
  return LegendStateOverlays(
    hoverAmount: a.hoverAmount == b.hoverAmount
        ? a.hoverAmount
        : a.hoverAmount * (1.0 - t) + b.hoverAmount * t,
    pressAmount: a.pressAmount == b.pressAmount
        ? a.pressAmount
        : a.pressAmount * (1.0 - t) + b.pressAmount * t,
    disabledOpacity: a.disabledOpacity == b.disabledOpacity
        ? a.disabledOpacity
        : a.disabledOpacity * (1.0 - t) + b.disabledOpacity * t,
  );
}

/// Const tear-off catalog for [LegendStateOverlays] (RFC-002 R10
/// amendment): one static per token field, usable directly
/// inside `@Style<T>.resolve` annotations —
/// `@Style<double>.resolve(StateRef.hoverAmount)`.
abstract final class StateRef {
  /// How far [hovered] shifts the base toward black/white (0–1).
  static double hoverAmount(LegendTokens t) => t.states.hoverAmount;

  /// How far [pressed] shifts the base toward black/white (0–1).
  static double pressAmount(LegendTokens t) => t.states.pressAmount;

  /// Opacity multiplier [disabled] applies to the base color (0–1).
  static double disabledOpacity(LegendTokens t) => t.states.disabledOpacity;
}
