// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_colors.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_colors.dart';

/// Generated mechanical members for [LegendColors] (RFC-002 R5):
/// `copyWith` and value `==`/`hashCode`. Applied via
/// `with _$LegendColors`; fields are read through a private cast
/// (no abstract getters, so the class declares no overrides).
mixin _$LegendColors {
  LegendColors get _self => this as LegendColors;

  /// Copy with the given fields replaced.
  LegendColors copyWith({
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? onPrimaryContainer,
    Color? secondary,
    Color? onSecondary,
    Color? background1,
    Color? background2,
    Color? background3,
    Color? surface,
    Color? onSurface,
    Color? error,
    Color? onError,
    Color? disabled,
    Color? onDisabled,
    Color? foreground1,
    Color? foreground2,
    Color? foreground3,
  }) => LegendColors(
    primary: primary ?? _self.primary,
    onPrimary: onPrimary ?? _self.onPrimary,
    primaryContainer: primaryContainer ?? _self.primaryContainer,
    onPrimaryContainer: onPrimaryContainer ?? _self.onPrimaryContainer,
    secondary: secondary ?? _self.secondary,
    onSecondary: onSecondary ?? _self.onSecondary,
    background1: background1 ?? _self.background1,
    background2: background2 ?? _self.background2,
    background3: background3 ?? _self.background3,
    surface: surface ?? _self.surface,
    onSurface: onSurface ?? _self.onSurface,
    error: error ?? _self.error,
    onError: onError ?? _self.onError,
    disabled: disabled ?? _self.disabled,
    onDisabled: onDisabled ?? _self.onDisabled,
    foreground1: foreground1 ?? _self.foreground1,
    foreground2: foreground2 ?? _self.foreground2,
    foreground3: foreground3 ?? _self.foreground3,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendColors &&
          other.primary == _self.primary &&
          other.onPrimary == _self.onPrimary &&
          other.primaryContainer == _self.primaryContainer &&
          other.onPrimaryContainer == _self.onPrimaryContainer &&
          other.secondary == _self.secondary &&
          other.onSecondary == _self.onSecondary &&
          other.background1 == _self.background1 &&
          other.background2 == _self.background2 &&
          other.background3 == _self.background3 &&
          other.surface == _self.surface &&
          other.onSurface == _self.onSurface &&
          other.error == _self.error &&
          other.onError == _self.onError &&
          other.disabled == _self.disabled &&
          other.onDisabled == _self.onDisabled &&
          other.foreground1 == _self.foreground1 &&
          other.foreground2 == _self.foreground2 &&
          other.foreground3 == _self.foreground3;

  @override
  int get hashCode => Object.hashAll([
    _self.primary,
    _self.onPrimary,
    _self.primaryContainer,
    _self.onPrimaryContainer,
    _self.secondary,
    _self.onSecondary,
    _self.background1,
    _self.background2,
    _self.background3,
    _self.surface,
    _self.onSurface,
    _self.error,
    _self.onError,
    _self.disabled,
    _self.onDisabled,
    _self.foreground1,
    _self.foreground2,
    _self.foreground3,
  ]);
}

/// Member-wise lerp for [LegendColors]; the public [LegendColors.lerp]
/// redirects here (part of the one token lerp a theme switch
/// pays, DESIGN.md §2.4).
LegendColors _$LegendColorsLerp(LegendColors a, LegendColors b, double t) =>
    LegendColors(
      primary: Color.lerp(a.primary, b.primary, t)!,
      onPrimary: Color.lerp(a.onPrimary, b.onPrimary, t)!,
      primaryContainer: Color.lerp(a.primaryContainer, b.primaryContainer, t)!,
      onPrimaryContainer: Color.lerp(
        a.onPrimaryContainer,
        b.onPrimaryContainer,
        t,
      )!,
      secondary: Color.lerp(a.secondary, b.secondary, t)!,
      onSecondary: Color.lerp(a.onSecondary, b.onSecondary, t)!,
      background1: Color.lerp(a.background1, b.background1, t)!,
      background2: Color.lerp(a.background2, b.background2, t)!,
      background3: Color.lerp(a.background3, b.background3, t)!,
      surface: Color.lerp(a.surface, b.surface, t)!,
      onSurface: Color.lerp(a.onSurface, b.onSurface, t)!,
      error: Color.lerp(a.error, b.error, t)!,
      onError: Color.lerp(a.onError, b.onError, t)!,
      disabled: Color.lerp(a.disabled, b.disabled, t)!,
      onDisabled: Color.lerp(a.onDisabled, b.onDisabled, t)!,
      foreground1: Color.lerp(a.foreground1, b.foreground1, t)!,
      foreground2: Color.lerp(a.foreground2, b.foreground2, t)!,
      foreground3: Color.lerp(a.foreground3, b.foreground3, t)!,
    );

/// Const tear-off catalog for [LegendColors] (RFC-002 R10
/// amendment): one static per token field, usable directly
/// inside `@Style<T>.resolve` annotations —
/// `@Style<Color>.resolve(ColorRef.primary)`.
abstract final class ColorRef {
  /// The brand color — filled buttons, active states, focus accents.
  static Color primary(LegendTokens t) => t.colors.primary;

  /// Foreground for content sitting on [primary].
  static Color onPrimary(LegendTokens t) => t.colors.onPrimary;

  /// Soft tinted fill derived from the brand — selected navigation items,
  /// secondary button fills.
  static Color primaryContainer(LegendTokens t) => t.colors.primaryContainer;

  /// Foreground for content sitting on [primaryContainer] (added by the
  /// 2026-07-09 §9.1 pairs audit; matches what components historically
  /// drew there — the primary color).
  static Color onPrimaryContainer(LegendTokens t) =>
      t.colors.onPrimaryContainer;

  /// The supporting accent — success accents, secondary highlights.
  static Color secondary(LegendTokens t) => t.colors.secondary;

  /// Foreground for content sitting on [secondary].
  static Color onSecondary(LegendTokens t) => t.colors.onSecondary;

  /// Page background (the lowest layer).
  static Color background1(LegendTokens t) => t.colors.background1;

  /// Raised background — hover fills, subtle emphasis over [background1].
  static Color background2(LegendTokens t) => t.colors.background2;

  /// Strong background — hairlines, resting borders, dividers.
  static Color background3(LegendTokens t) => t.colors.background3;

  /// Elevated content surfaces: cards, menus, dialogs, bars.
  static Color surface(LegendTokens t) => t.colors.surface;

  /// Foreground for content sitting on [surface].
  static Color onSurface(LegendTokens t) => t.colors.onSurface;

  /// Destructive/error color — error borders, messages, accents.
  static Color error(LegendTokens t) => t.colors.error;

  /// Foreground for content sitting on [error].
  static Color onError(LegendTokens t) => t.colors.onError;

  /// Fill of disabled interactive surfaces.
  static Color disabled(LegendTokens t) => t.colors.disabled;

  /// Foreground for content sitting on [disabled].
  static Color onDisabled(LegendTokens t) => t.colors.onDisabled;

  /// Primary text color.
  static Color foreground1(LegendTokens t) => t.colors.foreground1;

  /// Muted text color — labels, supporting copy.
  static Color foreground2(LegendTokens t) => t.colors.foreground2;

  /// Faint text color — placeholders, de-emphasized items.
  static Color foreground3(LegendTokens t) => t.colors.foreground3;
}
