// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_tokens.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_tokens.dart';

/// Generated mechanical members for [LegendTokens] (RFC-002 R5):
/// `copyWith` and value `==`/`hashCode`. Applied via
/// `with _$LegendTokens`; fields are read through a private cast
/// (no abstract getters, so the class declares no overrides).
mixin _$LegendTokens {
  LegendTokens get _self => this as LegendTokens;

  /// Copy with the given fields replaced.
  LegendTokens copyWith({
    LegendColors? colors,
    LegendSizes? sizes,
    LegendTypography? typography,
    LegendShadows? shadows,
    LegendStateOverlays? states,
  }) => LegendTokens(
    colors: colors ?? _self.colors,
    sizes: sizes ?? _self.sizes,
    typography: typography ?? _self.typography,
    shadows: shadows ?? _self.shadows,
    states: states ?? _self.states,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendTokens &&
          other.colors == _self.colors &&
          other.sizes == _self.sizes &&
          other.typography == _self.typography &&
          other.shadows == _self.shadows &&
          other.states == _self.states;

  @override
  int get hashCode => Object.hashAll([
    _self.colors,
    _self.sizes,
    _self.typography,
    _self.shadows,
    _self.states,
  ]);
}

/// Member-wise lerp for [LegendTokens]; the public [LegendTokens.lerp]
/// redirects here (part of the one token lerp a theme switch
/// pays, DESIGN.md §2.4). Identical endpoints short-circuit
/// to the same instance (RFC-002 R12 amendment): sub-objects
/// shared between theme poles stay identity-stable through
/// an animation, so per-field rebuild comparators never
/// re-diff unchanged token groups.
LegendTokens _$LegendTokensLerp(LegendTokens a, LegendTokens b, double t) {
  if (identical(a, b)) return a;
  return LegendTokens(
    colors: LegendColors.lerp(a.colors, b.colors, t),
    sizes: LegendSizes.lerp(a.sizes, b.sizes, t),
    typography: LegendTypography.lerp(a.typography, b.typography, t),
    shadows: LegendShadows.lerp(a.shadows, b.shadows, t),
    states: LegendStateOverlays.lerp(a.states, b.states, t),
  );
}

/// Const tear-off catalog for [LegendTokens] (RFC-002 R10
/// amendment): one static per token field, usable directly
/// inside `@Style<T>.resolve` annotations —
/// `@Style<LegendColors>.resolve(TokenRef.colors)`.
abstract final class TokenRef {
  /// The semantic color palette.
  static LegendColors colors(LegendTokens t) => t.colors;

  /// Spacing, radii, border and icon scales.
  static LegendSizes sizes(LegendTokens t) => t.sizes;

  /// The six-style type scale.
  static LegendTypography typography(LegendTokens t) => t.typography;

  /// The elevation system.
  static LegendShadows shadows(LegendTokens t) => t.shadows;

  /// Interaction-state derivation deltas (RFC-002 R6): how unset
  /// hover/press/disabled variants derive from a base color.
  static LegendStateOverlays states(LegendTokens t) => t.states;
}
