// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_switch.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_switch.dart';

/// Resolved theme for [LegendSwitch].
class LegendSwitchTheme {
  const LegendSwitchTheme({
    required this.activeTrack,
    required this.inactiveTrack,
    required this.thumb,
    required this.width,
    required this.height,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendSwitchTheme.defaults(LegendTokens t) => LegendSwitchTheme(
    activeTrack: ColorRef.primary(t),
    inactiveTrack: ColorRef.background3(t),
    thumb: ColorRef.surface(t),
    width: 44,
    height: 24,
  );

  final Color activeTrack;
  final Color inactiveTrack;
  final Color thumb;
  final double width;
  final double height;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendSwitch] first, [LegendSwitchThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  static LegendSwitchTheme of(
    BuildContext context, [
    LegendSwitchThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    return LegendSwitchTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendSwitchThemeNullable>(LegendSwitch))
        .merge(LegendThemeOverride.maybeOf<LegendSwitchThemeNullable>(context))
        .merge(local);
  }

  LegendSwitchTheme merge(LegendSwitchThemeNullable? other) {
    if (other == null) return this;
    return LegendSwitchTheme(
      activeTrack: other.activeTrack ?? activeTrack,
      inactiveTrack: other.inactiveTrack ?? inactiveTrack,
      thumb: other.thumb ?? thumb,
      width: other.width ?? width,
      height: other.height ?? height,
    );
  }

  LegendSwitchTheme copyWith({
    Color? activeTrack,
    Color? inactiveTrack,
    Color? thumb,
    double? width,
    double? height,
  }) => LegendSwitchTheme(
    activeTrack: activeTrack ?? this.activeTrack,
    inactiveTrack: inactiveTrack ?? this.inactiveTrack,
    thumb: thumb ?? this.thumb,
    width: width ?? this.width,
    height: height ?? this.height,
  );

  static LegendSwitchTheme lerp(
    LegendSwitchTheme a,
    LegendSwitchTheme b,
    double t,
  ) => LegendSwitchTheme(
    activeTrack: Color.lerp(a.activeTrack, b.activeTrack, t)!,
    inactiveTrack: Color.lerp(a.inactiveTrack, b.inactiveTrack, t)!,
    thumb: t < 0.5 ? a.thumb : b.thumb,
    width: t < 0.5 ? a.width : b.width,
    height: t < 0.5 ? a.height : b.height,
  );
}

/// Sparse overrides for [LegendSwitchTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendSwitchThemeNullable {
  const LegendSwitchThemeNullable({
    this.activeTrack,
    this.inactiveTrack,
    this.thumb,
    this.width,
    this.height,
  });

  final Color? activeTrack;
  final Color? inactiveTrack;
  final Color? thumb;
  final double? width;
  final double? height;

  LegendSwitchThemeNullable merge(LegendSwitchThemeNullable? other) {
    if (other == null) return this;
    return LegendSwitchThemeNullable(
      activeTrack: other.activeTrack ?? activeTrack,
      inactiveTrack: other.inactiveTrack ?? inactiveTrack,
      thumb: other.thumb ?? thumb,
      width: other.width ?? width,
      height: other.height ?? height,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendSwitchThemeNullable &&
          other.activeTrack == activeTrack &&
          other.inactiveTrack == inactiveTrack &&
          other.thumb == thumb &&
          other.width == width &&
          other.height == height;

  @override
  int get hashCode =>
      Object.hashAll([activeTrack, inactiveTrack, thumb, width, height]);
}

/// Overrides [LegendSwitchTheme] for a subtree (level 2).
class LegendSwitchThemeOverride extends StatelessWidget {
  const LegendSwitchThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendSwitchThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendSwitchThemeNullable>(data: data, child: child);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendSwitchThemeResolve on LegendSwitch {
  /// [LegendSwitchTheme.of] with this widget's constructor params as
  /// level 1.
  LegendSwitchTheme _theme(BuildContext context) => LegendSwitchTheme.of(
    context,
    LegendSwitchThemeNullable(
      activeTrack: activeTrack,
      inactiveTrack: inactiveTrack,
      thumb: thumb,
      width: width,
      height: height,
    ),
  );
}
