// GENERATED by legend_gen v0.1.0-dev.0 — do not edit.
// Source: legend_switch.dart
// ignore_for_file: type=lint, unused_import

import 'legend_switch.dart';
import 'package:flutter/widgets.dart';
import 'package:legend_ui/legend_ui.dart';
import 'package:legend_ui/src/annotations/annotations.dart';
import 'package:legend_ui/src/primitives/legend_interactive.dart';
import 'package:legend_ui/src/theme/legend_theme.dart';

/// Resolved theme for [LegendSwitch].
class LegendSwitchTheme {
  const LegendSwitchTheme({
    required this.activeTrack,
    required this.inactiveTrack,
    required this.thumb,
    required this.width,
    required this.height,
  });

  /// Token-derived defaults (level 5).
  factory LegendSwitchTheme.defaults(LegendTokens t) => LegendSwitchTheme(
    activeTrack: t.colors.primary,
    inactiveTrack: t.colors.background3,
    thumb: t.colors.surface,
    width: 44.0,
    height: 24.0,
  );

  final Color activeTrack;
  final Color inactiveTrack;
  final Color thumb;
  final double width;
  final double height;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static LegendSwitchTheme of(
    BuildContext context, [
    LegendSwitchThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    return LegendSwitchTheme.defaults(data.tokens)
        .merge(data.component<LegendSwitchThemeNullable>())
        .merge(LegendThemeOverride.maybeOf<LegendSwitchThemeNullable>(context))
        .merge(local);
  }

  LegendSwitchTheme merge(LegendSwitchThemeNullable? other) {
    if (other == null) return this;
    return LegendSwitchTheme(
      activeTrack: other.activeTrack ?? activeTrack,
      inactiveTrack: other.inactiveTrack ?? inactiveTrack,
      thumb: other.thumb ?? thumb,
      width: other.width ?? width,
      height: other.height ?? height,
    );
  }

  LegendSwitchTheme copyWith({
    Color? activeTrack,
    Color? inactiveTrack,
    Color? thumb,
    double? width,
    double? height,
  }) => LegendSwitchTheme(
    activeTrack: activeTrack ?? this.activeTrack,
    inactiveTrack: inactiveTrack ?? this.inactiveTrack,
    thumb: thumb ?? this.thumb,
    width: width ?? this.width,
    height: height ?? this.height,
  );

  static LegendSwitchTheme lerp(
    LegendSwitchTheme a,
    LegendSwitchTheme b,
    double t,
  ) => LegendSwitchTheme(
    activeTrack: Color.lerp(a.activeTrack, b.activeTrack, t)!,
    inactiveTrack: Color.lerp(a.inactiveTrack, b.inactiveTrack, t)!,
    thumb: t < 0.5 ? a.thumb : b.thumb,
    width: t < 0.5 ? a.width : b.width,
    height: t < 0.5 ? a.height : b.height,
  );
}

/// Sparse overrides for [LegendSwitchTheme]; null means "inherit".
class LegendSwitchThemeNullable {
  const LegendSwitchThemeNullable({
    this.activeTrack,
    this.inactiveTrack,
    this.thumb,
    this.width,
    this.height,
  });

  final Color? activeTrack;
  final Color? inactiveTrack;
  final Color? thumb;
  final double? width;
  final double? height;

  LegendSwitchThemeNullable merge(LegendSwitchThemeNullable? other) {
    if (other == null) return this;
    return LegendSwitchThemeNullable(
      activeTrack: other.activeTrack ?? activeTrack,
      inactiveTrack: other.inactiveTrack ?? inactiveTrack,
      thumb: other.thumb ?? thumb,
      width: other.width ?? width,
      height: other.height ?? height,
    );
  }
}

/// Overrides [LegendSwitchTheme] for a subtree (level 2).
class LegendSwitchThemeOverride extends StatelessWidget {
  const LegendSwitchThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendSwitchThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendSwitchThemeNullable>(data: data, child: child);
}
