// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_tooltip.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_tooltip.dart';

/// Resolved theme for [LegendTooltip].
class LegendTooltipTheme {
  const LegendTooltipTheme({
    required this.textStyle,
    required this.maxWidth,
    required this.showDelay,
    required this.hideDelay,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendTooltipTheme.defaults(LegendTokens t) => LegendTooltipTheme(
    textStyle: TextRef.b3(t),
    maxWidth: 320,
    showDelay: Duration(milliseconds: 500),
    hideDelay: Duration(milliseconds: 100),
  );

  final TextStyle textStyle;
  final double maxWidth;
  final Duration showDelay;
  final Duration hideDelay;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendTooltip] first, [LegendTooltipThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static LegendTooltipTheme of(
    BuildContext context, [
    LegendTooltipThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendTooltipThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendTooltipAspectTextStyle);
    LegendThemeOverride.depend<LegendTooltipThemeNullable>(
      context,
      _$LegendTooltipOverrideAspectTextStyle,
    );
    LegendTheme.depend(context, _$LegendTooltipAspectMaxWidth);
    LegendThemeOverride.depend<LegendTooltipThemeNullable>(
      context,
      _$LegendTooltipOverrideAspectMaxWidth,
    );
    LegendTheme.depend(context, _$LegendTooltipAspectShowDelay);
    LegendThemeOverride.depend<LegendTooltipThemeNullable>(
      context,
      _$LegendTooltipOverrideAspectShowDelay,
    );
    LegendTheme.depend(context, _$LegendTooltipAspectHideDelay);
    LegendThemeOverride.depend<LegendTooltipThemeNullable>(
      context,
      _$LegendTooltipOverrideAspectHideDelay,
    );
    return LegendTooltipTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendTooltipThemeNullable>(LegendTooltip))
        .merge(override)
        .merge(local);
  }

  LegendTooltipTheme merge(LegendTooltipThemeNullable? other) {
    if (other == null) return this;
    return LegendTooltipTheme(
      textStyle: other.textStyle ?? textStyle,
      maxWidth: other.maxWidth ?? maxWidth,
      showDelay: other.showDelay ?? showDelay,
      hideDelay: other.hideDelay ?? hideDelay,
    );
  }

  LegendTooltipTheme copyWith({
    TextStyle? textStyle,
    double? maxWidth,
    Duration? showDelay,
    Duration? hideDelay,
  }) => LegendTooltipTheme(
    textStyle: textStyle ?? this.textStyle,
    maxWidth: maxWidth ?? this.maxWidth,
    showDelay: showDelay ?? this.showDelay,
    hideDelay: hideDelay ?? this.hideDelay,
  );

  static LegendTooltipTheme lerp(
    LegendTooltipTheme a,
    LegendTooltipTheme b,
    double t,
  ) => LegendTooltipTheme(
    textStyle: t < 0.5 ? a.textStyle : b.textStyle,
    maxWidth: t < 0.5 ? a.maxWidth : b.maxWidth,
    showDelay: t < 0.5 ? a.showDelay : b.showDelay,
    hideDelay: t < 0.5 ? a.hideDelay : b.hideDelay,
  );
}

/// Sparse overrides for [LegendTooltipTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendTooltipThemeNullable {
  const LegendTooltipThemeNullable({
    this.textStyle,
    this.maxWidth,
    this.showDelay,
    this.hideDelay,
  });

  final TextStyle? textStyle;
  final double? maxWidth;
  final Duration? showDelay;
  final Duration? hideDelay;

  LegendTooltipThemeNullable merge(LegendTooltipThemeNullable? other) {
    if (other == null) return this;
    return LegendTooltipThemeNullable(
      textStyle: other.textStyle ?? textStyle,
      maxWidth: other.maxWidth ?? maxWidth,
      showDelay: other.showDelay ?? showDelay,
      hideDelay: other.hideDelay ?? hideDelay,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendTooltipThemeNullable &&
          other.textStyle == textStyle &&
          other.maxWidth == maxWidth &&
          other.showDelay == showDelay &&
          other.hideDelay == hideDelay;

  @override
  int get hashCode =>
      Object.hashAll([textStyle, maxWidth, showDelay, hideDelay]);
}

/// Overrides [LegendTooltipTheme] for a subtree (level 2).
class LegendTooltipThemeOverride extends StatelessWidget {
  const LegendTooltipThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendTooltipThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendTooltipThemeNullable>(data: data, child: child);
}

/// Resolves [LegendTooltip.textStyle] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
TextStyle _$LegendTooltipSelectTextStyle(LegendThemeData data) =>
    data.componentOf<LegendTooltipThemeNullable>(LegendTooltip)?.textStyle ??
    TextRef.b3(data.tokens);
const _$LegendTooltipAspectTextStyle = LegendThemeAspect(
  _$LegendTooltipSelectTextStyle,
);
Object? _$LegendTooltipOverrideSelectTextStyle(
  LegendTooltipThemeNullable data,
) => data.textStyle;
const _$LegendTooltipOverrideAspectTextStyle =
    LegendOverrideAspect<LegendTooltipThemeNullable>(
      _$LegendTooltipOverrideSelectTextStyle,
    );

/// Resolves [LegendTooltip.maxWidth] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
double _$LegendTooltipSelectMaxWidth(LegendThemeData data) =>
    data.componentOf<LegendTooltipThemeNullable>(LegendTooltip)?.maxWidth ??
    320;
const _$LegendTooltipAspectMaxWidth = LegendThemeAspect(
  _$LegendTooltipSelectMaxWidth,
);
Object? _$LegendTooltipOverrideSelectMaxWidth(
  LegendTooltipThemeNullable data,
) => data.maxWidth;
const _$LegendTooltipOverrideAspectMaxWidth =
    LegendOverrideAspect<LegendTooltipThemeNullable>(
      _$LegendTooltipOverrideSelectMaxWidth,
    );

/// Resolves [LegendTooltip.showDelay] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Duration _$LegendTooltipSelectShowDelay(LegendThemeData data) =>
    data.componentOf<LegendTooltipThemeNullable>(LegendTooltip)?.showDelay ??
    Duration(milliseconds: 500);
const _$LegendTooltipAspectShowDelay = LegendThemeAspect(
  _$LegendTooltipSelectShowDelay,
);
Object? _$LegendTooltipOverrideSelectShowDelay(
  LegendTooltipThemeNullable data,
) => data.showDelay;
const _$LegendTooltipOverrideAspectShowDelay =
    LegendOverrideAspect<LegendTooltipThemeNullable>(
      _$LegendTooltipOverrideSelectShowDelay,
    );

/// Resolves [LegendTooltip.hideDelay] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Duration _$LegendTooltipSelectHideDelay(LegendThemeData data) =>
    data.componentOf<LegendTooltipThemeNullable>(LegendTooltip)?.hideDelay ??
    Duration(milliseconds: 100);
const _$LegendTooltipAspectHideDelay = LegendThemeAspect(
  _$LegendTooltipSelectHideDelay,
);
Object? _$LegendTooltipOverrideSelectHideDelay(
  LegendTooltipThemeNullable data,
) => data.hideDelay;
const _$LegendTooltipOverrideAspectHideDelay =
    LegendOverrideAspect<LegendTooltipThemeNullable>(
      _$LegendTooltipOverrideSelectHideDelay,
    );

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class LegendTooltipThemeListenables {
  /// Change stream of the resolved [LegendTooltipTheme.textStyle].
  static ValueListenable<TextStyle> textStyle(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendTooltipSelectTextStyle);

  /// Change stream of the resolved [LegendTooltipTheme.maxWidth].
  static ValueListenable<double> maxWidth(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendTooltipSelectMaxWidth);

  /// Change stream of the resolved [LegendTooltipTheme.showDelay].
  static ValueListenable<Duration> showDelay(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendTooltipSelectShowDelay);

  /// Change stream of the resolved [LegendTooltipTheme.hideDelay].
  static ValueListenable<Duration> hideDelay(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendTooltipSelectHideDelay);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendTooltipThemeResolve on LegendTooltip {
  /// [LegendTooltipTheme.of] with this widget's constructor params as
  /// level 1.
  LegendTooltipTheme _theme(BuildContext context) => LegendTooltipTheme.of(
    context,
    LegendTooltipThemeNullable(
      textStyle: textStyle,
      maxWidth: maxWidth,
      showDelay: showDelay,
      hideDelay: hideDelay,
    ),
  );

  /// Resolves ONLY [LegendTooltip.textStyle] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._textStyle(context)`).
  TextStyle _textStyle(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendTooltipThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendTooltipAspectTextStyle);
    LegendThemeOverride.depend<LegendTooltipThemeNullable>(
      context,
      _$LegendTooltipOverrideAspectTextStyle,
    );
    return textStyle ??
        override?.textStyle ??
        _$LegendTooltipSelectTextStyle(data);
  }

  /// Resolves ONLY [LegendTooltip.maxWidth] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._maxWidth(context)`).
  double _maxWidth(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendTooltipThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendTooltipAspectMaxWidth);
    LegendThemeOverride.depend<LegendTooltipThemeNullable>(
      context,
      _$LegendTooltipOverrideAspectMaxWidth,
    );
    return maxWidth ??
        override?.maxWidth ??
        _$LegendTooltipSelectMaxWidth(data);
  }

  /// Resolves ONLY [LegendTooltip.showDelay] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._showDelay(context)`).
  Duration _showDelay(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendTooltipThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendTooltipAspectShowDelay);
    LegendThemeOverride.depend<LegendTooltipThemeNullable>(
      context,
      _$LegendTooltipOverrideAspectShowDelay,
    );
    return showDelay ??
        override?.showDelay ??
        _$LegendTooltipSelectShowDelay(data);
  }

  /// Resolves ONLY [LegendTooltip.hideDelay] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._hideDelay(context)`).
  Duration _hideDelay(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendTooltipThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendTooltipAspectHideDelay);
    LegendThemeOverride.depend<LegendTooltipThemeNullable>(
      context,
      _$LegendTooltipOverrideAspectHideDelay,
    );
    return hideDelay ??
        override?.hideDelay ??
        _$LegendTooltipSelectHideDelay(data);
  }
}

/// Auto-detected State wiring (RFC-002 R13): [_LegendTooltipState]
/// is this file's `State<LegendTooltip>`, so its
/// build reads the resolved theme as a plain `theme`
/// getter — zero visible wiring. A same-named instance
/// member (e.g. from [_$LegendTooltipThemeState])
/// wins over this extension.
extension _$LegendTooltipThemeOn_LegendTooltipState on _LegendTooltipState {
  LegendTooltipTheme get theme => widget._theme(context);
}

/// Explicit State wiring (RFC-002 R13): mix onto any
/// `State<LegendTooltip>` for the `theme` getter as a
/// real, overridable inherited member — no State-class
/// detection involved.
mixin _$LegendTooltipThemeState on State<LegendTooltip> {
  LegendTooltipTheme get theme => widget._theme(context);
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class LegendTooltip extends
/// _$LegendTooltipBase` receives the resolved
/// [LegendTooltipTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$LegendTooltipBase
    extends LegendStatelessWidget<LegendTooltipTheme> {
  const _$LegendTooltipBase({super.key});

  TextStyle? get textStyle;
  double? get maxWidth;
  Duration? get showDelay;
  Duration? get hideDelay;

  @override
  LegendTooltipTheme resolveThemeOf(BuildContext context) =>
      LegendTooltipTheme.of(
        context,
        LegendTooltipThemeNullable(
          textStyle: textStyle,
          maxWidth: maxWidth,
          showDelay: showDelay,
          hideDelay: hideDelay,
        ),
      );
}
