// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_divider.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendDivider`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_divider.dart.
const List<LegendDocEntry> legendDividerDocEntries = [
  LegendDocEntry(
    owner: 'LegendDivider',
    name: 'color',
    type: 'Color?',
    doc: '',
    defaultDescription: 't.colors.background3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDivider',
    name: 'thickness',
    type: 'double?',
    doc: '',
    defaultDescription: 't.sizes.borderWidth',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDivider',
    name: 'spacing',
    type: 'double?',
    doc: '',
    defaultDescription: 't.sizes.md',
    group: 'component',
  ),
];
