// GENERATED by nomo_gen v0.1.0-dev.0 — do not edit.
// Source: nomo_switch.dart
// ignore_for_file: type=lint

import 'package:flutter/widgets.dart';
import 'package:nomo_ui_kit/nomo_ui_kit.dart';
import 'package:nomo_ui_kit/src/annotations/annotations.dart';
import 'package:nomo_ui_kit/src/primitives/nomo_interactive.dart';
import 'package:nomo_ui_kit/src/theme/nomo_theme.dart';

/// Resolved theme for [NomoSwitch].
class NomoSwitchTheme {
  const NomoSwitchTheme({
    required this.activeTrack,
    required this.inactiveTrack,
    required this.thumb,
    required this.width,
    required this.height,
  });

  /// Token-derived defaults (level 5).
  factory NomoSwitchTheme.defaults(NomoTokens t) => NomoSwitchTheme(
    activeTrack: t.colors.primary,
    inactiveTrack: t.colors.background3,
    thumb: t.colors.surface,
    width: 44.0,
    height: 24.0,
  );

  final Color activeTrack;
  final Color inactiveTrack;
  final Color thumb;
  final double width;
  final double height;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static NomoSwitchTheme of(
    BuildContext context, [
    NomoSwitchThemeNullable? local,
  ]) {
    final data = NomoTheme.of(context);
    return NomoSwitchTheme.defaults(data.tokens)
        .merge(data.component<NomoSwitchThemeNullable>())
        .merge(NomoThemeOverride.maybeOf<NomoSwitchThemeNullable>(context))
        .merge(local);
  }

  NomoSwitchTheme merge(NomoSwitchThemeNullable? other) {
    if (other == null) return this;
    return NomoSwitchTheme(
      activeTrack: other.activeTrack ?? activeTrack,
      inactiveTrack: other.inactiveTrack ?? inactiveTrack,
      thumb: other.thumb ?? thumb,
      width: other.width ?? width,
      height: other.height ?? height,
    );
  }

  NomoSwitchTheme copyWith({
    Color? activeTrack,
    Color? inactiveTrack,
    Color? thumb,
    double? width,
    double? height,
  }) => NomoSwitchTheme(
    activeTrack: activeTrack ?? this.activeTrack,
    inactiveTrack: inactiveTrack ?? this.inactiveTrack,
    thumb: thumb ?? this.thumb,
    width: width ?? this.width,
    height: height ?? this.height,
  );

  static NomoSwitchTheme lerp(NomoSwitchTheme a, NomoSwitchTheme b, double t) =>
      NomoSwitchTheme(
        activeTrack: Color.lerp(a.activeTrack, b.activeTrack, t)!,
        inactiveTrack: Color.lerp(a.inactiveTrack, b.inactiveTrack, t)!,
        thumb: t < 0.5 ? a.thumb : b.thumb,
        width: t < 0.5 ? a.width : b.width,
        height: t < 0.5 ? a.height : b.height,
      );
}

/// Sparse overrides for [NomoSwitchTheme]; null means "inherit".
class NomoSwitchThemeNullable {
  const NomoSwitchThemeNullable({
    this.activeTrack,
    this.inactiveTrack,
    this.thumb,
    this.width,
    this.height,
  });

  final Color? activeTrack;
  final Color? inactiveTrack;
  final Color? thumb;
  final double? width;
  final double? height;

  NomoSwitchThemeNullable merge(NomoSwitchThemeNullable? other) {
    if (other == null) return this;
    return NomoSwitchThemeNullable(
      activeTrack: other.activeTrack ?? activeTrack,
      inactiveTrack: other.inactiveTrack ?? inactiveTrack,
      thumb: other.thumb ?? thumb,
      width: other.width ?? width,
      height: other.height ?? height,
    );
  }
}

/// Overrides [NomoSwitchTheme] for a subtree (level 2).
class NomoSwitchThemeOverride extends StatelessWidget {
  const NomoSwitchThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final NomoSwitchThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      NomoThemeOverride<NomoSwitchThemeNullable>(data: data, child: child);
}
