// GENERATED by nomo_gen v0.1.0-dev.0 — do not edit.
// Source: nomo_loading.dart
// ignore_for_file: type=lint

import 'dart:math' as math;
import 'package:flutter/widgets.dart';
import 'package:nomo_ui_kit/nomo_ui_kit.dart';
import 'package:nomo_ui_kit/src/annotations/annotations.dart';

/// Resolved theme for [NomoLoading].
class NomoLoadingTheme {
  const NomoLoadingTheme({
    required this.color,
    required this.size,
    required this.strokeWidth,
  });

  /// Token-derived defaults (level 5).
  factory NomoLoadingTheme.defaults(NomoTokens t) =>
      NomoLoadingTheme(color: t.colors.primary, size: 24.0, strokeWidth: 3.0);

  final Color color;
  final double size;
  final double strokeWidth;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static NomoLoadingTheme of(
    BuildContext context, [
    NomoLoadingThemeNullable? local,
  ]) {
    final data = NomoTheme.of(context);
    return NomoLoadingTheme.defaults(data.tokens)
        .merge(data.component<NomoLoadingThemeNullable>())
        .merge(NomoThemeOverride.maybeOf<NomoLoadingThemeNullable>(context))
        .merge(local);
  }

  NomoLoadingTheme merge(NomoLoadingThemeNullable? other) {
    if (other == null) return this;
    return NomoLoadingTheme(
      color: other.color ?? color,
      size: other.size ?? size,
      strokeWidth: other.strokeWidth ?? strokeWidth,
    );
  }

  NomoLoadingTheme copyWith({
    Color? color,
    double? size,
    double? strokeWidth,
  }) => NomoLoadingTheme(
    color: color ?? this.color,
    size: size ?? this.size,
    strokeWidth: strokeWidth ?? this.strokeWidth,
  );

  static NomoLoadingTheme lerp(
    NomoLoadingTheme a,
    NomoLoadingTheme b,
    double t,
  ) => NomoLoadingTheme(
    color: t < 0.5 ? a.color : b.color,
    size: t < 0.5 ? a.size : b.size,
    strokeWidth: t < 0.5 ? a.strokeWidth : b.strokeWidth,
  );
}

/// Sparse overrides for [NomoLoadingTheme]; null means "inherit".
class NomoLoadingThemeNullable {
  const NomoLoadingThemeNullable({this.color, this.size, this.strokeWidth});

  final Color? color;
  final double? size;
  final double? strokeWidth;

  NomoLoadingThemeNullable merge(NomoLoadingThemeNullable? other) {
    if (other == null) return this;
    return NomoLoadingThemeNullable(
      color: other.color ?? color,
      size: other.size ?? size,
      strokeWidth: other.strokeWidth ?? strokeWidth,
    );
  }
}

/// Overrides [NomoLoadingTheme] for a subtree (level 2).
class NomoLoadingThemeOverride extends StatelessWidget {
  const NomoLoadingThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final NomoLoadingThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      NomoThemeOverride<NomoLoadingThemeNullable>(data: data, child: child);
}
