// GENERATED by legend_gen v0.1.0-dev.0 — do not edit.
// Source: legend_card.dart
// ignore_for_file: type=lint, unused_import

import 'legend_card.dart';
import 'package:flutter/widgets.dart';
import 'package:legend_ui/legend_ui.dart';
import 'package:legend_ui/src/annotations/annotations.dart';
import 'package:legend_ui/src/primitives/legend_interactive.dart';
import 'package:legend_ui/src/primitives/legend_surface.dart';

/// Resolved theme for [LegendCard].
class LegendCardTheme {
  const LegendCardTheme({
    required this.background,
    required this.borderRadius,
    required this.padding,
    required this.shadows,
  });

  /// Token-derived defaults (level 5).
  factory LegendCardTheme.defaults(LegendTokens t) => LegendCardTheme(
    background: t.colors.surface,
    borderRadius: t.sizes.borderRadiusLg,
    padding: EdgeInsets.all(t.sizes.md),
    shadows: t.shadows.low,
  );

  final Color background;
  final BorderRadius borderRadius;
  final EdgeInsetsGeometry padding;
  final List<BoxShadow> shadows;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static LegendCardTheme of(
    BuildContext context, [
    LegendCardThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    return LegendCardTheme.defaults(data.tokens)
        .merge(data.component<LegendCardThemeNullable>())
        .merge(LegendThemeOverride.maybeOf<LegendCardThemeNullable>(context))
        .merge(local);
  }

  LegendCardTheme merge(LegendCardThemeNullable? other) {
    if (other == null) return this;
    return LegendCardTheme(
      background: other.background ?? background,
      borderRadius: other.borderRadius ?? borderRadius,
      padding: other.padding ?? padding,
      shadows: other.shadows ?? shadows,
    );
  }

  LegendCardTheme copyWith({
    Color? background,
    BorderRadius? borderRadius,
    EdgeInsetsGeometry? padding,
    List<BoxShadow>? shadows,
  }) => LegendCardTheme(
    background: background ?? this.background,
    borderRadius: borderRadius ?? this.borderRadius,
    padding: padding ?? this.padding,
    shadows: shadows ?? this.shadows,
  );

  static LegendCardTheme lerp(LegendCardTheme a, LegendCardTheme b, double t) =>
      LegendCardTheme(
        background: Color.lerp(a.background, b.background, t)!,
        borderRadius: t < 0.5 ? a.borderRadius : b.borderRadius,
        padding: t < 0.5 ? a.padding : b.padding,
        shadows: t < 0.5 ? a.shadows : b.shadows,
      );
}

/// Sparse overrides for [LegendCardTheme]; null means "inherit".
class LegendCardThemeNullable {
  const LegendCardThemeNullable({
    this.background,
    this.borderRadius,
    this.padding,
    this.shadows,
  });

  final Color? background;
  final BorderRadius? borderRadius;
  final EdgeInsetsGeometry? padding;
  final List<BoxShadow>? shadows;

  LegendCardThemeNullable merge(LegendCardThemeNullable? other) {
    if (other == null) return this;
    return LegendCardThemeNullable(
      background: other.background ?? background,
      borderRadius: other.borderRadius ?? borderRadius,
      padding: other.padding ?? padding,
      shadows: other.shadows ?? shadows,
    );
  }
}

/// Overrides [LegendCardTheme] for a subtree (level 2).
class LegendCardThemeOverride extends StatelessWidget {
  const LegendCardThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendCardThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendCardThemeNullable>(data: data, child: child);
}
