import 'package:dart_style/dart_style.dart';
import 'package:legend_gen/src/model.dart';
import 'package:legend_gen/src/version.dart';

/// Emits the generated theme part file for all themable widgets of one
/// source file (DESIGN.md §2.3 + RFC-002 R1): `XTheme`, `XThemeNullable`
/// (with value `==`, R2), `XThemeOverride`, `XTheme.defaults(tokens)`,
/// `merge`/`copyWith`/`lerp`, `XTheme.of` (both-keys registry lookup, R3),
/// and the private in-library `_theme(BuildContext)` resolver extension.
///
/// The output is `part of` the widget's library: it has no imports of its
/// own (the widget file's imports serve the whole library) and may call
/// the widget's private `.resolve` tear-offs.
String emitThemeFile(List<ThemableWidget> widgets) {
  assert(widgets.isNotEmpty, 'emitThemeFile needs at least one widget');
  final buffer = StringBuffer()
    ..writeln(_header(widgets.first.sourceBasename))
    ..writeln("part of '${widgets.first.sourceBasename}';");

  for (final widget in widgets) {
    _emitWidget(buffer, widget);
  }
  return _format(buffer.toString());
}

String _header(String sourceBasename) =>
    '// GENERATED by legend_gen v$legendGenVersion — do not edit.\n'
    '// Source: $sourceBasename\n'
    '// ignore_for_file: type=lint, unused_element';

String _format(String code) => DartFormatter(
  languageVersion: DartFormatter.latestLanguageVersion,
).format(code);

void _emitWidget(StringBuffer b, ThemableWidget widget) {
  final theme = '${widget.className}Theme';
  final nullable = '${widget.className}ThemeNullable';
  final override = '${widget.className}ThemeOverride';
  final fields = widget.fields;
  final derivedColorStates = fields
      .where((f) => f.statesInnerType == 'Color')
      .toList();

  // ── Resolved theme ────────────────────────────────────────────────
  b
    ..writeln()
    ..writeln('/// Resolved theme for [${widget.className}].')
    ..writeln('class $theme {')
    ..writeln('const $theme({')
    ..writeln(fields.map((f) => 'required this.${f.name},').join())
    ..writeln('});')
    ..writeln()
    ..writeln('/// Token-derived defaults (level 4) — the annotation')
    ..writeln('/// defaults ARE the kit defaults (DESIGN.md §9.9).')
    ..writeln('factory $theme.defaults(LegendTokens t) => $theme(')
    ..writeln(fields.map((f) => '${f.name}: ${_defaultExpression(f)},').join())
    ..writeln(');')
    ..writeln()
    ..writeln(fields.map((f) => 'final ${f.themeType} ${f.name};').join());

  // of(): the four-level resolution chain (DESIGN.md §1 goal 3).
  b
    ..writeln()
    ..writeln('/// Resolves the theme: defaults <- app registry (keyed by')
    ..writeln('/// [${widget.className}] first, [$nullable] as the legacy')
    ..writeln('/// fallback — RFC-002 R3) <- subtree override <- constructor')
    ..writeln('/// params ([local]).');
  if (derivedColorStates.isNotEmpty) {
    b
      ..writeln('///')
      ..writeln('/// Post-merge, unset `LegendStates<Color>` members fill')
      ..writeln('/// from the resolved `normal` via `tokens.states`')
      ..writeln('/// (RFC-002 R6) — named members at any level always win.');
  }
  b
    ..writeln('static $theme of(BuildContext context, [$nullable? local]) {')
    ..writeln('final data = LegendTheme.of(context);')
    ..writeln('final resolved = $theme.defaults(data.tokens)')
    ..writeln('.merge(data.componentOf<$nullable>(${widget.className}))')
    ..writeln('.merge(LegendThemeOverride.maybeOf<$nullable>(context))')
    ..writeln('.merge(local);');
  if (derivedColorStates.isEmpty) {
    b.writeln('return resolved;');
  } else {
    b
      ..writeln('return resolved.copyWith(')
      ..writeln(
        derivedColorStates
            .map(
              (f) =>
                  '${f.name}: resolved.${f.name}'
                  '${f.kind == StyleDefaultKind.none ? '?' : ''}'
                  '.withDerived(data.tokens.states),',
            )
            .join(),
      )
      ..writeln(');');
  }
  b.writeln('}');

  b
    ..writeln()
    ..writeln('$theme merge($nullable? other) {')
    ..writeln('if (other == null) return this;')
    ..writeln('return $theme(')
    ..writeln(
      fields
          .map((f) => '${f.name}: ${_mergeExpression(f, sparse: false)},')
          .join(),
    )
    ..writeln(');')
    ..writeln('}');

  b
    ..writeln()
    ..writeln('$theme copyWith({')
    ..writeln(fields.map((f) => '${f.type} ${f.name},').join())
    ..writeln('}) => $theme(')
    ..writeln(
      fields.map((f) => '${f.name}: ${f.name} ?? this.${f.name},').join(),
    )
    ..writeln(');');

  b
    ..writeln()
    ..writeln('static $theme lerp($theme a, $theme b, double t) => $theme(')
    ..writeln(fields.map((f) => '${f.name}: ${_lerpExpression(f)},').join())
    ..writeln(');')
    ..writeln('}');

  // ── Sparse theme (levels 1–3) ─────────────────────────────────────
  b
    ..writeln()
    ..writeln('/// Sparse overrides for [$theme]; null means "inherit".')
    ..writeln('/// Value-compared (RFC-002 R2), so rebuilding an ancestor')
    ..writeln('/// with an equal override never invalidates dependents.')
    ..writeln('class $nullable {')
    ..writeln('const $nullable({')
    ..writeln(fields.map((f) => 'this.${f.name},').join())
    ..writeln('});')
    ..writeln()
    ..writeln(fields.map((f) => 'final ${f.type} ${f.name};').join())
    ..writeln()
    ..writeln('$nullable merge($nullable? other) {')
    ..writeln('if (other == null) return this;')
    ..writeln('return $nullable(')
    ..writeln(
      fields
          .map((f) => '${f.name}: ${_mergeExpression(f, sparse: true)},')
          .join(),
    )
    ..writeln(');')
    ..writeln('}')
    ..writeln()
    ..writeln('@override')
    ..writeln('bool operator ==(Object other) =>')
    ..writeln('identical(this, other) ||')
    ..writeln('other is $nullable')
    ..writeln(fields.map((f) => '&& other.${f.name} == ${f.name}').join())
    ..writeln(';')
    ..writeln()
    ..writeln('@override')
    ..writeln('int get hashCode => Object.hashAll([')
    ..writeln(fields.map((f) => '${f.name},').join())
    ..writeln(']);')
    ..writeln('}');

  // ── Subtree override widget (level 2) ─────────────────────────────
  b
    ..writeln()
    ..writeln('/// Overrides [$theme] for a subtree (level 2).')
    ..writeln('class $override extends StatelessWidget {')
    ..writeln('const $override({')
    ..writeln('required this.data, required this.child, super.key,')
    ..writeln('});')
    ..writeln()
    ..writeln('final $nullable data;')
    ..writeln('final Widget child;')
    ..writeln()
    ..writeln('@override')
    ..writeln('Widget build(BuildContext context) =>')
    ..writeln('LegendThemeOverride<$nullable>(data: data, child: child);')
    ..writeln('}');

  // ── Private in-library resolver (RFC-002 R1) ──────────────────────
  b
    ..writeln()
    ..writeln('/// In-library resolver (RFC-002 R1): re-lists the themed')
    ..writeln('/// fields so the widget author never does — build calls')
    ..writeln('/// `_theme(context)` (`widget._theme(context)` from a State).')
    ..writeln(
      'extension _\$${widget.className}ThemeResolve '
      'on ${widget.className} {',
    )
    ..writeln("/// [$theme.of] with this widget's constructor params as")
    ..writeln('/// level 1.')
    ..writeln('$theme _theme(BuildContext context) => $theme.of(')
    ..writeln('context,')
    ..writeln('$nullable(')
    ..writeln(fields.map((f) => '${f.name}: ${f.name},').join())
    ..writeln('),')
    ..writeln(');')
    ..writeln('}');
}

String _defaultExpression(StyledField f) {
  return switch (f.kind) {
    StyleDefaultKind.value => f.defaultCode,
    StyleDefaultKind.resolve => '${f.defaultCode}(t)',
    StyleDefaultKind.none => 'null',
  };
}

String _mergeExpression(StyledField f, {required bool sparse}) {
  final n = f.name;
  if (!f.isStates) return 'other.$n ?? $n';
  // LegendStates<T> merges member-wise sparse (RFC-002 R6): a level that
  // names only one state variant never clobbers another level's members.
  final merged = 'LegendStates.merge($n, other.$n)';
  if (sparse || f.kind == StyleDefaultKind.none) return merged;
  return '$merged ?? $n';
}

String _lerpExpression(StyledField f) {
  final n = f.name;
  if (!f.lerp) return 't < 0.5 ? a.$n : b.$n';
  final nullable = f.kind == StyleDefaultKind.none;

  final inner = f.statesInnerType;
  if (inner != null) {
    final lerper = switch (inner) {
      'Color' => 'Color.lerp',
      _ =>
        '(x, y, u) => '
            'x == null || y == null ? (u < 0.5 ? x : y) : x + (y - x) * u',
    };
    final call =
        'LegendStates.lerpWith(a.$n${nullable ? '!' : ''}, '
        'b.$n${nullable ? '!' : ''}, t, $lerper)';
    if (!nullable) return call;
    return 'a.$n == null || b.$n == null ? (t < 0.5 ? a.$n : b.$n) : $call';
  }

  return switch (f.resolvedType) {
    // No `lerpDouble` — dart:ui isn't importable from a part file, and the
    // arithmetic form is null-safe by construction.
    'double' when nullable =>
      'a.$n == null || b.$n == null '
          '? (t < 0.5 ? a.$n : b.$n) '
          ': a.$n! + (b.$n! - a.$n!) * t',
    'double' => 'a.$n + (b.$n - a.$n) * t',
    'Color' => 'Color.lerp(a.$n, b.$n, t)${nullable ? '' : '!'}',
    'EdgeInsets' =>
      'EdgeInsetsGeometry.lerp(a.$n, b.$n, t)'
          '${nullable ? ' as EdgeInsets?' : '! as EdgeInsets'}',
    'EdgeInsetsGeometry' =>
      'EdgeInsetsGeometry.lerp(a.$n, b.$n, t)${nullable ? '' : '!'}',
    'BorderRadius' => 'BorderRadius.lerp(a.$n, b.$n, t)${nullable ? '' : '!'}',
    'TextStyle' => 'TextStyle.lerp(a.$n, b.$n, t)${nullable ? '' : '!'}',
    _ => 't < 0.5 ? a.$n : b.$n',
  };
}

// ── legend_gen docs (RFC-002 R9) ──────────────────────────────────────

/// Emits the docs manifest for all themable widgets of one source file:
/// one `const List<LegendDocEntry>` per widget, one entry per themed
/// variable (plus one per named state member of a `LegendStates` field),
/// each carrying the field's dartdoc and default source text.
///
/// Unlike the theme artifact this is a separate importable library — apps
/// aggregate manifests by importing the ones they care about.
String emitDocsFile(List<ThemableWidget> widgets) {
  assert(widgets.isNotEmpty, 'emitDocsFile needs at least one widget');
  final buffer = StringBuffer()
    ..writeln(_header(widgets.first.sourceBasename))
    ..writeln()
    ..writeln("import 'package:legend_ui/legend_ui.dart';");

  for (final widget in widgets) {
    final listName = '${_lowerCamel(widget.className)}DocEntries';
    buffer
      ..writeln()
      ..writeln('/// Theme docs manifest for `${widget.className}`')
      ..writeln('/// (RFC-002 R9): one entry per themed variable, extracted')
      ..writeln('/// from the dartdoc in ${widget.sourceBasename}.')
      ..writeln('const List<LegendDocEntry> $listName = [');
    for (final field in widget.fields) {
      _emitDocEntry(buffer, widget, field, field.name, field.type);
      final inner = field.statesInnerType;
      if (inner != null) {
        for (final member in _statesMembers) {
          _emitDocEntry(
            buffer,
            widget,
            field,
            '${field.name}.$member',
            '$inner?',
          );
        }
      }
    }
    buffer.writeln('];');
  }
  return _format(buffer.toString());
}

const _statesMembers = ['normal', 'hovered', 'pressed', 'focused', 'disabled'];

void _emitDocEntry(
  StringBuffer b,
  ThemableWidget widget,
  StyledField field,
  String name,
  String type,
) {
  b
    ..writeln('LegendDocEntry(')
    ..writeln("owner: '${_escape(widget.className)}',")
    ..writeln("name: '${_escape(name)}',")
    ..writeln("type: '${_escape(type)}',")
    ..writeln("doc: '${_escape(field.doc)}',")
    ..writeln("defaultDescription: '${_escape(field.defaultDescription)}',")
    ..writeln("group: 'component',")
    ..writeln('),');
}

String _lowerCamel(String name) => name[0].toLowerCase() + name.substring(1);

/// Escapes [value] for a single-quoted Dart string literal.
String _escape(String value) => value
    .replaceAll(r'\', r'\\')
    .replaceAll(r'$', r'\$')
    .replaceAll("'", r"\'")
    .replaceAll('\n', r'\n');
