// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_list.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_list.dart';

/// Resolved theme for [LegendList].
class LegendListTheme {
  const LegendListTheme({
    required this.headerStyle,
    required this.headerPadding,
    required this.spacing,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendListTheme.defaults(LegendTokens t) => LegendListTheme(
    headerStyle: _headerStyle(t),
    headerPadding: _headerPadding(t),
    spacing: SizeRef.xs(t),
  );

  final TextStyle headerStyle;
  final EdgeInsetsGeometry headerPadding;
  final double spacing;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendList] first, [LegendListThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static LegendListTheme of(
    BuildContext context, [
    LegendListThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendListThemeNullable>(context);
    LegendTheme.depend(context, _$LegendListAspectHeaderStyle);
    LegendThemeOverride.depend<LegendListThemeNullable>(
      context,
      _$LegendListOverrideAspectHeaderStyle,
    );
    LegendTheme.depend(context, _$LegendListAspectHeaderPadding);
    LegendThemeOverride.depend<LegendListThemeNullable>(
      context,
      _$LegendListOverrideAspectHeaderPadding,
    );
    LegendTheme.depend(context, _$LegendListAspectSpacing);
    LegendThemeOverride.depend<LegendListThemeNullable>(
      context,
      _$LegendListOverrideAspectSpacing,
    );
    return LegendListTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendListThemeNullable>(LegendList))
        .merge(override)
        .merge(local);
  }

  LegendListTheme merge(LegendListThemeNullable? other) {
    if (other == null) return this;
    return LegendListTheme(
      headerStyle: other.headerStyle ?? headerStyle,
      headerPadding: other.headerPadding ?? headerPadding,
      spacing: other.spacing ?? spacing,
    );
  }

  LegendListTheme copyWith({
    TextStyle? headerStyle,
    EdgeInsetsGeometry? headerPadding,
    double? spacing,
  }) => LegendListTheme(
    headerStyle: headerStyle ?? this.headerStyle,
    headerPadding: headerPadding ?? this.headerPadding,
    spacing: spacing ?? this.spacing,
  );

  static LegendListTheme lerp(LegendListTheme a, LegendListTheme b, double t) =>
      LegendListTheme(
        headerStyle: t < 0.5 ? a.headerStyle : b.headerStyle,
        headerPadding: t < 0.5 ? a.headerPadding : b.headerPadding,
        spacing: t < 0.5 ? a.spacing : b.spacing,
      );
}

/// Sparse overrides for [LegendListTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendListThemeNullable {
  const LegendListThemeNullable({
    this.headerStyle,
    this.headerPadding,
    this.spacing,
  });

  final TextStyle? headerStyle;
  final EdgeInsetsGeometry? headerPadding;
  final double? spacing;

  LegendListThemeNullable merge(LegendListThemeNullable? other) {
    if (other == null) return this;
    return LegendListThemeNullable(
      headerStyle: other.headerStyle ?? headerStyle,
      headerPadding: other.headerPadding ?? headerPadding,
      spacing: other.spacing ?? spacing,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendListThemeNullable &&
          other.headerStyle == headerStyle &&
          other.headerPadding == headerPadding &&
          other.spacing == spacing;

  @override
  int get hashCode => Object.hashAll([headerStyle, headerPadding, spacing]);
}

/// Overrides [LegendListTheme] for a subtree (level 2).
class LegendListThemeOverride extends StatelessWidget {
  const LegendListThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendListThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendListThemeNullable>(data: data, child: child);
}

/// Resolves [LegendList.headerStyle] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
TextStyle _$LegendListSelectHeaderStyle(LegendThemeData data) =>
    data.componentOf<LegendListThemeNullable>(LegendList)?.headerStyle ??
    _headerStyle(data.tokens);
const _$LegendListAspectHeaderStyle = LegendThemeAspect(
  _$LegendListSelectHeaderStyle,
);
Object? _$LegendListOverrideSelectHeaderStyle(LegendListThemeNullable data) =>
    data.headerStyle;
const _$LegendListOverrideAspectHeaderStyle =
    LegendOverrideAspect<LegendListThemeNullable>(
      _$LegendListOverrideSelectHeaderStyle,
    );

/// Resolves [LegendList.headerPadding] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
EdgeInsetsGeometry _$LegendListSelectHeaderPadding(LegendThemeData data) =>
    data.componentOf<LegendListThemeNullable>(LegendList)?.headerPadding ??
    _headerPadding(data.tokens);
const _$LegendListAspectHeaderPadding = LegendThemeAspect(
  _$LegendListSelectHeaderPadding,
);
Object? _$LegendListOverrideSelectHeaderPadding(LegendListThemeNullable data) =>
    data.headerPadding;
const _$LegendListOverrideAspectHeaderPadding =
    LegendOverrideAspect<LegendListThemeNullable>(
      _$LegendListOverrideSelectHeaderPadding,
    );

/// Resolves [LegendList.spacing] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
double _$LegendListSelectSpacing(LegendThemeData data) =>
    data.componentOf<LegendListThemeNullable>(LegendList)?.spacing ??
    SizeRef.xs(data.tokens);
const _$LegendListAspectSpacing = LegendThemeAspect(_$LegendListSelectSpacing);
Object? _$LegendListOverrideSelectSpacing(LegendListThemeNullable data) =>
    data.spacing;
const _$LegendListOverrideAspectSpacing =
    LegendOverrideAspect<LegendListThemeNullable>(
      _$LegendListOverrideSelectSpacing,
    );

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class LegendListThemeListenables {
  /// Change stream of the resolved [LegendListTheme.headerStyle].
  static ValueListenable<TextStyle> headerStyle(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendListSelectHeaderStyle);

  /// Change stream of the resolved [LegendListTheme.headerPadding].
  static ValueListenable<EdgeInsetsGeometry> headerPadding(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendListSelectHeaderPadding);

  /// Change stream of the resolved [LegendListTheme.spacing].
  static ValueListenable<double> spacing(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendListSelectSpacing);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendListThemeResolve on LegendList {
  /// [LegendListTheme.of] with this widget's constructor params as
  /// level 1.
  LegendListTheme _theme(BuildContext context) => LegendListTheme.of(
    context,
    LegendListThemeNullable(
      headerStyle: headerStyle,
      headerPadding: headerPadding,
      spacing: spacing,
    ),
  );

  /// Resolves ONLY [LegendList.headerStyle] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._headerStyle(context)`).
  TextStyle _headerStyle(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendListThemeNullable>(context);
    LegendTheme.depend(context, _$LegendListAspectHeaderStyle);
    LegendThemeOverride.depend<LegendListThemeNullable>(
      context,
      _$LegendListOverrideAspectHeaderStyle,
    );
    return headerStyle ??
        override?.headerStyle ??
        _$LegendListSelectHeaderStyle(data);
  }

  /// Resolves ONLY [LegendList.headerPadding] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._headerPadding(context)`).
  EdgeInsetsGeometry _headerPadding(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendListThemeNullable>(context);
    LegendTheme.depend(context, _$LegendListAspectHeaderPadding);
    LegendThemeOverride.depend<LegendListThemeNullable>(
      context,
      _$LegendListOverrideAspectHeaderPadding,
    );
    return headerPadding ??
        override?.headerPadding ??
        _$LegendListSelectHeaderPadding(data);
  }

  /// Resolves ONLY [LegendList.spacing] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._spacing(context)`).
  double _spacing(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendListThemeNullable>(context);
    LegendTheme.depend(context, _$LegendListAspectSpacing);
    LegendThemeOverride.depend<LegendListThemeNullable>(
      context,
      _$LegendListOverrideAspectSpacing,
    );
    return spacing ?? override?.spacing ?? _$LegendListSelectSpacing(data);
  }
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class LegendList extends
/// _$LegendListBase` receives the resolved
/// [LegendListTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$LegendListBase extends LegendStatelessWidget<LegendListTheme> {
  const _$LegendListBase({super.key});

  TextStyle? get headerStyle;
  EdgeInsetsGeometry? get headerPadding;
  double? get spacing;

  @override
  LegendListTheme resolveThemeOf(BuildContext context) => LegendListTheme.of(
    context,
    LegendListThemeNullable(
      headerStyle: headerStyle,
      headerPadding: headerPadding,
      spacing: spacing,
    ),
  );
}
