// GENERATED by legend_gen v0.1.0-dev.0 — do not edit.
// Source: legend_dialog.dart
// ignore_for_file: type=lint, unused_import

import 'legend_dialog.dart';
import 'package:flutter/widgets.dart';
import 'package:legend_ui/legend_ui.dart';
import 'package:legend_ui/src/annotations/annotations.dart';
import 'package:legend_ui/src/primitives/legend_modal.dart';
import 'package:legend_ui/src/primitives/legend_surface.dart';
import 'package:legend_ui/src/theme/legend_theme.dart';

/// Resolved theme for [LegendDialog].
class LegendDialogTheme {
  const LegendDialogTheme({
    required this.background,
    required this.borderRadius,
    required this.padding,
    required this.maxWidth,
  });

  /// Token-derived defaults (level 5).
  factory LegendDialogTheme.defaults(LegendTokens t) => LegendDialogTheme(
    background: t.colors.surface,
    borderRadius: t.sizes.borderRadiusLg,
    padding: EdgeInsets.all(t.sizes.lg),
    maxWidth: 420.0,
  );

  final Color background;
  final BorderRadius borderRadius;
  final EdgeInsetsGeometry padding;
  final double maxWidth;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static LegendDialogTheme of(
    BuildContext context, [
    LegendDialogThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    return LegendDialogTheme.defaults(data.tokens)
        .merge(data.component<LegendDialogThemeNullable>())
        .merge(LegendThemeOverride.maybeOf<LegendDialogThemeNullable>(context))
        .merge(local);
  }

  LegendDialogTheme merge(LegendDialogThemeNullable? other) {
    if (other == null) return this;
    return LegendDialogTheme(
      background: other.background ?? background,
      borderRadius: other.borderRadius ?? borderRadius,
      padding: other.padding ?? padding,
      maxWidth: other.maxWidth ?? maxWidth,
    );
  }

  LegendDialogTheme copyWith({
    Color? background,
    BorderRadius? borderRadius,
    EdgeInsetsGeometry? padding,
    double? maxWidth,
  }) => LegendDialogTheme(
    background: background ?? this.background,
    borderRadius: borderRadius ?? this.borderRadius,
    padding: padding ?? this.padding,
    maxWidth: maxWidth ?? this.maxWidth,
  );

  static LegendDialogTheme lerp(
    LegendDialogTheme a,
    LegendDialogTheme b,
    double t,
  ) => LegendDialogTheme(
    background: t < 0.5 ? a.background : b.background,
    borderRadius: t < 0.5 ? a.borderRadius : b.borderRadius,
    padding: t < 0.5 ? a.padding : b.padding,
    maxWidth: t < 0.5 ? a.maxWidth : b.maxWidth,
  );
}

/// Sparse overrides for [LegendDialogTheme]; null means "inherit".
class LegendDialogThemeNullable {
  const LegendDialogThemeNullable({
    this.background,
    this.borderRadius,
    this.padding,
    this.maxWidth,
  });

  final Color? background;
  final BorderRadius? borderRadius;
  final EdgeInsetsGeometry? padding;
  final double? maxWidth;

  LegendDialogThemeNullable merge(LegendDialogThemeNullable? other) {
    if (other == null) return this;
    return LegendDialogThemeNullable(
      background: other.background ?? background,
      borderRadius: other.borderRadius ?? borderRadius,
      padding: other.padding ?? padding,
      maxWidth: other.maxWidth ?? maxWidth,
    );
  }
}

/// Overrides [LegendDialogTheme] for a subtree (level 2).
class LegendDialogThemeOverride extends StatelessWidget {
  const LegendDialogThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendDialogThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendDialogThemeNullable>(data: data, child: child);
}
