// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_badge.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendBadge`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_badge.dart.
const List<LegendDocEntry> legendBadgeDocEntries = [
  LegendDocEntry(
    owner: 'LegendBadge',
    name: 'background',
    type: 'Color?',
    doc: 'Fill of the badge surface.',
    defaultDescription: 'ColorRef.error',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendBadge',
    name: 'foreground',
    type: 'Color?',
    doc: 'Color of the label/count text.',
    defaultDescription: 'ColorRef.onError',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendBadge',
    name: 'dotSize',
    type: 'double?',
    doc: 'Diameter of the [LegendBadge.dot] fill.',
    defaultDescription: 'SizeRef.sm',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendBadge',
    name: 'padding',
    type: 'EdgeInsetsGeometry?',
    doc: 'Inner padding of the label/count pill.',
    defaultDescription:
        'EdgeInsets.symmetric(horizontal: t.sizes.sm * 0.75, vertical: t.sizes.xs * 0.5)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendBadge',
    name: 'ringColor',
    type: 'Color?',
    doc: 'Color of the contrast ring drawn when anchored over a [child].',
    defaultDescription: 'ColorRef.surface',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendBadge',
    name: 'ringWidth',
    type: 'double?',
    doc:
        'Stroke width of the contrast ring drawn when anchored over a [child].',
    defaultDescription: 't.sizes.borderWidth * 2',
    group: 'component',
  ),
];
