// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_sider.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendSider`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_sider.dart.
const List<LegendDocEntry> legendSiderDocEntries = [
  LegendDocEntry(
    owner: 'LegendSider',
    name: 'background',
    type: 'LegendStates<Color>?',
    doc:
        'Fill of the sider surface and its items, per interaction state —\n`normal` paints the whole rail, `hovered`/`pressed`/`focused`\nhighlight the item under the pointer (a selected item uses the\n`primaryContainer` token instead).',
    defaultDescription:
        'LegendStates(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSider',
    name: 'background.normal',
    type: 'Color?',
    doc:
        'Fill of the sider surface and its items, per interaction state —\n`normal` paints the whole rail, `hovered`/`pressed`/`focused`\nhighlight the item under the pointer (a selected item uses the\n`primaryContainer` token instead).',
    defaultDescription:
        'LegendStates(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSider',
    name: 'background.hovered',
    type: 'Color?',
    doc:
        'Fill of the sider surface and its items, per interaction state —\n`normal` paints the whole rail, `hovered`/`pressed`/`focused`\nhighlight the item under the pointer (a selected item uses the\n`primaryContainer` token instead).',
    defaultDescription:
        'LegendStates(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSider',
    name: 'background.pressed',
    type: 'Color?',
    doc:
        'Fill of the sider surface and its items, per interaction state —\n`normal` paints the whole rail, `hovered`/`pressed`/`focused`\nhighlight the item under the pointer (a selected item uses the\n`primaryContainer` token instead).',
    defaultDescription:
        'LegendStates(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSider',
    name: 'background.focused',
    type: 'Color?',
    doc:
        'Fill of the sider surface and its items, per interaction state —\n`normal` paints the whole rail, `hovered`/`pressed`/`focused`\nhighlight the item under the pointer (a selected item uses the\n`primaryContainer` token instead).',
    defaultDescription:
        'LegendStates(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSider',
    name: 'background.disabled',
    type: 'Color?',
    doc:
        'Fill of the sider surface and its items, per interaction state —\n`normal` paints the whole rail, `hovered`/`pressed`/`focused`\nhighlight the item under the pointer (a selected item uses the\n`primaryContainer` token instead).',
    defaultDescription:
        'LegendStates(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSider',
    name: 'width',
    type: 'double?',
    doc: 'Width of the rail.',
    defaultDescription: '240',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSider',
    name: 'selectedColor',
    type: 'Color?',
    doc: 'Label/icon color of the selected item.',
    defaultDescription: 'ColorRef.primary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSider',
    name: 'unselectedColor',
    type: 'Color?',
    doc: 'Label/icon color of unselected items.',
    defaultDescription: 'ColorRef.foreground2',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendSider',
    name: 'itemPadding',
    type: 'EdgeInsetsGeometry?',
    doc: 'Inner padding of each item row.',
    defaultDescription:
        'EdgeInsets.symmetric(horizontal: t.sizes.md, vertical: t.sizes.sm)',
    group: 'component',
  ),
];
