// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_bottom_bar.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendBottomBar`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_bottom_bar.dart.
const List<LegendDocEntry> legendBottomBarDocEntries = [
  LegendDocEntry(
    owner: 'LegendBottomBar',
    name: 'background',
    type: 'Color?',
    doc: '',
    defaultDescription: 't.colors.surface',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendBottomBar',
    name: 'selectedColor',
    type: 'Color?',
    doc: '',
    defaultDescription: 't.colors.primary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendBottomBar',
    name: 'unselectedColor',
    type: 'Color?',
    doc: '',
    defaultDescription: 't.colors.foreground3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendBottomBar',
    name: 'height',
    type: 'double?',
    doc: '',
    defaultDescription: '64',
    group: 'component',
  ),
];
