// GENERATED by legend_gen v0.1.0-dev.0 — do not edit.
// Source: legend_bottom_bar.dart
// ignore_for_file: type=lint, unused_import

import 'legend_bottom_bar.dart';
import 'package:flutter/widgets.dart';
import 'package:legend_ui/legend_ui.dart';
import 'package:legend_ui/src/annotations/annotations.dart';
import 'package:legend_ui/src/primitives/legend_interactive.dart';
import 'package:legend_ui/src/primitives/legend_surface.dart';
import 'package:legend_ui/src/shell/legend_nav_item.dart';
import 'package:legend_ui/src/theme/legend_theme.dart';

/// Resolved theme for [LegendBottomBar].
class LegendBottomBarTheme {
  const LegendBottomBarTheme({
    required this.background,
    required this.selectedColor,
    required this.unselectedColor,
    required this.height,
  });

  /// Token-derived defaults (level 5).
  factory LegendBottomBarTheme.defaults(LegendTokens t) => LegendBottomBarTheme(
    background: t.colors.surface,
    selectedColor: t.colors.primary,
    unselectedColor: t.colors.foreground3,
    height: 64.0,
  );

  final Color background;
  final Color selectedColor;
  final Color unselectedColor;
  final double height;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static LegendBottomBarTheme of(
    BuildContext context, [
    LegendBottomBarThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    return LegendBottomBarTheme.defaults(data.tokens)
        .merge(data.component<LegendBottomBarThemeNullable>())
        .merge(
          LegendThemeOverride.maybeOf<LegendBottomBarThemeNullable>(context),
        )
        .merge(local);
  }

  LegendBottomBarTheme merge(LegendBottomBarThemeNullable? other) {
    if (other == null) return this;
    return LegendBottomBarTheme(
      background: other.background ?? background,
      selectedColor: other.selectedColor ?? selectedColor,
      unselectedColor: other.unselectedColor ?? unselectedColor,
      height: other.height ?? height,
    );
  }

  LegendBottomBarTheme copyWith({
    Color? background,
    Color? selectedColor,
    Color? unselectedColor,
    double? height,
  }) => LegendBottomBarTheme(
    background: background ?? this.background,
    selectedColor: selectedColor ?? this.selectedColor,
    unselectedColor: unselectedColor ?? this.unselectedColor,
    height: height ?? this.height,
  );

  static LegendBottomBarTheme lerp(
    LegendBottomBarTheme a,
    LegendBottomBarTheme b,
    double t,
  ) => LegendBottomBarTheme(
    background: t < 0.5 ? a.background : b.background,
    selectedColor: Color.lerp(a.selectedColor, b.selectedColor, t)!,
    unselectedColor: Color.lerp(a.unselectedColor, b.unselectedColor, t)!,
    height: t < 0.5 ? a.height : b.height,
  );
}

/// Sparse overrides for [LegendBottomBarTheme]; null means "inherit".
class LegendBottomBarThemeNullable {
  const LegendBottomBarThemeNullable({
    this.background,
    this.selectedColor,
    this.unselectedColor,
    this.height,
  });

  final Color? background;
  final Color? selectedColor;
  final Color? unselectedColor;
  final double? height;

  LegendBottomBarThemeNullable merge(LegendBottomBarThemeNullable? other) {
    if (other == null) return this;
    return LegendBottomBarThemeNullable(
      background: other.background ?? background,
      selectedColor: other.selectedColor ?? selectedColor,
      unselectedColor: other.unselectedColor ?? unselectedColor,
      height: other.height ?? height,
    );
  }
}

/// Overrides [LegendBottomBarTheme] for a subtree (level 2).
class LegendBottomBarThemeOverride extends StatelessWidget {
  const LegendBottomBarThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendBottomBarThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendBottomBarThemeNullable>(
        data: data,
        child: child,
      );
}
