// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_app_bar.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendAppBar`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_app_bar.dart.
const List<LegendDocEntry> legendAppBarDocEntries = [
  LegendDocEntry(
    owner: 'LegendAppBar',
    name: 'background',
    type: 'Color?',
    doc: 'Fill color of the bar.',
    defaultDescription: 't.colors.surface',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAppBar',
    name: 'height',
    type: 'double?',
    doc: 'Height of the bar content (excluding any safe-area inset).',
    defaultDescription: '56',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAppBar',
    name: 'padding',
    type: 'EdgeInsetsGeometry?',
    doc: 'Horizontal padding around the bar content.',
    defaultDescription: 'EdgeInsets.symmetric(horizontal: t.sizes.md)',
    group: 'component',
  ),
];
