// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_sider.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_sider.dart';

/// Resolved theme for [LegendSider].
class LegendSiderTheme {
  const LegendSiderTheme({
    required this.background,
    required this.width,
    required this.selectedColor,
    required this.unselectedColor,
    required this.itemPadding,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendSiderTheme.defaults(LegendTokens t) => LegendSiderTheme(
    background: _background(t),
    width: 240,
    selectedColor: LegendColorsRef.primary(t),
    unselectedColor: LegendColorsRef.foreground2(t),
    itemPadding: _itemPadding(t),
  );

  final LegendStates<Color> background;
  final double width;
  final Color selectedColor;
  final Color unselectedColor;
  final EdgeInsetsGeometry itemPadding;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendSider] first, [LegendSiderThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Post-merge, unset `LegendStates<Color>` members fill
  /// from the resolved `normal` via `tokens.states`
  /// (RFC-002 R6) — named members at any level always win.
  static LegendSiderTheme of(
    BuildContext context, [
    LegendSiderThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    final resolved = LegendSiderTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendSiderThemeNullable>(LegendSider))
        .merge(LegendThemeOverride.maybeOf<LegendSiderThemeNullable>(context))
        .merge(local);
    return resolved.copyWith(
      background: resolved.background.withDerived(data.tokens.states),
    );
  }

  LegendSiderTheme merge(LegendSiderThemeNullable? other) {
    if (other == null) return this;
    return LegendSiderTheme(
      background:
          LegendStates.merge(background, other.background) ?? background,
      width: other.width ?? width,
      selectedColor: other.selectedColor ?? selectedColor,
      unselectedColor: other.unselectedColor ?? unselectedColor,
      itemPadding: other.itemPadding ?? itemPadding,
    );
  }

  LegendSiderTheme copyWith({
    LegendStates<Color>? background,
    double? width,
    Color? selectedColor,
    Color? unselectedColor,
    EdgeInsetsGeometry? itemPadding,
  }) => LegendSiderTheme(
    background: background ?? this.background,
    width: width ?? this.width,
    selectedColor: selectedColor ?? this.selectedColor,
    unselectedColor: unselectedColor ?? this.unselectedColor,
    itemPadding: itemPadding ?? this.itemPadding,
  );

  static LegendSiderTheme lerp(
    LegendSiderTheme a,
    LegendSiderTheme b,
    double t,
  ) => LegendSiderTheme(
    background: t < 0.5 ? a.background : b.background,
    width: t < 0.5 ? a.width : b.width,
    selectedColor: Color.lerp(a.selectedColor, b.selectedColor, t)!,
    unselectedColor: Color.lerp(a.unselectedColor, b.unselectedColor, t)!,
    itemPadding: t < 0.5 ? a.itemPadding : b.itemPadding,
  );
}

/// Sparse overrides for [LegendSiderTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendSiderThemeNullable {
  const LegendSiderThemeNullable({
    this.background,
    this.width,
    this.selectedColor,
    this.unselectedColor,
    this.itemPadding,
  });

  final LegendStates<Color>? background;
  final double? width;
  final Color? selectedColor;
  final Color? unselectedColor;
  final EdgeInsetsGeometry? itemPadding;

  LegendSiderThemeNullable merge(LegendSiderThemeNullable? other) {
    if (other == null) return this;
    return LegendSiderThemeNullable(
      background: LegendStates.merge(background, other.background),
      width: other.width ?? width,
      selectedColor: other.selectedColor ?? selectedColor,
      unselectedColor: other.unselectedColor ?? unselectedColor,
      itemPadding: other.itemPadding ?? itemPadding,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendSiderThemeNullable &&
          other.background == background &&
          other.width == width &&
          other.selectedColor == selectedColor &&
          other.unselectedColor == unselectedColor &&
          other.itemPadding == itemPadding;

  @override
  int get hashCode => Object.hashAll([
    background,
    width,
    selectedColor,
    unselectedColor,
    itemPadding,
  ]);
}

/// Overrides [LegendSiderTheme] for a subtree (level 2).
class LegendSiderThemeOverride extends StatelessWidget {
  const LegendSiderThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendSiderThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendSiderThemeNullable>(data: data, child: child);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendSiderThemeResolve on LegendSider {
  /// [LegendSiderTheme.of] with this widget's constructor params as
  /// level 1.
  LegendSiderTheme _theme(BuildContext context) => LegendSiderTheme.of(
    context,
    LegendSiderThemeNullable(
      background: background,
      width: width,
      selectedColor: selectedColor,
      unselectedColor: unselectedColor,
      itemPadding: itemPadding,
    ),
  );
}
