// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_scaffold.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_scaffold.dart';

/// Resolved theme for [LegendScaffold].
class LegendScaffoldTheme {
  const LegendScaffoldTheme({required this.background});

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendScaffoldTheme.defaults(LegendTokens t) =>
      LegendScaffoldTheme(background: ColorRef.background1(t));

  final Color background;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendScaffold] first, [LegendScaffoldThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  static LegendScaffoldTheme of(
    BuildContext context, [
    LegendScaffoldThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    return LegendScaffoldTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendScaffoldThemeNullable>(LegendScaffold))
        .merge(
          LegendThemeOverride.maybeOf<LegendScaffoldThemeNullable>(context),
        )
        .merge(local);
  }

  LegendScaffoldTheme merge(LegendScaffoldThemeNullable? other) {
    if (other == null) return this;
    return LegendScaffoldTheme(background: other.background ?? background);
  }

  LegendScaffoldTheme copyWith({Color? background}) =>
      LegendScaffoldTheme(background: background ?? this.background);

  static LegendScaffoldTheme lerp(
    LegendScaffoldTheme a,
    LegendScaffoldTheme b,
    double t,
  ) => LegendScaffoldTheme(
    background: Color.lerp(a.background, b.background, t)!,
  );
}

/// Sparse overrides for [LegendScaffoldTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendScaffoldThemeNullable {
  const LegendScaffoldThemeNullable({this.background});

  final Color? background;

  LegendScaffoldThemeNullable merge(LegendScaffoldThemeNullable? other) {
    if (other == null) return this;
    return LegendScaffoldThemeNullable(
      background: other.background ?? background,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendScaffoldThemeNullable && other.background == background;

  @override
  int get hashCode => Object.hashAll([background]);
}

/// Overrides [LegendScaffoldTheme] for a subtree (level 2).
class LegendScaffoldThemeOverride extends StatelessWidget {
  const LegendScaffoldThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendScaffoldThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendScaffoldThemeNullable>(
        data: data,
        child: child,
      );
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendScaffoldThemeResolve on LegendScaffold {
  /// [LegendScaffoldTheme.of] with this widget's constructor params as
  /// level 1.
  LegendScaffoldTheme _theme(BuildContext context) => LegendScaffoldTheme.of(
    context,
    LegendScaffoldThemeNullable(background: background),
  );
}
