// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_scaffold.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendScaffold`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_scaffold.dart.
const List<LegendDocEntry> legendScaffoldDocEntries = [
  LegendDocEntry(
    owner: 'LegendScaffold',
    name: 'background',
    type: 'Color?',
    doc: 'Fill color behind the page body.',
    defaultDescription: 't.colors.background1',
    group: 'component',
  ),
];
