// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_bottom_bar.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_bottom_bar.dart';

/// Resolved theme for [LegendBottomBar].
class LegendBottomBarTheme {
  const LegendBottomBarTheme({
    required this.background,
    required this.selectedColor,
    required this.unselectedColor,
    required this.height,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendBottomBarTheme.defaults(LegendTokens t) => LegendBottomBarTheme(
    background: LegendColorsRef.surface(t),
    selectedColor: LegendColorsRef.primary(t),
    unselectedColor: LegendColorsRef.foreground3(t),
    height: 64,
  );

  final Color background;
  final Color selectedColor;
  final Color unselectedColor;
  final double height;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendBottomBar] first, [LegendBottomBarThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  static LegendBottomBarTheme of(
    BuildContext context, [
    LegendBottomBarThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    final resolved = LegendBottomBarTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendBottomBarThemeNullable>(LegendBottomBar))
        .merge(
          LegendThemeOverride.maybeOf<LegendBottomBarThemeNullable>(context),
        )
        .merge(local);
    return resolved;
  }

  LegendBottomBarTheme merge(LegendBottomBarThemeNullable? other) {
    if (other == null) return this;
    return LegendBottomBarTheme(
      background: other.background ?? background,
      selectedColor: other.selectedColor ?? selectedColor,
      unselectedColor: other.unselectedColor ?? unselectedColor,
      height: other.height ?? height,
    );
  }

  LegendBottomBarTheme copyWith({
    Color? background,
    Color? selectedColor,
    Color? unselectedColor,
    double? height,
  }) => LegendBottomBarTheme(
    background: background ?? this.background,
    selectedColor: selectedColor ?? this.selectedColor,
    unselectedColor: unselectedColor ?? this.unselectedColor,
    height: height ?? this.height,
  );

  static LegendBottomBarTheme lerp(
    LegendBottomBarTheme a,
    LegendBottomBarTheme b,
    double t,
  ) => LegendBottomBarTheme(
    background: t < 0.5 ? a.background : b.background,
    selectedColor: Color.lerp(a.selectedColor, b.selectedColor, t)!,
    unselectedColor: Color.lerp(a.unselectedColor, b.unselectedColor, t)!,
    height: t < 0.5 ? a.height : b.height,
  );
}

/// Sparse overrides for [LegendBottomBarTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendBottomBarThemeNullable {
  const LegendBottomBarThemeNullable({
    this.background,
    this.selectedColor,
    this.unselectedColor,
    this.height,
  });

  final Color? background;
  final Color? selectedColor;
  final Color? unselectedColor;
  final double? height;

  LegendBottomBarThemeNullable merge(LegendBottomBarThemeNullable? other) {
    if (other == null) return this;
    return LegendBottomBarThemeNullable(
      background: other.background ?? background,
      selectedColor: other.selectedColor ?? selectedColor,
      unselectedColor: other.unselectedColor ?? unselectedColor,
      height: other.height ?? height,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendBottomBarThemeNullable &&
          other.background == background &&
          other.selectedColor == selectedColor &&
          other.unselectedColor == unselectedColor &&
          other.height == height;

  @override
  int get hashCode =>
      Object.hashAll([background, selectedColor, unselectedColor, height]);
}

/// Overrides [LegendBottomBarTheme] for a subtree (level 2).
class LegendBottomBarThemeOverride extends StatelessWidget {
  const LegendBottomBarThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendBottomBarThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendBottomBarThemeNullable>(
        data: data,
        child: child,
      );
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendBottomBarThemeResolve on LegendBottomBar {
  /// [LegendBottomBarTheme.of] with this widget's constructor params as
  /// level 1.
  LegendBottomBarTheme _theme(BuildContext context) => LegendBottomBarTheme.of(
    context,
    LegendBottomBarThemeNullable(
      background: background,
      selectedColor: selectedColor,
      unselectedColor: unselectedColor,
      height: height,
    ),
  );
}
