// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_accordion.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendAccordion`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_accordion.dart.
const List<LegendDocEntry> legendAccordionDocEntries = [
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'headerPadding',
    type: 'EdgeInsetsGeometry?',
    doc: 'Inner padding of every section\'s header row.',
    defaultDescription: 'EdgeInsets.all(t.sizes.md)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'headerStyle',
    type: 'TextStyle?',
    doc: 'Style of every section\'s [LegendAccordionItem.title] text.',
    defaultDescription: 't.typography.b2.copyWith(color: t.colors.foreground1)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'background',
    type: 'InteractiveColors?',
    doc:
        'Fill of the sections, per interaction state — `normal` paints the\nwhole group, `hovered`/`pressed`/`focused` tint the header under the\npointer.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'background.normal',
    type: 'Color?',
    doc: 'Fill at rest (and the base unset members fall back to).',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'background.hovered',
    type: 'Color?',
    doc: 'Fill while a pointer hovers the widget.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'background.pressed',
    type: 'Color?',
    doc: 'Fill while the widget is actively pressed.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'background.focused',
    type: 'Color?',
    doc: 'Fill while the widget holds keyboard focus.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'background.disabled',
    type: 'Color?',
    doc: 'Fill while the widget is disabled.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'dividerColor',
    type: 'Color?',
    doc: 'Color of the rules between consecutive sections.',
    defaultDescription: 'ColorRef.background3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'caretColor',
    type: 'Color?',
    doc: 'Color of the rotating caret in every section header.',
    defaultDescription: 'ColorRef.foreground2',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'duration',
    type: 'Duration?',
    doc:
        'How long each section\'s expand/collapse (and caret) animation takes.',
    defaultDescription: 'Duration(milliseconds: 200)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendAccordion',
    name: 'borderRadius',
    type: 'BorderRadius?',
    doc: 'Corner rounding of the group\'s outer surface.',
    defaultDescription: 't.sizes.borderRadiusMd',
    group: 'component',
  ),
];
