// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_accordion.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_accordion.dart';

/// Resolved theme for [LegendAccordion].
class LegendAccordionTheme {
  const LegendAccordionTheme({
    required this.headerPadding,
    required this.headerStyle,
    required this.background,
    required this.dividerColor,
    required this.caretColor,
    required this.duration,
    required this.borderRadius,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendAccordionTheme.defaults(LegendTokens t) => LegendAccordionTheme(
    headerPadding: _headerPadding(t),
    headerStyle: _headerStyle(t),
    background: _background(t),
    dividerColor: ColorRef.background3(t),
    caretColor: ColorRef.foreground2(t),
    duration: Duration(milliseconds: 200),
    borderRadius: _borderRadius(t),
  );

  final EdgeInsetsGeometry headerPadding;
  final TextStyle headerStyle;
  final InteractiveColors background;
  final Color dividerColor;
  final Color caretColor;
  final Duration duration;
  final BorderRadius borderRadius;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendAccordion] first, [LegendAccordionThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static LegendAccordionTheme of(
    BuildContext context, [
    LegendAccordionThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendAccordionThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectHeaderPadding);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectHeaderPadding,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectHeaderStyle);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectHeaderStyle,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectBackground);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectBackground,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectDividerColor);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectDividerColor,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectCaretColor);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectCaretColor,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectDuration);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectDuration,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectBorderRadius);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectBorderRadius,
    );
    return LegendAccordionTheme.defaults(data.tokens)
        .merge(data.componentOf<LegendAccordionThemeNullable>(LegendAccordion))
        .merge(override)
        .merge(local);
  }

  LegendAccordionTheme merge(LegendAccordionThemeNullable? other) {
    if (other == null) return this;
    return LegendAccordionTheme(
      headerPadding: other.headerPadding ?? headerPadding,
      headerStyle: other.headerStyle ?? headerStyle,
      background: background.merge(other.background),
      dividerColor: other.dividerColor ?? dividerColor,
      caretColor: other.caretColor ?? caretColor,
      duration: other.duration ?? duration,
      borderRadius: other.borderRadius ?? borderRadius,
    );
  }

  LegendAccordionTheme copyWith({
    EdgeInsetsGeometry? headerPadding,
    TextStyle? headerStyle,
    InteractiveColors? background,
    Color? dividerColor,
    Color? caretColor,
    Duration? duration,
    BorderRadius? borderRadius,
  }) => LegendAccordionTheme(
    headerPadding: headerPadding ?? this.headerPadding,
    headerStyle: headerStyle ?? this.headerStyle,
    background: background ?? this.background,
    dividerColor: dividerColor ?? this.dividerColor,
    caretColor: caretColor ?? this.caretColor,
    duration: duration ?? this.duration,
    borderRadius: borderRadius ?? this.borderRadius,
  );

  static LegendAccordionTheme lerp(
    LegendAccordionTheme a,
    LegendAccordionTheme b,
    double t,
  ) => LegendAccordionTheme(
    headerPadding: t < 0.5 ? a.headerPadding : b.headerPadding,
    headerStyle: t < 0.5 ? a.headerStyle : b.headerStyle,
    background: t < 0.5 ? a.background : b.background,
    dividerColor: t < 0.5 ? a.dividerColor : b.dividerColor,
    caretColor: t < 0.5 ? a.caretColor : b.caretColor,
    duration: t < 0.5 ? a.duration : b.duration,
    borderRadius: t < 0.5 ? a.borderRadius : b.borderRadius,
  );
}

/// Sparse overrides for [LegendAccordionTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendAccordionThemeNullable {
  const LegendAccordionThemeNullable({
    this.headerPadding,
    this.headerStyle,
    this.background,
    this.dividerColor,
    this.caretColor,
    this.duration,
    this.borderRadius,
  });

  final EdgeInsetsGeometry? headerPadding;
  final TextStyle? headerStyle;
  final InteractiveColors? background;
  final Color? dividerColor;
  final Color? caretColor;
  final Duration? duration;
  final BorderRadius? borderRadius;

  LegendAccordionThemeNullable merge(LegendAccordionThemeNullable? other) {
    if (other == null) return this;
    return LegendAccordionThemeNullable(
      headerPadding: other.headerPadding ?? headerPadding,
      headerStyle: other.headerStyle ?? headerStyle,
      background: background?.merge(other.background) ?? other.background,
      dividerColor: other.dividerColor ?? dividerColor,
      caretColor: other.caretColor ?? caretColor,
      duration: other.duration ?? duration,
      borderRadius: other.borderRadius ?? borderRadius,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendAccordionThemeNullable &&
          other.headerPadding == headerPadding &&
          other.headerStyle == headerStyle &&
          other.background == background &&
          other.dividerColor == dividerColor &&
          other.caretColor == caretColor &&
          other.duration == duration &&
          other.borderRadius == borderRadius;

  @override
  int get hashCode => Object.hashAll([
    headerPadding,
    headerStyle,
    background,
    dividerColor,
    caretColor,
    duration,
    borderRadius,
  ]);
}

/// Overrides [LegendAccordionTheme] for a subtree (level 2).
class LegendAccordionThemeOverride extends StatelessWidget {
  const LegendAccordionThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendAccordionThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendAccordionThemeNullable>(
        data: data,
        child: child,
      );
}

/// Resolves [LegendAccordion.headerPadding] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
EdgeInsetsGeometry _$LegendAccordionSelectHeaderPadding(LegendThemeData data) =>
    data
        .componentOf<LegendAccordionThemeNullable>(LegendAccordion)
        ?.headerPadding ??
    _headerPadding(data.tokens);
const _$LegendAccordionAspectHeaderPadding = LegendThemeAspect(
  _$LegendAccordionSelectHeaderPadding,
);
Object? _$LegendAccordionOverrideSelectHeaderPadding(
  LegendAccordionThemeNullable data,
) => data.headerPadding;
const _$LegendAccordionOverrideAspectHeaderPadding =
    LegendOverrideAspect<LegendAccordionThemeNullable>(
      _$LegendAccordionOverrideSelectHeaderPadding,
    );

/// Resolves [LegendAccordion.headerStyle] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
TextStyle _$LegendAccordionSelectHeaderStyle(LegendThemeData data) =>
    data
        .componentOf<LegendAccordionThemeNullable>(LegendAccordion)
        ?.headerStyle ??
    _headerStyle(data.tokens);
const _$LegendAccordionAspectHeaderStyle = LegendThemeAspect(
  _$LegendAccordionSelectHeaderStyle,
);
Object? _$LegendAccordionOverrideSelectHeaderStyle(
  LegendAccordionThemeNullable data,
) => data.headerStyle;
const _$LegendAccordionOverrideAspectHeaderStyle =
    LegendOverrideAspect<LegendAccordionThemeNullable>(
      _$LegendAccordionOverrideSelectHeaderStyle,
    );

/// Resolves [LegendAccordion.background] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
InteractiveColors _$LegendAccordionSelectBackground(LegendThemeData data) =>
    _background(data.tokens).merge(
      data
          .componentOf<LegendAccordionThemeNullable>(LegendAccordion)
          ?.background,
    );
const _$LegendAccordionAspectBackground = LegendThemeAspect(
  _$LegendAccordionSelectBackground,
);
Object? _$LegendAccordionOverrideSelectBackground(
  LegendAccordionThemeNullable data,
) => data.background;
const _$LegendAccordionOverrideAspectBackground =
    LegendOverrideAspect<LegendAccordionThemeNullable>(
      _$LegendAccordionOverrideSelectBackground,
    );

/// Resolves [LegendAccordion.dividerColor] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendAccordionSelectDividerColor(LegendThemeData data) =>
    data
        .componentOf<LegendAccordionThemeNullable>(LegendAccordion)
        ?.dividerColor ??
    ColorRef.background3(data.tokens);
const _$LegendAccordionAspectDividerColor = LegendThemeAspect(
  _$LegendAccordionSelectDividerColor,
);
Object? _$LegendAccordionOverrideSelectDividerColor(
  LegendAccordionThemeNullable data,
) => data.dividerColor;
const _$LegendAccordionOverrideAspectDividerColor =
    LegendOverrideAspect<LegendAccordionThemeNullable>(
      _$LegendAccordionOverrideSelectDividerColor,
    );

/// Resolves [LegendAccordion.caretColor] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendAccordionSelectCaretColor(LegendThemeData data) =>
    data
        .componentOf<LegendAccordionThemeNullable>(LegendAccordion)
        ?.caretColor ??
    ColorRef.foreground2(data.tokens);
const _$LegendAccordionAspectCaretColor = LegendThemeAspect(
  _$LegendAccordionSelectCaretColor,
);
Object? _$LegendAccordionOverrideSelectCaretColor(
  LegendAccordionThemeNullable data,
) => data.caretColor;
const _$LegendAccordionOverrideAspectCaretColor =
    LegendOverrideAspect<LegendAccordionThemeNullable>(
      _$LegendAccordionOverrideSelectCaretColor,
    );

/// Resolves [LegendAccordion.duration] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Duration _$LegendAccordionSelectDuration(LegendThemeData data) =>
    data.componentOf<LegendAccordionThemeNullable>(LegendAccordion)?.duration ??
    Duration(milliseconds: 200);
const _$LegendAccordionAspectDuration = LegendThemeAspect(
  _$LegendAccordionSelectDuration,
);
Object? _$LegendAccordionOverrideSelectDuration(
  LegendAccordionThemeNullable data,
) => data.duration;
const _$LegendAccordionOverrideAspectDuration =
    LegendOverrideAspect<LegendAccordionThemeNullable>(
      _$LegendAccordionOverrideSelectDuration,
    );

/// Resolves [LegendAccordion.borderRadius] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
BorderRadius _$LegendAccordionSelectBorderRadius(LegendThemeData data) =>
    data
        .componentOf<LegendAccordionThemeNullable>(LegendAccordion)
        ?.borderRadius ??
    _borderRadius(data.tokens);
const _$LegendAccordionAspectBorderRadius = LegendThemeAspect(
  _$LegendAccordionSelectBorderRadius,
);
Object? _$LegendAccordionOverrideSelectBorderRadius(
  LegendAccordionThemeNullable data,
) => data.borderRadius;
const _$LegendAccordionOverrideAspectBorderRadius =
    LegendOverrideAspect<LegendAccordionThemeNullable>(
      _$LegendAccordionOverrideSelectBorderRadius,
    );

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class LegendAccordionThemeListenables {
  /// Change stream of the resolved [LegendAccordionTheme.headerPadding].
  static ValueListenable<EdgeInsetsGeometry> headerPadding(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendAccordionSelectHeaderPadding);

  /// Change stream of the resolved [LegendAccordionTheme.headerStyle].
  static ValueListenable<TextStyle> headerStyle(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendAccordionSelectHeaderStyle);

  /// Change stream of the resolved [LegendAccordionTheme.background].
  static ValueListenable<InteractiveColors> background(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendAccordionSelectBackground);

  /// Change stream of the resolved [LegendAccordionTheme.dividerColor].
  static ValueListenable<Color> dividerColor(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendAccordionSelectDividerColor);

  /// Change stream of the resolved [LegendAccordionTheme.caretColor].
  static ValueListenable<Color> caretColor(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendAccordionSelectCaretColor);

  /// Change stream of the resolved [LegendAccordionTheme.duration].
  static ValueListenable<Duration> duration(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendAccordionSelectDuration);

  /// Change stream of the resolved [LegendAccordionTheme.borderRadius].
  static ValueListenable<BorderRadius> borderRadius(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendAccordionSelectBorderRadius);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendAccordionThemeResolve on LegendAccordion {
  /// [LegendAccordionTheme.of] with this widget's constructor params as
  /// level 1.
  LegendAccordionTheme _theme(BuildContext context) => LegendAccordionTheme.of(
    context,
    LegendAccordionThemeNullable(
      headerPadding: headerPadding,
      headerStyle: headerStyle,
      background: background,
      dividerColor: dividerColor,
      caretColor: caretColor,
      duration: duration,
      borderRadius: borderRadius,
    ),
  );

  /// Resolves ONLY [LegendAccordion.headerPadding] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._headerPadding(context)`).
  EdgeInsetsGeometry _headerPadding(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendAccordionThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectHeaderPadding);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectHeaderPadding,
    );
    return headerPadding ??
        override?.headerPadding ??
        _$LegendAccordionSelectHeaderPadding(data);
  }

  /// Resolves ONLY [LegendAccordion.headerStyle] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._headerStyle(context)`).
  TextStyle _headerStyle(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendAccordionThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectHeaderStyle);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectHeaderStyle,
    );
    return headerStyle ??
        override?.headerStyle ??
        _$LegendAccordionSelectHeaderStyle(data);
  }

  /// Resolves ONLY [LegendAccordion.background] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._background(context)`).
  InteractiveColors _background(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendAccordionThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectBackground);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectBackground,
    );
    return _$LegendAccordionSelectBackground(
      data,
    ).merge(override?.background).merge(background);
  }

  /// Resolves ONLY [LegendAccordion.dividerColor] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._dividerColor(context)`).
  Color _dividerColor(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendAccordionThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectDividerColor);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectDividerColor,
    );
    return dividerColor ??
        override?.dividerColor ??
        _$LegendAccordionSelectDividerColor(data);
  }

  /// Resolves ONLY [LegendAccordion.caretColor] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._caretColor(context)`).
  Color _caretColor(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendAccordionThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectCaretColor);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectCaretColor,
    );
    return caretColor ??
        override?.caretColor ??
        _$LegendAccordionSelectCaretColor(data);
  }

  /// Resolves ONLY [LegendAccordion.duration] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._duration(context)`).
  Duration _duration(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendAccordionThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectDuration);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectDuration,
    );
    return duration ??
        override?.duration ??
        _$LegendAccordionSelectDuration(data);
  }

  /// Resolves ONLY [LegendAccordion.borderRadius] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._borderRadius(context)`).
  BorderRadius _borderRadius(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendAccordionThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendAccordionAspectBorderRadius);
    LegendThemeOverride.depend<LegendAccordionThemeNullable>(
      context,
      _$LegendAccordionOverrideAspectBorderRadius,
    );
    return borderRadius ??
        override?.borderRadius ??
        _$LegendAccordionSelectBorderRadius(data);
  }
}

/// Auto-detected State wiring (RFC-002 R13): [_LegendAccordionState]
/// is this file's `State<LegendAccordion>`, so its
/// build reads the resolved theme as a plain `theme`
/// getter — zero visible wiring. A same-named instance
/// member (e.g. from [_$LegendAccordionThemeState])
/// wins over this extension.
extension _$LegendAccordionThemeOn_LegendAccordionState
    on _LegendAccordionState {
  LegendAccordionTheme get theme => widget._theme(context);
}

/// Explicit State wiring (RFC-002 R13): mix onto any
/// `State<LegendAccordion>` for the `theme` getter as a
/// real, overridable inherited member — no State-class
/// detection involved.
mixin _$LegendAccordionThemeState on State<LegendAccordion> {
  LegendAccordionTheme get theme => widget._theme(context);
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class LegendAccordion extends
/// _$LegendAccordionBase` receives the resolved
/// [LegendAccordionTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$LegendAccordionBase
    extends LegendStatelessWidget<LegendAccordionTheme> {
  const _$LegendAccordionBase({super.key});

  EdgeInsetsGeometry? get headerPadding;
  TextStyle? get headerStyle;
  InteractiveColors? get background;
  Color? get dividerColor;
  Color? get caretColor;
  Duration? get duration;
  BorderRadius? get borderRadius;

  @override
  LegendAccordionTheme resolveThemeOf(BuildContext context) =>
      LegendAccordionTheme.of(
        context,
        LegendAccordionThemeNullable(
          headerPadding: headerPadding,
          headerStyle: headerStyle,
          background: background,
          dividerColor: dividerColor,
          caretColor: caretColor,
          duration: duration,
          borderRadius: borderRadius,
        ),
      );
}
