// GENERATED by nomo_gen v0.1.0-dev.0 — do not edit.
// Source: nomo_dialog.dart
// ignore_for_file: type=lint

import 'package:flutter/widgets.dart';
import 'package:nomo_ui_kit/nomo_ui_kit.dart';
import 'package:nomo_ui_kit/src/annotations/annotations.dart';
import 'package:nomo_ui_kit/src/primitives/nomo_modal.dart';
import 'package:nomo_ui_kit/src/primitives/nomo_surface.dart';
import 'package:nomo_ui_kit/src/theme/nomo_theme.dart';

/// Resolved theme for [NomoDialog].
class NomoDialogTheme {
  const NomoDialogTheme({
    required this.background,
    required this.borderRadius,
    required this.padding,
    required this.maxWidth,
  });

  /// Token-derived defaults (level 5).
  factory NomoDialogTheme.defaults(NomoTokens t) => NomoDialogTheme(
    background: t.colors.surface,
    borderRadius: t.sizes.borderRadiusLg,
    padding: EdgeInsets.all(t.sizes.lg),
    maxWidth: 420.0,
  );

  final Color background;
  final BorderRadius borderRadius;
  final EdgeInsetsGeometry padding;
  final double maxWidth;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static NomoDialogTheme of(
    BuildContext context, [
    NomoDialogThemeNullable? local,
  ]) {
    final data = NomoTheme.of(context);
    return NomoDialogTheme.defaults(data.tokens)
        .merge(data.component<NomoDialogThemeNullable>())
        .merge(NomoThemeOverride.maybeOf<NomoDialogThemeNullable>(context))
        .merge(local);
  }

  NomoDialogTheme merge(NomoDialogThemeNullable? other) {
    if (other == null) return this;
    return NomoDialogTheme(
      background: other.background ?? background,
      borderRadius: other.borderRadius ?? borderRadius,
      padding: other.padding ?? padding,
      maxWidth: other.maxWidth ?? maxWidth,
    );
  }

  NomoDialogTheme copyWith({
    Color? background,
    BorderRadius? borderRadius,
    EdgeInsetsGeometry? padding,
    double? maxWidth,
  }) => NomoDialogTheme(
    background: background ?? this.background,
    borderRadius: borderRadius ?? this.borderRadius,
    padding: padding ?? this.padding,
    maxWidth: maxWidth ?? this.maxWidth,
  );

  static NomoDialogTheme lerp(NomoDialogTheme a, NomoDialogTheme b, double t) =>
      NomoDialogTheme(
        background: t < 0.5 ? a.background : b.background,
        borderRadius: t < 0.5 ? a.borderRadius : b.borderRadius,
        padding: t < 0.5 ? a.padding : b.padding,
        maxWidth: t < 0.5 ? a.maxWidth : b.maxWidth,
      );
}

/// Sparse overrides for [NomoDialogTheme]; null means "inherit".
class NomoDialogThemeNullable {
  const NomoDialogThemeNullable({
    this.background,
    this.borderRadius,
    this.padding,
    this.maxWidth,
  });

  final Color? background;
  final BorderRadius? borderRadius;
  final EdgeInsetsGeometry? padding;
  final double? maxWidth;

  NomoDialogThemeNullable merge(NomoDialogThemeNullable? other) {
    if (other == null) return this;
    return NomoDialogThemeNullable(
      background: other.background ?? background,
      borderRadius: other.borderRadius ?? borderRadius,
      padding: other.padding ?? padding,
      maxWidth: other.maxWidth ?? maxWidth,
    );
  }
}

/// Overrides [NomoDialogTheme] for a subtree (level 2).
class NomoDialogThemeOverride extends StatelessWidget {
  const NomoDialogThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final NomoDialogThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      NomoThemeOverride<NomoDialogThemeNullable>(data: data, child: child);
}
