// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: secondary_legend_button.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `SecondaryLegendButton`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in secondary_legend_button.dart.
const List<LegendDocEntry> secondaryLegendButtonDocEntries = [
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'background',
    type: 'InteractiveColors?',
    doc:
        'Tinted fill behind the label, per interaction state — hover/press\nblend the foreground over the container tint (8%/16%), disabled\nswaps to the token disabled fill.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primaryContainer, hovered: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), pressed: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.16), t.colors.primaryContainer), focused: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'background.normal',
    type: 'Color?',
    doc: 'Fill at rest (and the base unset members fall back to).',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primaryContainer, hovered: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), pressed: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.16), t.colors.primaryContainer), focused: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'background.hovered',
    type: 'Color?',
    doc: 'Fill while a pointer hovers the widget.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primaryContainer, hovered: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), pressed: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.16), t.colors.primaryContainer), focused: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'background.pressed',
    type: 'Color?',
    doc: 'Fill while the widget is actively pressed.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primaryContainer, hovered: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), pressed: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.16), t.colors.primaryContainer), focused: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'background.focused',
    type: 'Color?',
    doc: 'Fill while the widget holds keyboard focus.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primaryContainer, hovered: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), pressed: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.16), t.colors.primaryContainer), focused: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'background.disabled',
    type: 'Color?',
    doc: 'Fill while the widget is disabled.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primaryContainer, hovered: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), pressed: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.16), t.colors.primaryContainer), focused: Color.alphaBlend(t.colors.primary.withValues(alpha: 0.08), t.colors.primaryContainer), disabled: t.colors.disabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'foreground',
    type: 'InteractiveColors?',
    doc:
        'Color of the label and icon, per interaction state (steady except\nwhile disabled).',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: t.colors.primary, pressed: t.colors.primary, focused: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'foreground.normal',
    type: 'Color?',
    doc: 'Fill at rest (and the base unset members fall back to).',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: t.colors.primary, pressed: t.colors.primary, focused: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'foreground.hovered',
    type: 'Color?',
    doc: 'Fill while a pointer hovers the widget.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: t.colors.primary, pressed: t.colors.primary, focused: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'foreground.pressed',
    type: 'Color?',
    doc: 'Fill while the widget is actively pressed.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: t.colors.primary, pressed: t.colors.primary, focused: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'foreground.focused',
    type: 'Color?',
    doc: 'Fill while the widget holds keyboard focus.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: t.colors.primary, pressed: t.colors.primary, focused: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'foreground.disabled',
    type: 'Color?',
    doc: 'Fill while the widget is disabled.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.primary, hovered: t.colors.primary, pressed: t.colors.primary, focused: t.colors.primary, disabled: t.colors.onDisabled)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'borderColor',
    type: 'Color?',
    doc: 'Color of the outline (dropped entirely while disabled).',
    defaultDescription: 'ColorRef.primary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'SecondaryLegendButton',
    name: 'textStyle',
    type: 'TextStyle?',
    doc: 'Text style of the [text] label (its color comes from [foreground]).',
    defaultDescription: 'TextRef.b2',
    group: 'component',
  ),
];
