// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: secondary_legend_button.dart
// ignore_for_file: type=lint, unused_element
part of 'secondary_legend_button.dart';

/// Resolved theme for [SecondaryLegendButton].
class SecondaryLegendButtonTheme {
  const SecondaryLegendButtonTheme({
    required this.background,
    required this.foreground,
    required this.borderColor,
    required this.padding,
    required this.borderRadius,
    required this.textStyle,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory SecondaryLegendButtonTheme.defaults(LegendTokens t) =>
      SecondaryLegendButtonTheme(
        background: SecondaryLegendButton._background(t),
        foreground: SecondaryLegendButton._foreground(t),
        borderColor: SecondaryLegendButton._borderColor(t),
        padding: SecondaryLegendButton._padding(t),
        borderRadius: SecondaryLegendButton._borderRadius(t),
        textStyle: SecondaryLegendButton._textStyle(t),
      );

  final Color background;
  final Color foreground;
  final Color borderColor;
  final EdgeInsetsGeometry padding;
  final BorderRadius borderRadius;
  final TextStyle textStyle;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [SecondaryLegendButton] first, [SecondaryLegendButtonThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  static SecondaryLegendButtonTheme of(
    BuildContext context, [
    SecondaryLegendButtonThemeNullable? local,
  ]) {
    final data = LegendTheme.of(context);
    final resolved = SecondaryLegendButtonTheme.defaults(data.tokens)
        .merge(
          data.componentOf<SecondaryLegendButtonThemeNullable>(
            SecondaryLegendButton,
          ),
        )
        .merge(
          LegendThemeOverride.maybeOf<SecondaryLegendButtonThemeNullable>(
            context,
          ),
        )
        .merge(local);
    return resolved;
  }

  SecondaryLegendButtonTheme merge(SecondaryLegendButtonThemeNullable? other) {
    if (other == null) return this;
    return SecondaryLegendButtonTheme(
      background: other.background ?? background,
      foreground: other.foreground ?? foreground,
      borderColor: other.borderColor ?? borderColor,
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
      textStyle: other.textStyle ?? textStyle,
    );
  }

  SecondaryLegendButtonTheme copyWith({
    Color? background,
    Color? foreground,
    Color? borderColor,
    EdgeInsetsGeometry? padding,
    BorderRadius? borderRadius,
    TextStyle? textStyle,
  }) => SecondaryLegendButtonTheme(
    background: background ?? this.background,
    foreground: foreground ?? this.foreground,
    borderColor: borderColor ?? this.borderColor,
    padding: padding ?? this.padding,
    borderRadius: borderRadius ?? this.borderRadius,
    textStyle: textStyle ?? this.textStyle,
  );

  static SecondaryLegendButtonTheme lerp(
    SecondaryLegendButtonTheme a,
    SecondaryLegendButtonTheme b,
    double t,
  ) => SecondaryLegendButtonTheme(
    background: Color.lerp(a.background, b.background, t)!,
    foreground: Color.lerp(a.foreground, b.foreground, t)!,
    borderColor: t < 0.5 ? a.borderColor : b.borderColor,
    padding: t < 0.5 ? a.padding : b.padding,
    borderRadius: t < 0.5 ? a.borderRadius : b.borderRadius,
    textStyle: t < 0.5 ? a.textStyle : b.textStyle,
  );
}

/// Sparse overrides for [SecondaryLegendButtonTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class SecondaryLegendButtonThemeNullable {
  const SecondaryLegendButtonThemeNullable({
    this.background,
    this.foreground,
    this.borderColor,
    this.padding,
    this.borderRadius,
    this.textStyle,
  });

  final Color? background;
  final Color? foreground;
  final Color? borderColor;
  final EdgeInsetsGeometry? padding;
  final BorderRadius? borderRadius;
  final TextStyle? textStyle;

  SecondaryLegendButtonThemeNullable merge(
    SecondaryLegendButtonThemeNullable? other,
  ) {
    if (other == null) return this;
    return SecondaryLegendButtonThemeNullable(
      background: other.background ?? background,
      foreground: other.foreground ?? foreground,
      borderColor: other.borderColor ?? borderColor,
      padding: other.padding ?? padding,
      borderRadius: other.borderRadius ?? borderRadius,
      textStyle: other.textStyle ?? textStyle,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecondaryLegendButtonThemeNullable &&
          other.background == background &&
          other.foreground == foreground &&
          other.borderColor == borderColor &&
          other.padding == padding &&
          other.borderRadius == borderRadius &&
          other.textStyle == textStyle;

  @override
  int get hashCode => Object.hashAll([
    background,
    foreground,
    borderColor,
    padding,
    borderRadius,
    textStyle,
  ]);
}

/// Overrides [SecondaryLegendButtonTheme] for a subtree (level 2).
class SecondaryLegendButtonThemeOverride extends StatelessWidget {
  const SecondaryLegendButtonThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final SecondaryLegendButtonThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<SecondaryLegendButtonThemeNullable>(
        data: data,
        child: child,
      );
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$SecondaryLegendButtonThemeResolve on SecondaryLegendButton {
  /// [SecondaryLegendButtonTheme.of] with this widget's constructor params as
  /// level 1.
  SecondaryLegendButtonTheme _theme(BuildContext context) =>
      SecondaryLegendButtonTheme.of(
        context,
        SecondaryLegendButtonThemeNullable(
          background: background,
          foreground: foreground,
          borderColor: borderColor,
          padding: padding,
          borderRadius: borderRadius,
          textStyle: textStyle,
        ),
      );
}
