// GENERATED by nomo_gen v0.1.0-dev.0 — do not edit.
// Source: nomo_scaffold.dart
// ignore_for_file: type=lint, unused_import

import 'nomo_scaffold.dart';
import 'package:flutter/widgets.dart';
import 'package:nomo_ui_kit/nomo_ui_kit.dart';
import 'package:nomo_ui_kit/src/annotations/annotations.dart';
import 'package:nomo_ui_kit/src/theme/nomo_breakpoints.dart';

/// Resolved theme for [NomoScaffold].
class NomoScaffoldTheme {
  const NomoScaffoldTheme({required this.background});

  /// Token-derived defaults (level 5).
  factory NomoScaffoldTheme.defaults(NomoTokens t) =>
      NomoScaffoldTheme(background: t.colors.background1);

  final Color background;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static NomoScaffoldTheme of(
    BuildContext context, [
    NomoScaffoldThemeNullable? local,
  ]) {
    final data = NomoTheme.of(context);
    return NomoScaffoldTheme.defaults(data.tokens)
        .merge(data.component<NomoScaffoldThemeNullable>())
        .merge(NomoThemeOverride.maybeOf<NomoScaffoldThemeNullable>(context))
        .merge(local);
  }

  NomoScaffoldTheme merge(NomoScaffoldThemeNullable? other) {
    if (other == null) return this;
    return NomoScaffoldTheme(background: other.background ?? background);
  }

  NomoScaffoldTheme copyWith({Color? background}) =>
      NomoScaffoldTheme(background: background ?? this.background);

  static NomoScaffoldTheme lerp(
    NomoScaffoldTheme a,
    NomoScaffoldTheme b,
    double t,
  ) =>
      NomoScaffoldTheme(background: Color.lerp(a.background, b.background, t)!);
}

/// Sparse overrides for [NomoScaffoldTheme]; null means "inherit".
class NomoScaffoldThemeNullable {
  const NomoScaffoldThemeNullable({this.background});

  final Color? background;

  NomoScaffoldThemeNullable merge(NomoScaffoldThemeNullable? other) {
    if (other == null) return this;
    return NomoScaffoldThemeNullable(
      background: other.background ?? background,
    );
  }
}

/// Overrides [NomoScaffoldTheme] for a subtree (level 2).
class NomoScaffoldThemeOverride extends StatelessWidget {
  const NomoScaffoldThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final NomoScaffoldThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      NomoThemeOverride<NomoScaffoldThemeNullable>(data: data, child: child);
}
