// GENERATED by nomo_gen v0.1.0-dev.0 — do not edit.
// Source: nomo_bottom_bar.dart
// ignore_for_file: type=lint, unused_import

import 'nomo_bottom_bar.dart';
import 'package:flutter/widgets.dart';
import 'package:nomo_ui_kit/nomo_ui_kit.dart';
import 'package:nomo_ui_kit/src/annotations/annotations.dart';
import 'package:nomo_ui_kit/src/primitives/nomo_interactive.dart';
import 'package:nomo_ui_kit/src/primitives/nomo_surface.dart';
import 'package:nomo_ui_kit/src/shell/nomo_nav_item.dart';
import 'package:nomo_ui_kit/src/theme/nomo_theme.dart';

/// Resolved theme for [NomoBottomBar].
class NomoBottomBarTheme {
  const NomoBottomBarTheme({
    required this.background,
    required this.selectedColor,
    required this.unselectedColor,
    required this.height,
  });

  /// Token-derived defaults (level 5).
  factory NomoBottomBarTheme.defaults(NomoTokens t) => NomoBottomBarTheme(
    background: t.colors.surface,
    selectedColor: t.colors.primary,
    unselectedColor: t.colors.foreground3,
    height: 64.0,
  );

  final Color background;
  final Color selectedColor;
  final Color unselectedColor;
  final double height;

  /// Resolves the theme: defaults <- app theme <- subtree
  /// override <- constructor params ([local]).
  static NomoBottomBarTheme of(
    BuildContext context, [
    NomoBottomBarThemeNullable? local,
  ]) {
    final data = NomoTheme.of(context);
    return NomoBottomBarTheme.defaults(data.tokens)
        .merge(data.component<NomoBottomBarThemeNullable>())
        .merge(NomoThemeOverride.maybeOf<NomoBottomBarThemeNullable>(context))
        .merge(local);
  }

  NomoBottomBarTheme merge(NomoBottomBarThemeNullable? other) {
    if (other == null) return this;
    return NomoBottomBarTheme(
      background: other.background ?? background,
      selectedColor: other.selectedColor ?? selectedColor,
      unselectedColor: other.unselectedColor ?? unselectedColor,
      height: other.height ?? height,
    );
  }

  NomoBottomBarTheme copyWith({
    Color? background,
    Color? selectedColor,
    Color? unselectedColor,
    double? height,
  }) => NomoBottomBarTheme(
    background: background ?? this.background,
    selectedColor: selectedColor ?? this.selectedColor,
    unselectedColor: unselectedColor ?? this.unselectedColor,
    height: height ?? this.height,
  );

  static NomoBottomBarTheme lerp(
    NomoBottomBarTheme a,
    NomoBottomBarTheme b,
    double t,
  ) => NomoBottomBarTheme(
    background: t < 0.5 ? a.background : b.background,
    selectedColor: Color.lerp(a.selectedColor, b.selectedColor, t)!,
    unselectedColor: Color.lerp(a.unselectedColor, b.unselectedColor, t)!,
    height: t < 0.5 ? a.height : b.height,
  );
}

/// Sparse overrides for [NomoBottomBarTheme]; null means "inherit".
class NomoBottomBarThemeNullable {
  const NomoBottomBarThemeNullable({
    this.background,
    this.selectedColor,
    this.unselectedColor,
    this.height,
  });

  final Color? background;
  final Color? selectedColor;
  final Color? unselectedColor;
  final double? height;

  NomoBottomBarThemeNullable merge(NomoBottomBarThemeNullable? other) {
    if (other == null) return this;
    return NomoBottomBarThemeNullable(
      background: other.background ?? background,
      selectedColor: other.selectedColor ?? selectedColor,
      unselectedColor: other.unselectedColor ?? unselectedColor,
      height: other.height ?? height,
    );
  }
}

/// Overrides [NomoBottomBarTheme] for a subtree (level 2).
class NomoBottomBarThemeOverride extends StatelessWidget {
  const NomoBottomBarThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final NomoBottomBarThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      NomoThemeOverride<NomoBottomBarThemeNullable>(data: data, child: child);
}
