// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_expandable.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendExpandable`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_expandable.dart.
const List<LegendDocEntry> legendExpandableDocEntries = [
  LegendDocEntry(
    owner: 'LegendExpandable',
    name: 'headerPadding',
    type: 'EdgeInsetsGeometry?',
    doc: 'Inner padding of the header row.',
    defaultDescription: 'EdgeInsets.all(t.sizes.md)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendExpandable',
    name: 'backgroundColor',
    type: 'InteractiveColors?',
    doc:
        'Fill of the container and its header, per interaction state —\n`normal` paints the whole surface, `hovered`/`pressed`/`focused`\ntint the header while the pointer is on it.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendExpandable',
    name: 'backgroundColor.normal',
    type: 'Color?',
    doc: 'Fill at rest (and the base unset members fall back to).',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendExpandable',
    name: 'backgroundColor.hovered',
    type: 'Color?',
    doc: 'Fill while a pointer hovers the widget.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendExpandable',
    name: 'backgroundColor.pressed',
    type: 'Color?',
    doc: 'Fill while the widget is actively pressed.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendExpandable',
    name: 'backgroundColor.focused',
    type: 'Color?',
    doc: 'Fill while the widget holds keyboard focus.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendExpandable',
    name: 'backgroundColor.disabled',
    type: 'Color?',
    doc: 'Fill while the widget is disabled.',
    defaultDescription:
        'InteractiveColors(normal: t.colors.surface, hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendExpandable',
    name: 'borderRadius',
    type: 'BorderRadius?',
    doc: 'Corner rounding of the container surface.',
    defaultDescription: 't.sizes.borderRadiusMd',
    group: 'component',
  ),
];
