// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_drawer.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendDrawer`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_drawer.dart.
const List<LegendDocEntry> legendDrawerDocEntries = [
  LegendDocEntry(
    owner: 'LegendDrawer',
    name: 'background',
    type: 'Color?',
    doc: 'Fill color of the sheet surface.',
    defaultDescription: 'ColorRef.surface',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDrawer',
    name: 'width',
    type: 'double?',
    doc: 'Fixed width of a side drawer (bottom drawers span the window).',
    defaultDescription: '320',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDrawer',
    name: 'borderRadius',
    type: 'BorderRadius?',
    doc:
        'Corner rounding of a bottom drawer\'s top edge (side drawers stay\nsquare against their edge).',
    defaultDescription:
        'BorderRadius.vertical(top: Radius.circular(t.sizes.radiusLg))',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDrawer',
    name: 'handleColor',
    type: 'Color?',
    doc: 'Color of the bottom drawer\'s drag handle.',
    defaultDescription: 'ColorRef.background3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDrawer',
    name: 'padding',
    type: 'EdgeInsetsGeometry?',
    doc: 'Inner padding around [child].',
    defaultDescription: 'EdgeInsets.all(t.sizes.lg)',
    group: 'component',
  ),
];
