// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_tabs.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendTabs`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_tabs.dart.
const List<LegendDocEntry> legendTabsDocEntries = [
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'background',
    type: 'InteractiveColors?',
    doc:
        'Fill of each tab per interaction state — an unset `normal` keeps\ntabs transparent; `hovered`/`pressed`/`focused` tint the tab under\nthe pointer (and the keyboard focus).',
    defaultDescription:
        'InteractiveColors(hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'background.normal',
    type: 'Color?',
    doc: 'Fill at rest (and the base unset members fall back to).',
    defaultDescription:
        'InteractiveColors(hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'background.hovered',
    type: 'Color?',
    doc: 'Fill while a pointer hovers the widget.',
    defaultDescription:
        'InteractiveColors(hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'background.pressed',
    type: 'Color?',
    doc: 'Fill while the widget is actively pressed.',
    defaultDescription:
        'InteractiveColors(hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'background.focused',
    type: 'Color?',
    doc: 'Fill while the widget holds keyboard focus.',
    defaultDescription:
        'InteractiveColors(hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'background.disabled',
    type: 'Color?',
    doc: 'Fill while the widget is disabled.',
    defaultDescription:
        'InteractiveColors(hovered: t.colors.background2, pressed: t.colors.background2, focused: t.colors.background2)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'indicator',
    type: 'Color?',
    doc: 'Color of the active-tab indicator line.',
    defaultDescription: 'ColorRef.primary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'indicatorThickness',
    type: 'double?',
    doc: 'Stroke height of the active-tab indicator line.',
    defaultDescription: '2',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'selectedColor',
    type: 'Color?',
    doc: 'Label/icon color of the selected tab.',
    defaultDescription: 'ColorRef.primary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'unselectedColor',
    type: 'Color?',
    doc: 'Label/icon color of unselected tabs.',
    defaultDescription: 'ColorRef.foreground2',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendTabs',
    name: 'padding',
    type: 'EdgeInsetsGeometry?',
    doc: 'Inner padding of each tab.',
    defaultDescription:
        'EdgeInsets.symmetric(horizontal: t.sizes.md, vertical: t.sizes.sm)',
    group: 'component',
  ),
];
