// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_dropdown.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendDropdown`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_dropdown.dart.
const List<LegendDocEntry> legendDropdownDocEntries = [
  LegendDocEntry(
    owner: 'LegendDropdown',
    name: 'menuBackground',
    type: 'Color?',
    doc: '',
    defaultDescription: 't.colors.surface',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDropdown',
    name: 'menuBorderRadius',
    type: 'BorderRadius?',
    doc: '',
    defaultDescription: 't.sizes.borderRadiusMd',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDropdown',
    name: 'menuShadows',
    type: 'List<BoxShadow>?',
    doc: '',
    defaultDescription: 't.shadows.medium',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDropdown',
    name: 'menuMaxHeight',
    type: 'double?',
    doc:
        'The menu scrolls past this height instead of overflowing the screen\non long item lists.',
    defaultDescription: '320',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDropdown',
    name: 'itemPadding',
    type: 'EdgeInsetsGeometry?',
    doc: '',
    defaultDescription:
        'EdgeInsets.symmetric(horizontal: t.sizes.md, vertical: t.sizes.sm)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendDropdown',
    name: 'textStyle',
    type: 'TextStyle?',
    doc: '',
    defaultDescription: 't.typography.b2',
    group: 'component',
  ),
];
