// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_copy_button.dart
// ignore_for_file: type=lint, unused_element
part of 'legend_copy_button.dart';

/// Resolved theme for [LegendCopyButton].
class LegendCopyButtonTheme {
  const LegendCopyButtonTheme({
    required this.foreground,
    required this.confirmationColor,
    required this.glyphSize,
  });

  /// Token-derived defaults (level 4) — the annotation
  /// defaults ARE the kit defaults (DESIGN.md §9.9).
  factory LegendCopyButtonTheme.defaults(LegendTokens t) =>
      LegendCopyButtonTheme(
        foreground: _foreground(t),
        confirmationColor: ColorRef.secondary(t),
        glyphSize: SizeRef.iconSm(t),
      );

  final InteractiveColors foreground;
  final Color confirmationColor;
  final double glyphSize;

  /// Resolves the theme: defaults <- app registry (keyed by
  /// [LegendCopyButton] first, [LegendCopyButtonThemeNullable] as the legacy
  /// fallback — RFC-002 R3) <- subtree override <- constructor
  /// params ([local]).
  ///
  /// Registers one rebuild aspect per `listen: true` field
  /// (RFC-002 R12): the caller rebuilds only when a listened
  /// field's resolved value changes; `listen: false` fields
  /// resolve fresh but never cause a rebuild by themselves.
  static LegendCopyButtonTheme of(
    BuildContext context, [
    LegendCopyButtonThemeNullable? local,
  ]) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendCopyButtonThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendCopyButtonAspectForeground);
    LegendThemeOverride.depend<LegendCopyButtonThemeNullable>(
      context,
      _$LegendCopyButtonOverrideAspectForeground,
    );
    LegendTheme.depend(context, _$LegendCopyButtonAspectConfirmationColor);
    LegendThemeOverride.depend<LegendCopyButtonThemeNullable>(
      context,
      _$LegendCopyButtonOverrideAspectConfirmationColor,
    );
    LegendTheme.depend(context, _$LegendCopyButtonAspectGlyphSize);
    LegendThemeOverride.depend<LegendCopyButtonThemeNullable>(
      context,
      _$LegendCopyButtonOverrideAspectGlyphSize,
    );
    return LegendCopyButtonTheme.defaults(data.tokens)
        .merge(
          data.componentOf<LegendCopyButtonThemeNullable>(LegendCopyButton),
        )
        .merge(override)
        .merge(local);
  }

  LegendCopyButtonTheme merge(LegendCopyButtonThemeNullable? other) {
    if (other == null) return this;
    return LegendCopyButtonTheme(
      foreground: foreground.merge(other.foreground),
      confirmationColor: other.confirmationColor ?? confirmationColor,
      glyphSize: other.glyphSize ?? glyphSize,
    );
  }

  LegendCopyButtonTheme copyWith({
    InteractiveColors? foreground,
    Color? confirmationColor,
    double? glyphSize,
  }) => LegendCopyButtonTheme(
    foreground: foreground ?? this.foreground,
    confirmationColor: confirmationColor ?? this.confirmationColor,
    glyphSize: glyphSize ?? this.glyphSize,
  );

  static LegendCopyButtonTheme lerp(
    LegendCopyButtonTheme a,
    LegendCopyButtonTheme b,
    double t,
  ) => LegendCopyButtonTheme(
    foreground: InteractiveColors.lerp(a.foreground, b.foreground, t)!,
    confirmationColor: Color.lerp(a.confirmationColor, b.confirmationColor, t)!,
    glyphSize: t < 0.5 ? a.glyphSize : b.glyphSize,
  );
}

/// Sparse overrides for [LegendCopyButtonTheme]; null means "inherit".
/// Value-compared (RFC-002 R2), so rebuilding an ancestor
/// with an equal override never invalidates dependents.
class LegendCopyButtonThemeNullable {
  const LegendCopyButtonThemeNullable({
    this.foreground,
    this.confirmationColor,
    this.glyphSize,
  });

  final InteractiveColors? foreground;
  final Color? confirmationColor;
  final double? glyphSize;

  LegendCopyButtonThemeNullable merge(LegendCopyButtonThemeNullable? other) {
    if (other == null) return this;
    return LegendCopyButtonThemeNullable(
      foreground: foreground?.merge(other.foreground) ?? other.foreground,
      confirmationColor: other.confirmationColor ?? confirmationColor,
      glyphSize: other.glyphSize ?? glyphSize,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LegendCopyButtonThemeNullable &&
          other.foreground == foreground &&
          other.confirmationColor == confirmationColor &&
          other.glyphSize == glyphSize;

  @override
  int get hashCode =>
      Object.hashAll([foreground, confirmationColor, glyphSize]);
}

/// Overrides [LegendCopyButtonTheme] for a subtree (level 2).
class LegendCopyButtonThemeOverride extends StatelessWidget {
  const LegendCopyButtonThemeOverride({
    required this.data,
    required this.child,
    super.key,
  });

  final LegendCopyButtonThemeNullable data;
  final Widget child;

  @override
  Widget build(BuildContext context) =>
      LegendThemeOverride<LegendCopyButtonThemeNullable>(
        data: data,
        child: child,
      );
}

/// Resolves [LegendCopyButton.foreground] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
InteractiveColors _$LegendCopyButtonSelectForeground(LegendThemeData data) =>
    _foreground(data.tokens).merge(
      data
          .componentOf<LegendCopyButtonThemeNullable>(LegendCopyButton)
          ?.foreground,
    );
const _$LegendCopyButtonAspectForeground = LegendThemeAspect(
  _$LegendCopyButtonSelectForeground,
);
Object? _$LegendCopyButtonOverrideSelectForeground(
  LegendCopyButtonThemeNullable data,
) => data.foreground;
const _$LegendCopyButtonOverrideAspectForeground =
    LegendOverrideAspect<LegendCopyButtonThemeNullable>(
      _$LegendCopyButtonOverrideSelectForeground,
    );

/// Resolves [LegendCopyButton.confirmationColor] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
Color _$LegendCopyButtonSelectConfirmationColor(LegendThemeData data) =>
    data
        .componentOf<LegendCopyButtonThemeNullable>(LegendCopyButton)
        ?.confirmationColor ??
    ColorRef.secondary(data.tokens);
const _$LegendCopyButtonAspectConfirmationColor = LegendThemeAspect(
  _$LegendCopyButtonSelectConfirmationColor,
);
Object? _$LegendCopyButtonOverrideSelectConfirmationColor(
  LegendCopyButtonThemeNullable data,
) => data.confirmationColor;
const _$LegendCopyButtonOverrideAspectConfirmationColor =
    LegendOverrideAspect<LegendCopyButtonThemeNullable>(
      _$LegendCopyButtonOverrideSelectConfirmationColor,
    );

/// Resolves [LegendCopyButton.glyphSize] through the
/// registry and the token defaults (levels 4+3) — the
/// comparator behind its rebuild aspect and listenable
/// (RFC-002 R12).
double _$LegendCopyButtonSelectGlyphSize(LegendThemeData data) =>
    data
        .componentOf<LegendCopyButtonThemeNullable>(LegendCopyButton)
        ?.glyphSize ??
    SizeRef.iconSm(data.tokens);
const _$LegendCopyButtonAspectGlyphSize = LegendThemeAspect(
  _$LegendCopyButtonSelectGlyphSize,
);
Object? _$LegendCopyButtonOverrideSelectGlyphSize(
  LegendCopyButtonThemeNullable data,
) => data.glyphSize;
const _$LegendCopyButtonOverrideAspectGlyphSize =
    LegendOverrideAspect<LegendCopyButtonThemeNullable>(
      _$LegendCopyButtonOverrideSelectGlyphSize,
    );

/// Distinct-until-changed per-field change streams over a
/// theme source (RFC-002 R12.4) — for animation and
/// imperative consumers that want theme changes without any
/// widget rebuild. Bind `source` to the app theme
/// controller (any [Listenable]) and `data` to its
/// [LegendThemeData] getter; dispose the returned selector
/// when done. Values resolve through registry + token
/// defaults (constructor params and subtree overrides are
/// element-tree concerns and have no controller-level
/// equivalent).
abstract final class LegendCopyButtonThemeListenables {
  /// Change stream of the resolved [LegendCopyButtonTheme.foreground].
  static ValueListenable<InteractiveColors> foreground(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendCopyButtonSelectForeground);

  /// Change stream of the resolved [LegendCopyButtonTheme.confirmationColor].
  static ValueListenable<Color> confirmationColor(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(
    source,
    data,
    _$LegendCopyButtonSelectConfirmationColor,
  );

  /// Change stream of the resolved [LegendCopyButtonTheme.glyphSize].
  static ValueListenable<double> glyphSize(
    Listenable source,
    LegendThemeData Function() data,
  ) => LegendThemeSelector(source, data, _$LegendCopyButtonSelectGlyphSize);
}

/// In-library resolver (RFC-002 R1): re-lists the themed
/// fields so the widget author never does — build calls
/// `_theme(context)` (`widget._theme(context)` from a State).
extension _$LegendCopyButtonThemeResolve on LegendCopyButton {
  /// [LegendCopyButtonTheme.of] with this widget's constructor params as
  /// level 1.
  LegendCopyButtonTheme _theme(BuildContext context) =>
      LegendCopyButtonTheme.of(
        context,
        LegendCopyButtonThemeNullable(
          foreground: foreground,
          confirmationColor: confirmationColor,
          glyphSize: glyphSize,
        ),
      );

  /// Resolves ONLY [LegendCopyButton.foreground] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._foreground(context)`).
  InteractiveColors _foreground(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendCopyButtonThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendCopyButtonAspectForeground);
    LegendThemeOverride.depend<LegendCopyButtonThemeNullable>(
      context,
      _$LegendCopyButtonOverrideAspectForeground,
    );
    return _$LegendCopyButtonSelectForeground(
      data,
    ).merge(override?.foreground).merge(foreground);
  }

  /// Resolves ONLY [LegendCopyButton.confirmationColor] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._confirmationColor(context)`).
  Color _confirmationColor(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendCopyButtonThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendCopyButtonAspectConfirmationColor);
    LegendThemeOverride.depend<LegendCopyButtonThemeNullable>(
      context,
      _$LegendCopyButtonOverrideAspectConfirmationColor,
    );
    return confirmationColor ??
        override?.confirmationColor ??
        _$LegendCopyButtonSelectConfirmationColor(data);
  }

  /// Resolves ONLY [LegendCopyButton.glyphSize] (full
  /// four-level chain), registering just this field's
  /// rebuild aspect (RFC-002 R12.3) — for widgets consuming
  /// one property. When a top-level tear-off shares the
  /// name, call it receiver-qualified
  /// (`this._glyphSize(context)`).
  double _glyphSize(BuildContext context) {
    final data = LegendTheme.read(context);
    final override = LegendThemeOverride.read<LegendCopyButtonThemeNullable>(
      context,
    );
    LegendTheme.depend(context, _$LegendCopyButtonAspectGlyphSize);
    LegendThemeOverride.depend<LegendCopyButtonThemeNullable>(
      context,
      _$LegendCopyButtonOverrideAspectGlyphSize,
    );
    return glyphSize ??
        override?.glyphSize ??
        _$LegendCopyButtonSelectGlyphSize(data);
  }
}

/// Auto-detected State wiring (RFC-002 R13): [_LegendCopyButtonState]
/// is this file's `State<LegendCopyButton>`, so its
/// build reads the resolved theme as a plain `theme`
/// getter — zero visible wiring. A same-named instance
/// member (e.g. from [_$LegendCopyButtonThemeState])
/// wins over this extension.
extension _$LegendCopyButtonThemeOn_LegendCopyButtonState
    on _LegendCopyButtonState {
  LegendCopyButtonTheme get theme => widget._theme(context);
}

/// Explicit State wiring (RFC-002 R13): mix onto any
/// `State<LegendCopyButton>` for the `theme` getter as a
/// real, overridable inherited member — no State-class
/// detection involved.
mixin _$LegendCopyButtonThemeState on State<LegendCopyButton> {
  LegendCopyButtonTheme get theme => widget._theme(context);
}

/// Opt-in two-argument build base (RFC-002 R13, opt-in
/// base): `class LegendCopyButton extends
/// _$LegendCopyButtonBase` receives the resolved
/// [LegendCopyButtonTheme] as a build parameter. Plain-widget forms stay
/// the default; there is no stateful two-argument variant.
abstract class _$LegendCopyButtonBase
    extends LegendStatelessWidget<LegendCopyButtonTheme> {
  const _$LegendCopyButtonBase({super.key});

  InteractiveColors? get foreground;
  Color? get confirmationColor;
  double? get glyphSize;

  @override
  LegendCopyButtonTheme resolveThemeOf(BuildContext context) =>
      LegendCopyButtonTheme.of(
        context,
        LegendCopyButtonThemeNullable(
          foreground: foreground,
          confirmationColor: confirmationColor,
          glyphSize: glyphSize,
        ),
      );
}
