// GENERATED by legend_gen v0.2.0-dev.0 — do not edit.
// Source: legend_markdown.dart
// ignore_for_file: type=lint, unused_element

import 'package:legend_ui/legend_ui.dart';

/// Theme docs manifest for `LegendMarkdown`
/// (RFC-002 R9): one entry per themed variable, extracted
/// from the dartdoc in legend_markdown.dart.
const List<LegendDocEntry> legendMarkdownDocEntries = [
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'h1Style',
    type: 'TextStyle?',
    doc: 'Style of `#` headings.',
    defaultDescription: 'TextRef.h1',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'h2Style',
    type: 'TextStyle?',
    doc: 'Style of `##` headings.',
    defaultDescription: 'TextRef.h2',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'h3Style',
    type: 'TextStyle?',
    doc: 'Style of `###` headings.',
    defaultDescription: 'TextRef.h3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'h4Style',
    type: 'TextStyle?',
    doc: 'Style of `####` headings.',
    defaultDescription: 't.typography.b1.copyWith(fontWeight: FontWeight.w600)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'h5Style',
    type: 'TextStyle?',
    doc: 'Style of `#####` headings.',
    defaultDescription: 't.typography.b2.copyWith(fontWeight: FontWeight.w600)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'h6Style',
    type: 'TextStyle?',
    doc: 'Style of `######` headings.',
    defaultDescription: 't.typography.b3.copyWith(fontWeight: FontWeight.w600)',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'bodyStyle',
    type: 'TextStyle?',
    doc: 'Base style of paragraphs, list items, quotes, and table cells.',
    defaultDescription: 'TextRef.b1',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'codeStyle',
    type: 'TextStyle?',
    doc: 'Monospace style of inline code and fenced code blocks.',
    defaultDescription:
        't.typography.b2.copyWith(fontFamily: \'monospace\', fontFamilyFallback: const [\'Menlo\', \'Courier\'])',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'codeBackground',
    type: 'Color?',
    doc: 'Fill behind inline code and fenced code blocks.',
    defaultDescription: 'ColorRef.background2',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'blockquoteBarColor',
    type: 'Color?',
    doc: 'Color of the bar running down a blockquote\'s leading edge.',
    defaultDescription: 'ColorRef.background3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'blockquoteInset',
    type: 'double?',
    doc: 'Gap between the blockquote bar and the quoted content.',
    defaultDescription: 'SizeRef.md',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'linkColor',
    type: 'Color?',
    doc: 'Color of link text and its underline.',
    defaultDescription: 'ColorRef.primary',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'markerColor',
    type: 'Color?',
    doc: 'Color of list bullets and numbers.',
    defaultDescription: 'ColorRef.foreground2',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'listIndent',
    type: 'double?',
    doc: 'Width of the marker gutter each list level indents by.',
    defaultDescription: 'SizeRef.lg',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'tableBorderColor',
    type: 'Color?',
    doc: 'Color of table grid lines.',
    defaultDescription: 'ColorRef.background3',
    group: 'component',
  ),
  LegendDocEntry(
    owner: 'LegendMarkdown',
    name: 'blockSpacing',
    type: 'double?',
    doc: 'Vertical gap between top-level blocks.',
    defaultDescription: 'SizeRef.md',
    group: 'component',
  ),
];
